naver/arcus-java-client

src/main/java/net/spy/memcached/AdminConnectTimeoutException.java, src/main/java/net/spy/memcached/CacheManager.java
Arcus java client 시작 시에, 
Arcus admin인 ZK 연결 요청이 connect timeout(2초)안에 완료되지 않으면,
AdminConnectTimeoutException이 발생하도록 하였습니다.
따라서, 사용자가 현재의 이슈 상황을 정확히 이해할 수 있게 됩니다.
=> Throw AdminConnectTimeoutException if connecting to arcus admin timed out.

src/main/java/net/spy/memcached/CacheManager.java
Refer to issue #12 of naver/arcus-java-client.
=> Change ZK_SESSION_TIMEOUT from 5 seconds to SESSION_TIMEOUT.

src/main/java/net/spy/memcached/DefaultConnectionFactory.java
DEFAULT_OPERATION_TIMEOUT : 1000 -> 700L
DEFAULT_BULKSERVICE_SINGLE_OP_TIMEOUT : 1000L -> 700L 
로 수정했습니다.
=> change default opration timeout value

src/main/java/net/spy/memcached/collection/CollectionBulkStore.java, src/main/java/net/spy/memcached/collection/CollectionPipedStore.java, src/main/java/net/spy/memcached/collection/SetPipedExist.java
bulk 혹은 pip operation 이 swithcover 에 의해 master 에서 slave 로 이동되는 경우,
전체 operation 이 재수행되는 것이 아니라 가장 마지막에 수행된 operation 의 다음부터 처리될 수 있도록 수정한 내용입니다.
@aiceru, @jhpark816 review 부탁드립니다.
=> modify that next index will be processed when bulk and pipe opeartion moved by switchover

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/OperationFactory.java, src/main/java/net/spy/memcached/collection/BTreeDelete.java, src/main/java/net/spy/memcached/collection/CollectionDelete.java, src/main/java/net/spy/memcached/collection/CollectionExist.java, src/main/java/net/spy/memcached/collection/ListDelete.java, src/main/java/net/spy/memcached/collection/SetDelete.java, src/main/java/net/spy/memcached/collection/SetExist.java, src/main/java/net/spy/memcached/ops/CollectionExistOperation.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolSetDeleteTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolSetExistTest.java
- CollectionDelete 의 기존 `data` member variable 을`additionalArgs` 로 naming 변경
- 해당 변수의 setter method 를 삭제하고 생성자에 transcoder 를 추가
- 추후 오사용 방지 및 이미 기존의 생성자가 `T value` 를 포함하고 있어 transcoder 를 함께 가지고 있다가 `getAdditionalArgs` (수정 전의 `getData` 역할) 에서 byte encoding 하여 return 하도록 하였습니다.
근거 논의 사항은 [Closed PR#66](https://github.com/naver/arcus-java-client/pull/66) 참조.
=> fixed CollectionDelete/Exist to accept additional ascii protocol argument

src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java, src/main/java/net/spy/memcached/collection/BTreeGet.java, src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java, src/main/java/net/spy/memcached/collection/CollectionGet.java, src/main/java/net/spy/memcached/collection/ListGet.java, src/main/java/net/spy/memcached/collection/SetGet.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
Fixed CollectionGet and its subclasses to be able to accept additional arguments.
[CollectionDelete/Exist 와 마찬가지](https://github.com/naver/arcus-java-client/pull/67/files)로, map collection protocol support 를 위해 CollectionGet 에서도 additional argument 를 받을 수 있도록 수정합니다.
First reviewer
Final Reviewer
=> Fixed CollectionGet

src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
byte[] additionalArgs must not go through setArguments() method.
Instead, put it directly to ByteBuffer using bb.put().
=> Fixed bug in CollectionGetOperationImpl

src/test/manual/net/spy/memcached/MultibyteKeyTest.java
자꾸 번거롭게 해서 죄송합니다. ㅠ 필요없는 import 가 남아서 warning 을 발생시키고 있었네요
=> Remove unnecessary imports that raised mvn build warnings

pom.xml, src/main/java/net/spy/memcached/ArcusClientException.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/compat/log/LoggerFactory.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/main/java/net/spy/memcached/ops/OperationException.java, src/main/java/net/spy/memcached/plugin/LocalCacheManager.java, src/test/java/net/spy/memcached/OperationFactoryTestBase.java, src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetErrorTest.java, src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetIrregularEflagTest.java, src/test/manual/net/spy/memcached/btreesmget/SMGetErrorTest.java, src/test/manual/net/spy/memcached/collection/CollectionFutureTest.java, src/test/manual/net/spy/memcached/collection/btree/BopFindPositionWithGetTest.java, src/test/manual/net/spy/memcached/collection/btree/BopMutateTest.java, src/test/manual/net/spy/memcached/collection/btree/BopServerMessageTest.java, src/test/manual/net/spy/memcached/collection/list/LopServerMessageTest.java, src/test/manual/net/spy/memcached/collection/set/SopServerMessageTest.java
Fix from https://github.com/jam2in/arcus-task/issues/116
1. maven compiler 옵션에 build warning 발생시 error 로 취급하여 build failure 되도록 변경
2. test code 에 존재하던 build warning 제거 (기존에는 maven compiler 의 `showWarnings` 옵션이 default false 여서 나오지 않았던 warning 들입니다)
로컬에서 mvn clean install, mvn test 실행 완료 확인하였습니다. branch pull 해서 빌드해 보는 정도로 확인해 주시면 될 것 같습니다.
=> Refactoring: remove warnings

docs/06-btree-API.md, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/collection/BTreeMutate.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/test/manual/net/spy/memcached/collection/btree/BopMutateTest.java
bop incr/decr 에서 initial value를 설정할 수 있는 함수들을 추가했습니다.
null key혹은 음수 값이 들어왔을 때에 대해 exception을 발생시키는 코드를 추가해야할지 고민이 됩니다.
reviewer
=> Add bop incr/decr with initial value

src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java, src/main/java/net/spy/memcached/collection/CollectionStore.java, src/main/java/net/spy/memcached/collection/CollectionUpdate.java, src/main/java/net/spy/memcached/collection/Element.java, src/main/java/net/spy/memcached/collection/ElementFlagUpdate.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
elementFlag를 사용하는 데 있어, 아래 문제들을 해결하였습니다.
- elementFlag에 대한 정확한 validation check.
- eflag 값을 저장하는 경우는 0-length byte array를 허용하지 않음
- eflag 값을 삭제하는 경우만 0-length byte array를 허용
- bop update command string 생성 시에 noreply 와 value length의 순서가 바뀐 문제 해결
- 기타 코드 간결히 : ElementFlagUpdate 객체를 활용.
reviewer
=> Fix several mistakes in using elementFlag.

pom.xml
remove compiler options that make compiler to treat warnings as error
=> Remove compiler options "-Werror", "-Xlint"

docs/10-log-message.md, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/CollectionFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java
timeout 메시지 출력 시 time unit 이 함께 출력되지 않아 단위 확인에 어려움이 있어 메시지를 수정합니다.
https://github.com/naver/arcus-java-client/issues/100 이슈를 해결한 PR 입니다.
timeout duration이 누락된 곳은 단위와 함께 추가했습니다.
리뷰 부탁드립니다.
=> add timeunit and ommited duration at operation timeout log message

ChangeLog
=> Typo found : 'Extensice' -> 'Extensive'

docs/09-other-API.md, src/main/java/net/spy/memcached/protocol/ascii/FlushByPrefixOperationImpl.java
@jhpark816 
flush prefix에 대한 수정입니다.
key에 대한 validation check를 넣어야되나 고민을 했는데 그렇게 되면 exception을 던져줘야해서 기존 사용자들이 사용함에 문제가 있을 것 같아 넣지 않았습니다.
=> FIX: flush by prefix method return false when prefix does not exist

src/main/java/net/spy/memcached/ops/APIType.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MGetOperationImpl.java
@jhpark816 
get operation에 대해 optimize를 수행할 때
MGetOperation으로 인해 ClassCastException 발생에 대한 수정 입니다.
MGetOperationImpl, GetOperationImpl 모두 operation 에 대한 구현체로
MGetOperation 전용의 interface를 새로 만들어서 사용하는 것 보다
optimize 내부에서만 APIType을 구분하여 사용하는게 낫다고 판단했습니다.
=> FIX: ClassCastException error of optimize get operation(MGet to Get)

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java
shouldOptimize 사용에서,
optimize 대상이 되는 GetOperation 을 확인하는 과정 중
MGetOperation filtering이 모든 case를 확인할 수 있도록
수정하기 위한 PR 입니다.
=> FIX: check MGetOperation when get next Optimize Op

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java
binary protocol 일 경우, asyncGetBulk 요청에 대해
MGetOperation enable 여부를 확인하지 않고
항상 GetOperation 으로만 보내도록 동작합니다.
=> CLEANUP: do not check enable MGetOperation when use binary protocol

src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/CacheMonitor.java
ZK session expired 이후 reconnect 에서
실제로 reconnect에 성공 했지만,
cacheMonitor != null 로 인해 zkInitLatch.countDown()을 수행하지 못해
initZooKeeperClient() 에서 AdminConnectTimeoutException 이 발생하는 문제가 있습니다.
@jhpark816 
확인 요청 드립니다.
참고 : https://cwiki.apache.org/confluence/display/ZOOKEEPER/FAQ, https://github.com/jam2in/arcus-memcached-EE/issues/595
=> FIX: ZkInitLatch procession when reconnect with ZK session expired

src/main/java/net/spy/memcached/CacheManager.java
ZK reconnect 과정에서 연속으로 exception이 발생했을 때
zk == null 인 상태로 initZooKeeperClient() 를 수행하여
CacheManager thread가 종료되는 문제가 있었습니다.
ZK reconnect 과정에서 exception이 발생하면, 일정시간 sleep 후
reconnect 시도를 반복하도록 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
=> FIX: handling CacheManager exceptions for ZooKeeper

src/main/java/net/spy/memcached/CacheManager.java
client info 를 create 할 수 없을 때
exception 을 생성하도록 수정 했습니다.
(기존 코드로 원복하기 위한 수정 입니다.)
@jhpark816 
확인 요청 드립니다.
=> CLEANUP: throw exception when can't create the znode of client info

.travis.yml, mvnTestConf.json, src/test/java/net/spy/memcached/AsciiClientTest.java, src/test/java/net/spy/memcached/BinaryClientTest.java, src/test/java/net/spy/memcached/CancelFailureModeTest.java, src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java, src/test/java/net/spy/memcached/RedistributeFailureModeTest.java, src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
travis-ci test error에 대한 수정 입니다.
travis-ci 에서, memcached 를 사용 하면서
default port 중복 문제로 인한 에러가 발생 했었습니다.
arcus-java-client  test를 위한 arcus-memcached port를
default port를 회피하도록 수정 했습니다.
reviewer
확인 요청 드립니다.
=> TEST: fix travis-ci test error due to using memcached

src/main/java/net/spy/memcached/CacheManager.java
CacheManager log message 관련 수정 입니다.
Reconnect message에 CacheList 를 추가하고,
CacheManager 종료 시 shutdownRequested flag 세팅에 따라
log message level 과 내용을 다르게 출력하도록 했습니다.
@jhpark816 
확인 요청 드립니다.
=> CLEANUP: add CacheManager log message

.travis.yml, mvnTestConf.json, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/CacheMonitor.java, src/main/java/net/spy/memcached/ops/APIType.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java, src/test/java/net/spy/memcached/AsciiClientTest.java, src/test/java/net/spy/memcached/BinaryClientTest.java, src/test/java/net/spy/memcached/CancelFailureModeTest.java, src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java, src/test/java/net/spy/memcached/RedistributeFailureModeTest.java, src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
reviewer
MGetOperation 관련 commit
- [CLEANUP: do not check enable MGetOperation when use binary protocol](https://github.com/naver/arcus-java-client/commit/c06646bea7fbf4bbd643ff6a48564e37840d0e8f)
- [FIX: check MGetOperation when get next Optimize Op](https://github.com/naver/arcus-java-client/commit/a3944d895f17cdd590f8dd06b2fa46972dfe319b)
- [FIX: ClassCastException error of optimize get operation(MGet to Get)](https://github.com/naver/arcus-java-client/commit/eff908db7fd23543223e574dcea3b1c5a96b06d6)
=> FIX: Bug patch caused by CacheManager(v1.11.0)

src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
MemcachedNode 로 부터 replication switchover 응답을 받았을 때
CollectionPipedUpdate 연산에서 실패된 operation index를 기준으로
command를 만들어서 new master에게 보내도록 하는 기능이 빠져있었습니다.
다른 piped operation과 동일하게 next op index를 set 하는 방법으로
실패된 index 부터 command를 만들도록 수정 했습니다.
@minkikim89 @jhpark816 
확인 요청 드립니다.
=> FIX: when replication switchover, set next opindex of pipedUpdateOp

docs/02-arcus-java-client.md, pom.xml, src/main/java/net/spy/memcached/compat/log/AbstractLogger.java, src/main/java/net/spy/memcached/compat/log/DefaultLogger.java, src/main/java/net/spy/memcached/compat/log/Level.java, src/main/java/net/spy/memcached/compat/log/Log4JLogger.java, src/main/java/net/spy/memcached/compat/log/Logger.java, src/main/java/net/spy/memcached/compat/log/LoggerFactory.java, src/main/java/net/spy/memcached/compat/log/SLF4JLogger.java, src/main/java/net/spy/memcached/compat/log/SunLogger.java
original code: couchbase/spymemcached
- https://github.com/couchbase/spymemcached/commit/730fe4f285887ed074c78da84ef58a85bf8abd4d
couchbase/spymemcached의 net.spy.memcached.compat.log 패키지의 코드들을 그대로 적용했습니다.
SLF4J 지원 뿐만 아니라 Trace Logging Level이 추가됐습니다.
=> FEATURE: Adding support for SLF4J logging

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
reviewer
java client의 FAKE_SERVER_NODE 여부를 판단하는 방법에 오류가 있습니다.
fake server address를 변환 한 ipport string에 "/" 가 포함되어 있기때문에
fake server 여부를 address로 판별하기 위해 "/"를 포함하여 확인해야 합니다.
확인 요청 드립니다.
참고로, 기존코드에서 변경된 commit은 아래와 같습니다.
commit : https://github.com/naver/arcus-java-client/commit/2659175c7bdd8ead98a221255b09dabdfdafaa40
=> FIX: change FAKE_SERVER_NODE check method

docs/07-btree-API.md
bop smget 스펙 변경에 따라서 ATTR_MISMATCH response가
arcus-memcached 1.11.3 이후로는 발생하지 않습니다.
관련 내용을 btree document에 추가 했습니다.
@jhpark816 
확인 요청 드립니다.
=> DOC: Changed ATTR_MISMATCH response description according to spec change of 'bop smget'.

src/main/java/net/spy/memcached/collection/BTreeMutate.java
java client의 asyncBopIncr, asyncBopDecr 명령에서,
element가 없을 때 element를 생성해주기 위한 initial 변수의 범위가 잘못되었습니다.
document에 따라서, 0 이상이면 element를 생성하도록 수정 했습니다.
@jhpark816 
확인 요청 드립니다.
=> FIX: asyncBopIncr,asyncBopDecr command initial range problem

src/test/java/net/spy/memcached/CancelFailureModeTest.java, src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
ZK를 사용할 때 두 코드에서 문제가 발생합니다.
- CancelFailureModeTest.java의 testQueueingToDownServer 테스트에서 테스트가 끝난뒤 teardown이 호출되는데 이 때 super.teardown이 호출되면 ARCUS_HOST와 연결을 맺고 flush명령을 날리는데 ARCUS_HOST가 존재하지 않아 flush 명령이 실패하여 테스트가 실패합니다.
- MemcachedClientConstructorTest.java의 testVarargConstructor 테스트는 USE_ZK가 설정되어있어도 cache_list를 사용하지 않고 ARCUS_HOST를 사용해 연결을 시도하고, 연결이 정상적으로 되지 않아 테스트에 실패합니다. 이에 USE_ZK시에는 해당 테스트를 시도하지 않도록 수정하였습니다.
=> TEST: fix travis failed test case when USE_ZK is true

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/protocol/ascii/VersionOperationImpl.java
version operation이 input queue overflow로 인해 exception이 나는 경우를 없애기 위한 PR입니다.
handleIO에서 node.getVersion==null일 경우 operation을 보내도록 수정하려 했지만, 그렇게 구현할 경우 operation을 이미 보낸 상황임에도 아직 version이 set 되지 않은 상태라면 계속해서 operation을 보내는 문제가 있어 HashSet을 사용하여 version operaation을 보내야하는 상태의 노드를 구분하도록 하였습니다.
=> CLEANUP: refactor version operation handling

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/QueueOverflowTest.java
1. readQ 오버플로우시 readQ에 있던 오퍼레이션들이 다시 inputQ로 재분배되어 발생하는 오버플로우 문제가 발생하였고 이를 해결하기 위해 FailureMode를 Cancel로 설정하였습니다.
2. 위의 FailureMode 변경으로 readQ 오버플로우 후 inputQ 오버플로우 문제는 해결했지만 이후 바로 set 연산을 실행하면 reconnect 중이기 때문에 cancel이 발생합니다. 이를 해결하기 위해 reconnectDelay를 1로 설정하고 set 이전에 1.5초간 sleep 하도록하여 reconnect 완료 후 연산 처리를 하도록 수정하였습니다.
3. testOverflowingReadQueue에서 set을 한 후에 이에 대해 asyncGet 하며 readQ 오버플로우를 발생시키는데 FailureMode를 Cancel로 설정하면서 MemcachedNode 연결 이전에 set연산을 실행하여 client.set 부분에서 cancel이 되는 현상이 발생합니다. 이에 set 연산 앞에 100ms sleep 하도록 코드 삽입하였습니다.
4. testOverflowingReadQueue에서 asyncGet을 1000번 반복하여 오버플로우 발생을 확인하는데 테스트를 여러번 해본 결과 간헐적으로 1000번 반복에도 오버플로우가 발생하지 않는 경우가 발생하여 10000번 반복하도록 수정하였습니다.
추가) OverflowingWriteQueueu에서도 기존 1000번 테스트해서 overflow가 발생하지 않는 현상이 발생하여 10000으로 수정하였습니다.
=> TEST: fix QueueOverflowTest fail case

pom.xml
ZooKeeper의 DNS Lookup 이슈(https://issues.apache.org/jira/browse/ZOOKEEPER-1506  - 갱신된 IP address를 참조하지 않는 현상)를 반영하기 위한 ZK 라이브러리 업데이트입니다.
또한 
Github의 arcus-java-client 프로젝트에 대한 ACL 관련 보안 경고(https://zookeeper.apache.org/security.html#CVE-2019-0201)로 3.4.14 버전으로 업데이트하였습니다.
=> FEATURE: upgrade zookeeper version 3.4.5=>3.4.14

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/CollectionFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/main/java/net/spy/memcached/ops/BaseOperationFactory.java, src/main/java/net/spy/memcached/ops/Operation.java, src/main/java/net/spy/memcached/ops/OperationState.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java, src/test/java/net/spy/memcached/internal/CheckedOperationTimeoutExceptionTest.java
cancel된 Operation이 Operation의 write buffer에 기록되지 않았다면, write을 스킵하는 내용입니다.
기존 코드의 로직을 아래와 같이 정리합니다.
1. 응용이 Operation을 요청하고, future.get을 waiting함
2. future.get의 타임아웃이 발생되어, future.cancel 호출
3. MemcachedConnection의 handleIO에서 Operation write 준비
https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/MemcachedConnection.java#L791
4. MemcachedNode의 writeQ에 가장 앞단에 위치한 Operation을 꺼내서 status(cancel 유무)를 확인하지 않고, Operation의 write buffer에 기록
https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java#L281
5. inputQ, writeQ에 남아있는 Operation들은 status(cancel 유무)를 확인하고, cancel이 되었다면, writeQ에 제거
https://github.com/naver/arcus-java-client/blob/master/src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.jav …
=> ENHANCE: Skip the canceled operation not has been written to buffer.

docs/01-arcus-cloud-basics.md, docs/04-list-API.md, docs/05-set-API.md, docs/06-map-API.md, docs/07-btree-API.md, src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java, src/test/manual/net/spy/memcached/collection/CollectionMaxElementSize.java
element 최대 크기 변경하였습니다.
@jhpark816 
실제 서버에서는 16KB가 기본 제약인데,
java docs에는 32KB로 써야하는 상태인데,
그대로 가도 괜찮을까요?
아니면, 캐시서버는 16KB가 기본인 것을 언급해야할까요?
=> CLEANUP: change max element size

src/test/java/net/spy/memcached/ConsistentHashingTest.java
간헐적으로 테스트 실패하고, 이유에 대해 파악해둔 상태이기 때문에
우선 테스트에서 제외시키도록 하고 이후에 수정하도록 합니다.
junit 공식 가이드를 보면 @Ignore를 함수별로도 붙일 수 있다고 하여
testLargeSet만 ignore 하려했는데
java client의 경우 TestCase를 상속해서 쓰면서 함수에 Ignore를 붙여 쓸 수 없게 된 것
같습니다.(자세한 이유는 더 찾아봐야할 것 같습니다. TestCase를 상속하지 않을 경우
함수마다 @Test 어노테이션을 붙여서 테스트합니다.)
일단은 클래스 전체 테스트를 스킵하고, 이후에 수정하면 될 것 같아 이대로 PR합니다.
=> TEST: ignore ConsistentHashingTest

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
https://github.com/jam2in/arcus-works/issues/151 이슈에 대한 PR입니다.
제거된 노드에 대한 readQ의 operation들을 제거하였습니다.
=> ENHAHCE: destroy read queue of removed node

src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/util/ArcusKetamaNodeLocatorConfiguration.java, src/main/java/net/spy/memcached/util/ArcusReplKetamaNodeLocatorConfiguration.java
https://github.com/naver/arcus-java-client/issues/204 이슈에 대한 PR입니다.
현재 테스트 중에서 이러한 collision 현상이 발생할 수 있는 테스트가 ConsistentHashingTest이고
간헐적으로 collision 현상으로 인해 해당 테스트가 실패하여 현재는 ignore 처리한 상태입니다.
이번 PR의 경우 코드 구현상 복잡해지는 부분이 있어서 실제 사용중인 ArcusKetamaNodeLocator와 ArcusReplKetamaNodeLocator에 대해서는 collision 관련 수정을 하였고,
KetamaNodeLocator에 대해서는 수정을 하지 않았습니다.
따라서, ConsistentHashingTest 테스트는 여전히 실패할 수 있는 상황입니다.
개인적으로는 KetamaNodeLocator에 대해서는 collision 처리를 하지 않아도 될 것 같기 때문에
기존에 있던 ConsistentHashingTest는 그대로 ignore 시키던지 아니면 ArcusKetamaNodeLocator를 테스트 하도록 수정하면 될 것 같은데, 그에 대한 의견도 주시면 감사하겠습니다.
=> CLEANUP: solve hash point collision with comparison socket address of node

checkstyle.xml
[google](https://github.com/checkstyle/checkstyle/blob/checkstyle-8.31/src/main/resources/google_checks.xml), [spymemcached](https://github.com/couchbase/spymemcached/blob/2.12.3/etc/checkstyle.xml) 기반의 [checkstyle](https://checkstyle.sourceforge.io/)을 적용하였습니다.
코드 수정이 필요한 모듈은 주석처리를 하였으며,
코드 수정이 필요하지 않은 모듈(validation checking 통과)은 전부 적용하였습니다.
주석 처리된 모듈들은 추후에 하나씩 풀어나가면서 PR을 올리도록 하겠습니다.
checkstyle 실행은
`mvn checkstyle:checkstyle` 또는 `mvn validate` 명령을 입력하시면 checkstyle 결과가 출력됩니다. 
또한 `mvn install` 시에 violation error가 발생하면 빌드가 되지 않도록 처리하였습니다.
```
$ mvn install -DskipTests=true
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------< com.navercorp.arcus:arcus-java-client >----------------
[INFO] Building Arcus Java Client 1.12.0
[INFO] --------------------------------[ jar …
```
=> FEATURE: apply checkstyle

pom.xml
checkstyle PR( https://github.com/naver/arcus-java-client/commit/afc6a912354743b8dc6d984bb1c980f7c96664c4 )을 rebase하다가 실수로 pom.xml 파일을 누락하였습니다.
이전 PR에 pom.xml 파일이 없어 checkstyle이 동작을 하지 않을 것이며 CI와도 연동이 되지 않을 것입니다.
이를 위해 pom.xml 파일에 대해 PR 올립니다.
=> FEATURE: add maven plugin of checkstyle

checkstyle.xml, src/test/java/net/spy/memcached/ProtocolBaseCase.java
client에 적용된 checkstyle이 `src/main/**.java` 코드에만 반영되는 문제가 있네요.
테스트 `src/test/**.java` 코드에도 checkstyle을 적용할 수 있도록 수정하였습니다.
이와 함께 테스트 코드에서 기존 모듈의 violation error가 발생되는 곳이 있어 코드 수정하였습니다.
=> FEATURE: apply checkstyle to test sources

pom.xml
mvn install시 checkstyle이 실행이 안되는 문제가 있었습니다.
현재 violation level을 warning으로 설정하였는데,
실제로 검사할 때는 error level 부터 검사를 하여서, violation warning이 발생하여도 mvn install은 성공하게됩니다. 따라서 현재 상태에서 CI와 연동되지 않는 문제가 있습니다.
이전에 rebase 하면서 해당 설정을 누락한 듯 싶습니다.
이에 대해 warning level 까지 검사를 할 수 있도록 수정하였습니다.
=> FEATURE: apply warning violation severity in checkstyle

.travis.yml
forked 저장소의 빌드는 PR을 제외하고 이메일 알림이 가지 않도록 했습니다.
=> FIX: disable email notification in forked repo except PR

src/main/java/net/spy/memcached/collection/SetPipedExist.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java
sop exist 는 read operation 으로 switchover 가 발생하지 않으므로 이에 대한 처리 코드를 제거하였습니다.
@minkikim89 리뷰 요청드립니다.
=> CLEANUP: don't occur switchover in sop exist operation.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/KetamaConnectionFactory.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/ops/ArrayOperationQueueFactory.java, src/main/java/net/spy/memcached/ops/LinkedOperationQueueFactory.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java, src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java, src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java, src/main/java/net/spy/memcached/transcoders/WhalinTranscoder.java
LineLength checkstyle 모듈 적용을 위해 에디터(eclipse)에서 자동생성하는 의미 없는 주석을 제거하였습니다.
=> CLEANUP: remove non-javadoc comments

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java, src/test/manual/net/spy/memcached/bulkoperation/BulkDeleteTest.java
https://github.com/naver/arcus-java-client/issues/229 이슈에 대한 PR입니다.
기존 bulkService 코드는 사용하는 쪽만 주석으로 해두고 코드는 그대로 둔 상태입니다.
코드를 bopInsertBulk 기준으로 수정하고 보니 기존 bulkService와 동작이 달라지는 부분들이 생기네요.
1. DEFAULT_LOOP_LIMIT와 같은 연산양 조절 기능이 사라짐
2. singleOpTimeout에 따른 일부 연산 timeout 처리 기능이 사라짐
=> CLEANUP: refactor asyncSetBulk, asyncDeleteBulk

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/GetFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java, src/main/java/net/spy/memcached/ops/CASOperationStatus.java, src/main/java/net/spy/memcached/ops/CancelledOperationStatus.java, src/main/java/net/spy/memcached/ops/OperationStatus.java, src/main/java/net/spy/memcached/ops/StatusCode.java, src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java, src/main/java/net/spy/memcached/protocol/GetCallbackWrapper.java, src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CASOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/DeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/FlushByPrefixOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/FlushOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/StatsOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/VersionOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/MutatorOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/OperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/SASLBaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/SASLMechsOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/VersionOperationImpl.java
https://github.com/naver/arcus-java-client/issues/226#issuecomment-638697151 이슈 관련 PR 입니다.
이번에 deleteBulk 연산을 release 내용에 넣을 예정이고, 여기서 OperationStatus를 사용할 수 있도록 할 예정이기 때문에 이 PR에서 OperationFuture에 OperationStatus를 추가하는 작업 진행했습니다. 외부 API 자체는 아직 타입을 바꾸지 않았기 때문에 아직 응용에서 OperationStatus를 사용하지는 못하는 상태입니다. 
코드 수정에는 spymemcached 코드를 참고하였습니다.
=> CLEANUP: add OperationStatus to OperationFuture

src/main/java/net/spy/memcached/MemcachedConnection.java
같은 node에 대해 연속해서 reconnect 요청이 될 경우,
handleIO의 reconnect 처리 타이밍에 따라 이미 연결이 완료된 node에 대해
기존 연결을 해제하지 않고 새로운 연결을 생성하는 동작이 수행되는 문제가 있었습니다.
이러한 동작은 fd leak을 발생시키게 되며, 반복될 때 마다 fd가 증가하는 문제를 발생시키므로
reconnect 처리 동작에서 node의 channel이 null일 경우만 연결을 생성하도록 변경 했습니다.
@jhpark816 
확인 요청 드립니다.
=> FIX: skipping reconnect request that already reconnected

src/main/java/net/spy/memcached/CacheManager.java
CacheManager에서 address string 연결시, String 객체를 계속해서 생성하는 문제가 있어 StringBuilder를 사용하여 최적화하였습니다.
=> ENHANCE: using stringbuilder in CachaManager.getAddressListString

src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java
Write type의 operation 중 replication SWITCHOVER / REPL_SLAVE
응답에 대한 return 처리가 빠져있는 operation이 있어 추가 했습니다.
return 처리가 되지 않을 경우 위 응답에 대해 아래와 같은 로그를 출력하게 됩니다.
`[Memcached IO] - Unhandled state: {OperationStatus success=false:  REPL_SLAVE}`
Write type의 replication response 처리는 https://github.com/naver/arcus-java-client/commit/8c4776c071094dd3b510a07d2c0368e6ea7af58c commit에서 일괄적으로 추가되었는데,
두 operation만 빠진 것 같습니다.
@hjyun328 @minkikim89 @jhpark816 
확인 요청 드립니다.
=> FIX: add missing SWITCHOVER, REPL_SLAVE response handling

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/BinaryConnectionFactory.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java, src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java, src/test/java/net/spy/memcached/MemcachedConnectionTest.java, src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java
pool에 대한 정보를 MemcachedNode toString 결과에 추가하였으며,
handleIO에서 connectable 이벤트로 selectionKey 처리할 때 로깅하는 부분을 selectionKey가 아닌 MemcachedNode 정보를 출력하도록 수정하였습니다.
=> CLEANUP: add pool information to MemcachedNode toString

src/main/java/net/spy/memcached/ArcusClient.java
일부 bulk 연산에 isDone 함수가 override 되어있지 않아 추가하였습니다.
현재 상태에서 해당 연산들에 대해 isDone 함수를 호출 할 시 assert 문에 걸려서
exception이 발생합니다.
=> FIX: add override code for isDone function to some bulk code

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
bulk 연산들의 return future들의 isDone 함수를 리팩토링하였습니다.
그 과정에서 FrontCacheGetFuture의 경우 isDone이 항상 true인 것이 맞아보여 이 부분도 수정하였습니다.
=> CLEANUP: refactor bulk operations' isDone function

src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
예전에 hash collision 관련 수정하면서 버그가 있었네요.
remove 시에 잘못된 객체를 사용하여 복제 모드에서 group 이 삭제되면 exception이 발생하는 버그가 있습니다.
=> FIX: incorrect deleteion of replication nodeSet

src/main/java/net/spy/memcached/AddrUtil.java, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplNodeAddress.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/AddrUtilTest.java, src/test/java/net/spy/memcached/ArcusTimeoutTest.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
기존에 캐시노드가 존재하지 않을 시 fake node를 사용하여 실제 노드가 존재하는 것처럼 동작하도록 하였으나,
이에 대한 처리가 매번 버그를 유발하여 이를 삭제하도록 합니다.
=> CLEANUP: remove fake node

src/test/java/net/spy/memcached/ProtocolBaseCase.java
old cache server 와의 호환성 보장을 위해 E2BIG을 CLIENT or SERVER 로 확인하도록 변경하였습니다.
=> CLEANUP: ensure compatibility about changing E2BIG

pom.xml, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/CacheMonitor.java, src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java, src/main/java/net/spy/memcached/collection/Element.java, src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java
maven 배포시 발생되는 javadoc의 warning 메시지를 제거하였습니다.
```
[WARNING] /Users/hjyun/Workspace/arcus-java-client/src/main/java/net/spy/memcached/CacheMonitor.java:74: warning: no @param for children
[WARNING] void commandCacheListChange(List<String> children);
[WARNING] ^
[WARNING] /Users/hjyun/Workspace/arcus-java-client/src/main/java/net/spy/memcached/CacheMonitor.java:53: warning: no @param for cacheListZPath
[WARNING] public CacheMonitor(ZooKeeper zk, String cacheListZPath, String serviceCode,
[WARNING] ^
[WARNING] /Users/hjyun/Workspace/arcus-java-client/src/main/java/net/spy/memcached/CacheMonitor.java:153: warning: no @return
[WARNING] public boolean isDead() {
[WARNING] ^
...
```
=> DOC: fixed the javadoc generation warnings

docs/03-key-value-API.md
doc 문서의 Value 설명 부분이 잘못되어
이에 대한 수정을 위한 PR 입니다.
기존 문서 에서 `Value는 최대 1Mb까지 저장할 수 있다.`로 설명된 부분을
`Cache item의 최대 크기는 1MB이다.`로 변경 했습니다.
@jhpark816
확인 요청 드립니다.
=> DOC: change the description of the max item size

src/main/java/net/spy/memcached/ArcusReplNodeAddress.java, src/main/java/net/spy/memcached/MemcachedConnection.java
replication switchover response read 와 다른 group에 의한 cache list update가
동시에 발생 할 경우, switchover를 여러번 반복 수행하는 문제가 발생할 수 있습니다.
이유는 switchover response read 로 group switchover 를 수행 했지만,
아직 node는 cache list update를 하지 않은 상태에서
다른 group cache list update에 의해 old cache list를 read하게 되면서
또 다시 switchover가 발생 했다고 판단하고 또 다시 switchover를 수행하게 됩니다.
위 상황에 대한 해결을 위해 CacheManager가 cache list를 read하면
replication cluster일 경우 이전 cache list와 비교하여
변경된 group만 cache list를 반영하도록 수정 했습니다.
@minkikim89 @hjyun328 
확인 요청 드립니다.
=>  ENHANCE: reflected only the changed groups in hash ring

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MemcachedNodeROImplTest.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
https://github.com/naver/arcus-java-client/issues/304 에 대한 PR입니다.
new connection이 생성되면 바로 해시링에 참여하고, 이러한 첫번째 접속 시도일 때는
connected 상태가 아니어도 connection에 연산이 삽입되도록 하였습니다.
만약 connected 상태가 되기전에 큐가 가득차게 된다면 queue overflow exception이 발생할 수 있습니다.
=> CLEANUP: do not cancel the operations if it is first connecting

checkstyle-suppressions.xml, docs/03-key-value-API.md, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java, src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java, src/test/manual/net/spy/memcached/ops/OperationStatusTest.java
#226 에 대한 pr입니다.
[Key-Value Item 연산](https://github.com/naver/arcus-java-client/blob/master/docs/arcus-java-client-user-guide.md) API 목록을 참고하여 key-value 연산들의 반환 타입인 Future을 OperationFuture로 변경하였습니다.
인터페이스를 제외한 구현클래스의 반환타입을 모두 변경하였습니다.
인터페이스의 반환타입을 변경하지 않은 이유는 Mock을 이용한 테스트에 오류가 발생하여 테스트가 실패하는 문제가 발생했기 때문입니다.
해당 문제를 해결하기 위하여 spymemcached를 참고하였고, spymemcached에서도 OperationFuture의 반환 타입은 구현 클래스에서만 적용이 되어 있었습니다.
아래는 참고한 spymemcached의 내용 중 일부입니다.
- MemcachedClientIF
```java
Future<Boolean> set(String key, int exp, Object o);
Future<Boolean> set(String key, int exp, Object o);
```
- MemcachedClient
```java
@Override
public OperationFuture<Boolean> set(String key, int exp, Object o) {
return asyncStore(StoreType.set, key, exp, o, transcoder);
}
@Override
public OperationFuture<Boolean> …
```
=> CLEANUP: change the return type Future to OperationFuture

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MemcachedNodeROImplTest.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
#305  에 대한 pr입니다.
#321 의 pr을 close하고 새로 pr하였습니다.
nodename을 이용하여 정보를 보강하도록 했습니다. 수정된 결과로는
- DNS name이 존재할 시 (hostname출력)
```
Cancelled (inactive node: (ArcusClient /127.0.0.1:11211-localhost))
```
- DNS name이 존재하지 않을 시 (ip출력)
```
Cancelled (inactive node: (ArcusClient /1.255.51.181:11912-1.255.51.181))
```
- hostname을 추가하여 테스트가 깨지는 경우가 몇개 있어서 테스트도 같이 수정하였습니다.
리뷰 요청드립니다.
@hjyun328
=> ENHANCE: add node information to the cancellation message

docs/03-key-value-API.md, src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedClientIF.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/OperationFactory.java, src/main/java/net/spy/memcached/ops/APIType.java, src/main/java/net/spy/memcached/ops/BaseOperationFactory.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java, src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java, src/main/java/net/spy/memcached/protocol/ascii/GetsOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MGetsOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java, src/main/java/net/spy/memcached/transcoders/TranscodeService.java, src/test/java/net/spy/memcached/BinaryClientTest.java, src/test/java/net/spy/memcached/MockMemcachedNode.java, src/test/java/net/spy/memcached/OperationFactoryTestBase.java, src/test/java/net/spy/memcached/ProtocolBaseCase.java, src/test/java/net/spy/memcached/protocol/binary/OperationFactoryTest.java
mgets 지원 
issue : #320 
mgets 지원을 위하여 APITYPE에 MGETS를 추가하였으며, 노드 초기화시 해당 노드가 mgets를 지원할 수 있는지
enabeldMgets를 추가하여 지원하지 않을시엔 gets를 사용하도록 했습니다.
- asyncGetsBulk, getsBulk API 추가
- 테스트 코드 추가 
- doc : key-value 조회 부분에 기존에 포함되지 않았던 asyncGets와 개발된 asyncGetsBulk를 추가 
asyncGetBulk와 asyncGetsBulk가 중복되는 부분이 있어서 중복코드를 제거하기 위해 리팩토링을 진행했지만,
오히려 더 복잡하게 코드가 변하게 되어 간결성 유지를 위해 크게 중복된 부분만 메서드로 통합하였습니다.
리팩토링 필요한 부분은 리뷰를 통해 의견받고 더 진행 하도록 하겠습니다.
=> FEATURE: support mgets command

src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
bop mget, smget 커맨드의 key length가 byte 기준이 아닌 UTF-16 encoding 기준으로 잘못 설정되어 `CLIENT_ERROR bad data chunk`가 발생하는 현상을 수정하였습니다. 
```
Feb 25 17:44:17 net.spy.memcached.ops.OperationException: CLIENT_ERROR bad data chunk
Feb 25 17:44:17     at net.spy.memcached.protocol.BaseOperationImpl.handleError(BaseOperationImpl.java:196) ~[arcus-java-client-1.   12.1.jar:1.12.1]
Feb 25 17:44:17     at net.spy.memcached.protocol.ascii.OperationImpl.readFromBuffer(OperationImpl.java:145) ~[arcus-java-client-1.  12.1.jar:1.12.1]
Feb 25 17:44:17     at net.spy.memcached.protocol.ascii.BTreeGetBulkOperationImpl.readFromBuffer(BTreeGetBulkOperationImpl.java:38)  ~[arcus-java-client-1.12.1.jar:1.12.1]
Feb 25 17:44:17     at net.spy.memcached.MemcachedConnection.handleReads(MemcachedConnection.java:781) …
```
=> FIX: invalid key length in bop mget, smget command

src/test/manual/net/spy/memcached/emptycollection/InsertBTreeWithAttrAndEFlagTest.java, src/test/manual/net/spy/memcached/emptycollection/InsertListWithAttrTest.java, src/test/manual/net/spy/memcached/emptycollection/InsertMapWithAttrTest.java, src/test/manual/net/spy/memcached/emptycollection/InsertSetWithAttrTest.java, src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertBTreeWithAttrTest.java, src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertListWithAttrTest.java, src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertMapWithAttrTest.java, src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertSetWithAttrTest.java
expired 테스트에서 아이템이 expired 되기 위해 기다리는 시간을 수정하였습니다.
**변경전**
expire_time_in_sec * 2
**변경후**
expire_time_in_sec + 1초
=> TEST: fix sleep time for item to be expired

pom.xml, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/CacheMonitor.java, src/main/java/net/spy/memcached/ConfigMonitor.java
ZooKeeper dynamic reconfiguration 기능 지원을 위한 PR 입니다.
zookeeper library version을 3.4.14 에서 3.5.7로 업그레이드 했습니다.
zookeeper initialize 시점에 /zookeeper/config znode와 data를 조회하고
configMonitor class 생성을 enable/disable 합니다.
조회한 configuration data는 필요한 정보들을 parsing 하고 현재 version과 비교하여,
변경이 필요한 경우만 ZK server list를 업데이트 하도록 했습니다.
@hjyun328 @jhpark816 
확인 요청 드립니다.
=> FEATURE: support zookeeper dynamic reconfiguration

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/OperationTimeoutException.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/test/java/net/spy/memcached/ArcusTimeoutMessageTest.java
#326 을 반영한 commit입니다.
broadcasting operation들이 timeout시에 해당 timeoutException 메세지를 남기도록 수정했습니다.
```
- version
Exception in thread "main" net.spy.memcached.OperationTimeoutException: VERSION operation timed out (>700 MILLISECONDS) - failing nodes: /127.0.0.1:11911 [READING] [#Tops=2 #iq=0 #Wops=0 #Rops=1 #CT=1 #TR=-1], /127.0.0.1:11912 [READING] [#Tops=2 #iq=0 #Wops=0 #Rops=1 #CT=1 #TR=-1]
- stats
Exception in thread "main" net.spy.memcached.OperationTimeoutException: STATS operation timed out (>700 MILLISECONDS) - failing nodes: /127.0.0.1:11911[READING] [#Tops=2 #iq=0 #Wops=0 #Rops=1 #CT=1 #TR=-1], /127.0.0.1:11912 [READING] [#Tops=3 #iq=0 #Wops=0 #Rops=2 #CT=1 #TR=-1]
```
또한 ops를 하나하나 foreach로 넘겨주는 코드의 중복이 있어서 해당 내용을
MemcachedConnection에서 복수개의 op를 직접 처리하도록 하였습니다.
해당 내용이 반영되면 후 작업으로 …
=> ENHANCE: add the TimeoutException message to broadcasting operation

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
operation 은 readQ, writeQ 모두에 존재할 수 있는데, 이 경우는 정상적인 상태로 보여 굳이 warn log message 를 남길 필요가 없다고 판단해 제거하였습니다.
=> CLEANUP: removed unnecessary log warn message in getAllOperations().

src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/NotExistsMemcachedNodeException.java
이슈 발생 상황은 아래와 같습니다.
1) ZooKeeper에 특정 service code의 cache_list znode가 존재하지 않음
2) arcus-java-client 시작
3) CacheManager.commandCacheListChange 호출 (children 파라미터는 empty)
4) CacheManager.createArcusClient("") 호출
4) ArcusClient[poolSize] array 생성
5) 주소가 없으므로 Exception이 throw 됨. (IllegalArgumentException: You must have at least one server to connect to)
6) 특정 service code에서 127.0.0.1:11211 주소를 가진 캐시 서버가 실행됨
7) CacheManager.commandCacheListChange 호출 (children 파라미터는 ["127.0.0.1:11211"])
8) ArcusClient[poolSize] array는 이미 생성됐으므로, CacheManager.createArcusClient("127.0.0.1:11211")을 호출하지 않고 ac.getMemcachedConnection() 을 호출
9) ArcusClient[poolSize] array의 element들은 전부 null 값이므로 NullPointerException 발생
10) ArcusClient를 생성한 쪽은 무한 대기 발생 (캐시 서버와 연결 성공이 되지 않으면, latch의 countDown()은 영원히 실행이 안됨)
ZK의 watcher로부터 …
=> FIX: do not create connection pool array if node address is empty

src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/java/net/spy/memcached/MemcachedConnectionTest.java
MemcachedConnection() 로 전달한 bufSize 를 사용하지 않고 f.getReadBufSize() 를 통해 bufSize 를 얻고 있으므로 제거하였습니다.
=> CLEANUP: removed readBufferSize argument in MemcachedConnection().

src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/test/java/net/spy/memcached/MemcachedConnectionTest.java
KetamaLocator의 node, group collection의 reference를 그대로 리턴하게 되어, 바깥에서 collection을 수정할 위험이 있어 이러한 collection 들을 immutable 속성으로 변경하여 리턴하도록 수정하였습니다. 
참고로 immutable collection은 element 변경(remove, put, ...)시 UnsupportedOperationException 발생됩니다. (get은 element를 변경하지 않으므로 그대로 동작)
=> CLEANUP: return immutable collection of node and groups

src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplNodeAddress.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedReplicaGroup.java, src/main/java/net/spy/memcached/MemcachedReplicaGroupImpl.java, src/main/java/net/spy/memcached/ReplicaPick.java, src/main/java/net/spy/memcached/util/ArcusReplKetamaNodeLocatorConfiguration.java
replication 동작중 cache list update로 node의 변경이 일어나는 부분들을 수정하였습니다.
기존의 로직들 중 긴 부분은 모듈화하였고,  메소드명 변경 및  간단화 작업을 진행했습니다.
이후 작업으로는
1. cache list update 설계안 적용
2. "SWITCHOVER" or "REPL_SLAVE" 메세지 수신에 따른 동작 리팩토링
3. 메세지 수신에 따른 switchover 수행입니다.
=> CLEANUP : refactored the cache list update functions of replication cluster

src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
연결에 실패하여 selector에 selection key가 등록되지 않은 노드가 hashring에 제거되는 경우 null pointer exception이 발생될 수 있어 수정하였습니다.
=> FIX: add null check in attachment removal of selection key

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedReplicaGroup.java, src/main/java/net/spy/memcached/MemcachedReplicaGroupImpl.java, src/main/java/net/spy/memcached/MemcachedReplicaGroupROImpl.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
#362 에 계속되는 pr 진행입니다.
기존 pr commit과  리뷰 반영된 commit 을 분리해 두었습니다.
변경된 내용 
- switchover시 setMasterCandidate 설정 (이중화시, 삼중화시) 코드 변경 및 주석 추가
- oldSlaveAddrs, newSlaveAddrs의 자료 구조형태 List->Set으로 변경
- 해당 변경으로 addr 비교시 contains() 사용  
-  updateReplConnections에서 newGroup제거에 대한 형준전임 리뷰 내용 반영
=> FEATURE : support expanded replication group

pom.xml
log4j2에 보안 취약점이 존재해 업그레이드하였습니다.
참고로 업그레이드 하지 않아도 의존성이 optional로 설정되어있기때문에 client 의존성 추가시 자동으로 log4j 의존성이 추가되지 않습니다.
=> FEATURE: upgrade log4j version for security vulnerabilities

src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java, src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java, src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
#378 을 반영한 pr입니다.
pipedInsert 연산 도중 맨 마지막 key의 연산에서 switchover가 발생할 시에
전송하지 못한 인덱스를 저장하여 변경된 master에게 Insert 연산을 재전송합니다.
pipedInsert 내부 구현에서는 ascii 명령어 생성시 하나의 연산을 전송할때는 "PIPE"를 붙이지 않은 nomal 연산을 전송하므로 마지막 인덱스에서 switchover가 발생하여 재전송을 하면 nomal 연산에 대한 결과값을 보내게 됩니다.
그러므로 기존 코드에서 pipedInsert 수행시 1개의 연산 전송을 할때 뿐만 아니라 switchover가 발생한 후 하나의 연산이 재전송 되었을 때도 nomal 연산을 parsing할 수 있도록 수정하였습니다.
=> FIX: fixed parsing only one result after switchover in pipe operation

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java
https://github.com/naver/arcus-java-client/issues/4 이슈에서
mget, mgets operation에서 cancel failure mode를 지원하지 않고, redistribute 모드로 동작하는 현상을 수정하였습니다.
수정하는 김에 중복 코드까지 제거하였습니다.
=> FEATURE: support cancel failure mode in mget, mgets operation

src/main/java/net/spy/memcached/collection/CollectionAttributes.java
CollectionAttributes 클래스에 MinBkey를 설정하는 set API가 불필요하게 있어 
사용자에게 노출 될 수 있기 때문에 제거 하였습니다.
=> fix: remove unnecessary API

src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java
MutatorOperation, BaseStoreOperation 이 두 Operation이 BufferOverFlowException 발생할 수 있어 OVERHEAD 사이즈를 32에서 
64로 변경하였습니다.
=> FIX: Operation command buffer size

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/util/BTreeUtil.java, src/test/java/net/spy/memcached/util/BTreeUtilTest.java
#335 이슈에 관련 pr입니다.
hexadecimal을 지원하는 byte array의 사이즈가 31을 초과할 경우에는 문서상에 IllegalArgumentException를 던지게 되있지만,
현재는 client에서 validation이 되지않아 추가하는 코드를 넣었습니다.
=> FEATURE: add bkey validation

pom.xml, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BKeyObject.java, src/main/java/net/spy/memcached/collection/BTreeCount.java, src/main/java/net/spy/memcached/collection/BTreeDelete.java, src/main/java/net/spy/memcached/collection/BTreeGet.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/CollectionAttributes.java, src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java, src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java, src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java, src/main/java/net/spy/memcached/collection/SMGetElement.java, src/main/java/net/spy/memcached/collection/SMGetTrimKey.java, src/main/java/net/spy/memcached/util/BTreeUtil.java, src/test/java/net/spy/memcached/util/BTreeUtilTest.java
#335 이슈에서 bkey를 unsigned long string으로 출력하는 pr입니다.
long type의 bkey를 사용할 때에도 현재는 String.valueof()를 사용하여서 signed long 형태로 bkey가 변환되어,
unsinged long 형태로 변환될 수 있도록 변경하였습니다.
기존 리뷰 의견 반영하여 toHex -> toHexString으로 convertBkey -> toULongString으로 수정했습니다.
=> FIX: fixed long type string to unsigned long type string on bkey

src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java, src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java, src/main/java/net/spy/memcached/collection/Element.java, src/test/manual/net/spy/memcached/bulkoperation/BopPipeUpdateTest.java, src/test/manual/net/spy/memcached/collection/btree/longbkey/BopGetTest.java, src/test/manual/net/spy/memcached/collection/btree/longbkey/BopInsertAndGetWithElementFlagTest.java, src/test/manual/net/spy/memcached/collection/btree/longbkey/BopUpsertTest.java
#410 이슈 pr입니다.
처음에는 code readability를 위해 element class 내에 
long 타입의 bkey를 String.valueOf 메서드를 이용해 String으로 변환하는 메소드를 추가했었는데
코드를 조금 더 보니, 사용되는 곳이 capacity와 argument를 설정하는 부분에서만 사용이 되고 있었고 
사용되는 부분에서 bkey가 byte 형태인지 long 형태인지 비교하여 값을 가져오는 코드 형태로 구현하고 있었습니다.
해당 코드도 element 내부에서 처리해서 가져오면 code readability가 더 좋을 것 같아
byte형태인지 long 형태인지 비교한후 hex 또는 long을 string으로 변환하여 가져오도록 메소드를 추가했습니다.
=> CLEANUP: refactored get exist bkey

src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java
#400 이슈 관련 pr 입니다.
args를 지우고 additionalArgs.length로 표현하였고, subkey와 additionalArgs null 체크하는 부분을 제거하였습니다.
=> FIX: CollectionOperationimpl command buffer

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/collection/BTreeGetBulk.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGet.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
```java
public interface BTreeSMGet<T> {
public String getRepresentKey();
}
```
- getRepresentKey() 메소드는 smget() 메소드에서 노드를 찾기 위해서만 사용됩니다. 따라서 다음과 같이 인터페이스를 변경합니다.
```java
public interface BTreeSMGet<T> {
public MemcachedNode getMemcachedNode();
}
```
- MemcachedNode 객체는 groupingKeys() 메소드에서 가져옵니다. groupingKeys() 메소드의 반환 값에 MemcachedNode 객체를 포함하기 위해 반환 타입을 변경합니다.
```java
private List<Entry<MemcachedNode, List<String>>> groupingKeys(List<String> keyList)
```
- addOp(final MemcachedNode node, final Operation op) 메소드를 추가하여 key로 노드를 찾는 과정을 거치지 않고 Operation을 InputQ에 추가합니다.
```java
protected Operation addOp(final MemcachedNode node, final Operation op) {
checkState();
conn.addOperation(node, op);
return op;
}
```
=> ENHANCE: Remove getRepresentKey() and add getMemcachedNode() to BTreeSMGet to skip key iteration for searching MemcachedNode #385

src/main/java/net/spy/memcached/ArcusClient.java
#408 에 관한 pr입니다.
String type의 mkey를 한번 더 String.valueOf()로 감싸고 있어서 제거 했습니다.
이외에 불필요하게 String.valueOf()를 사용하는 부분도 확인하였고 다른 부분은 문제 없습니다.
=> FIX: remove unnecessary String.valueOf in ArcusClient.asyncMopUpdate

src/main/java/net/spy/memcached/MemcachedConnection.java
#402 관련 pr입니다.
ZK가 아닌, Old Master 서버로부터 "SWITCHOVER" 메세지를 받아 swichover시 기존의 코드에서는
moveOperation이 이루어진뒤에 role을 변경하게 되어 있어, role을 변경하기전 oldMaster가 Operation을 받게 된다면
남아 있는 Operation은 move되지 않게 됩니다.
그래서 순서를 조정하여 role을 먼저 변경하고 moveOperation이 이루어 지도록 수정했습니다.
~~또한 masterCandidate가 없을 경우 이전 swichover에서 설정해둔 masterCandidate를 활용하게 되어 있어 
group에서 address에 해당하는 candidate가 없을 경우 Null로 설정하도록 변경했습니다.~~
=> FIX: change the order of moveOperation and ChangeRole on switchover

src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
Redistribute 옵션은 노드 구성이 변경되지 않는 고정된 클러스터 구조에서, 실패한 노드로 향하는 연산을 다른 담당 노드가 처리될 수 있게 하기 위해서 만들어진 옵션이다. ARCUS는 클러스터 구성이 유연하므로, 실패한 노드는 ZK로부터 클러스터에서 제거되므로 Operation을 재분배할 필요가 없다.
ArcusClient 사용시 redistribute failure mode를 사용하면 Exception을 던질 수 있도록 수정하였습니다.
또한 ARCUS 노드가 클러스터로부터 제거될 때 failure mode와 관계 없이 operation을 취소처리할 수 있도록 하였고, redistribute로 인한 resend시 inputQ 뿐만아니라 writeQ에 있는 operation도 함께 재분배될 수 있도록 수정하였습니다.
=> FEATURE: block to use redistribute failure mode in ArcusClient

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BKeyObject.java, src/main/java/net/spy/memcached/collection/BTreeFindPosition.java, src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java, src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java, src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/ByteArrayBKey.java, src/main/java/net/spy/memcached/collection/CollectionAttributes.java, src/main/java/net/spy/memcached/collection/Element.java, src/main/java/net/spy/memcached/collection/SMGetElement.java, src/main/java/net/spy/memcached/collection/SMGetTrimKey.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/main/java/net/spy/memcached/util/BTreeUtil.java, src/test/java/net/spy/memcached/util/BTreeUtilTest.java, src/test/manual/net/spy/memcached/collection/attribute/MaxBkeyRangeTest.java, src/test/manual/net/spy/memcached/collection/btree/BKeyObjectTest.java, src/test/manual/net/spy/memcached/collection/btree/ElementTest.java, src/test/manual/net/spy/memcached/collection/btree/SMGetElementTest.java, src/test/manual/net/spy/memcached/collection/btree/SMGetTrimKeyTest.java
issue : #335 , #419 
변경 지점이 많아 각 주제별로 commit을 나눠 두었습니다.
1. long primitive type -> Long wrapper class로 변경
2. long type과 byte array type 혼합 사용 field BkeyObject로 통합, 테스트 코드 추가
3. long bkey의 음수 사용 제한을 위해 API 수준 및 Bkeyobject에 validation 로직 추가, 테스트 코드 추가
- API 수준 변경
- BTreeCreate, BTreeGet, BTreeInsert, BTreeUpdate BTreeUpsert, BTreeDelete, BTreeCount,  BTreeMutate
- Class 내에 BkeyObject를 field로 가지고 있는 API 들은 따로 API에 validation 로직을 추가하지 않았습니다.
=> CLEANUP: refactored bkey 

src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
#409 관련 pr입니다.
1. single bkey일 경우엔 bkey 변수 하나에만 설정
2. from, to 2개의 bkey 를 통해 range를 설정
하도록 생성자를 분리 하였습니다.
이전의 코드를 보면 bkey 하나만을 사용하는(to < 0) 경우가 있는데, 실제 사용하는 api 상에서는
from, to를 사용하여 range를 나타내고 있습니다.
내부에서 한개의 bkey를 사용하는 코드가 구현 되있는것 으로 보아 1개의 bkey를 사용하는 경우도 있는 것 같아 일단 생성자를 추가하였습니다.
=> CLEANUP: separate constructor for searching condition

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeGet.java, src/main/java/net/spy/memcached/collection/CollectionGet.java, src/main/java/net/spy/memcached/collection/ListGet.java, src/main/java/net/spy/memcached/collection/MapGet.java, src/main/java/net/spy/memcached/collection/SetGet.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolBTreeGetTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolListGetTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolMapGetTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolSetGetTest.java
https://github.com/naver/arcus-java-client/issues/433 이슈와 관련된 PR입니다.
dropIfEmpty를 false로 초기화하고, 사용되지 않는 생성자는 제거하였습니다.
=> CLEANUP: refactored CollectionGet

src/main/java/net/spy/memcached/TimedOutMessageFactory.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
https://github.com/naver/arcus-java-client/issues/444#issue-1160304700
TimeoutException 메세지에 pool 정보와 service code를 함께 출력하도록 했습니다.
정보가 없는 경우에는 기존과 같이 출력하도록 했습니다.
=> ENHANCE: Enhance timeout exception message #444

src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
https://github.com/naver/arcus-java-client/issues/445 timeout 경과 시간이 1.5초 지나면 reconnect 될 수 있도록 수정하였습니다.
=> FEATURE: add timeout duration threshold

src/test/java/net/spy/memcached/ClientBaseCase.java
https://github.com/naver/arcus-java-client/pull/447 timeout duration PR 적용하면서, 테스트코드에 getTimeoutDurationThreshold 메소드를 누락하였습니다. 빌드 에러가 발생되어 수정합니다.
=> TEST: fix build error in ClientBaseCase test class

src/test/java/net/spy/memcached/ProtocolBaseCase.java
#462에 관련 pr입니다.
간헐적으로 testGracefulShutdownTooSlow() test가 fail되는 문제가 발생합니다.
그 이유는 현재 fast shutdown 기준인 1 millisecond보다 조금 더 빠르게 shutdown이 이루어지는 경우가
아주 가끔 (몇백번)에 한번 정도 발생하는 것을 테스트로 확인했습니다.
fast shutdown 기준을 조금 더 낮추었고 (700micro == 0.7milli), 5000번 정도 테스트 했을 때 실패 없이 테스트를 통과했습니다.
=> FIX: change the fast shutdown time

src/main/java/net/spy/memcached/BinaryConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryMemcachedNodeImpl.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java, src/test/java/net/spy/memcached/MockMemcachedNode.java, src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java
memcachednode 생성자에서 socket channel 인자를 제거하고 setter로 초기화할 수 있도록 수정하였습니다.
=> CLEANUP: remove socket channel argument in MemcachedNode constructor

src/main/java/net/spy/memcached/MemcachedConnection.java
empty selected 현상이 발생될 경우, select delay 로그를 출력하여 원인을 알아낼 수 있도록 하였습니다.
=> FEATURE: print select delay in case of too many empty selected keys

src/main/java/net/spy/memcached/MemcachedConnection.java
switchover timeout이 발생될 경우, delayedSwitchover 플래그에 false로 초기화하지 못하여, write 작업을 처리하지 못함에따라 op timeout이 발생하는 현상을 수정하였습니다.
=> FIX: missing to set false to delayedSwitchover of replica group

src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
addAllOpToWriteQ() 메서드를 변경하였습니다. (https://github.com/naver/arcus-java-client/pull/473#discussion_r884135421)
기존 : int addAllOpToWriteQ(BlockingQueue<Operation> allOp) 
변경 : boolean addOpToWriteQ(Operation op)
메서드는 하나의 Operation 만을 writeQ 로 옮기는 작업을 수행하고,
기존 Operation 컬렉션의 경우는 외부에서 이터레이트하여 호출하도록 변경하였습니다.
=> CLEANUP: changed method addAllOpToWriteQ() to addOpToWriteQ().

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/OperationFactory.java, src/main/java/net/spy/memcached/TimedOutMessageFactory.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java, src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
다음을 수정하였습니다.
- BaseGetOpImpl 의 isBulkOperation() 는 key 개수가 2개 이상이면 true, 아니면 false 리턴.
- TimedOutMessage 생성 시에는 key 개수로 bulk operation 인지를 확인하고 있음. 이와 같은 로직이 맞다고 봄.
```java
public final class TimedOutMessageFactory {
...
private static boolean isBulkOperation(Operation op, Collection<Operation> ops) {
if (op instanceof GetOperation) {
GetOperation gop = (GetOperation) op;
return gop.getKeys().size() > 1;
} else if (op instanceof StoreOperation) {
return ops.size() > 1;
} else if (op instanceof DeleteOperation) {
return ops.size() > 1;
}
return op.isBulkOperation();
}
}
```
- CollectionBulkInsertOperationImpl 의 key field 는 keylist 를 갖도록 수정.
- multi key & single value 를 요청하므로 keylist 를 갖고,
- CollectionPipedInsertOperationImpl 처럼 single key & multi value 를 요청하는 연산에서는 single key 를 갖는 것이 맞아보임. …
=> FIX: get operation can be bulk operation if having multi key.

src/test/java/net/spy/memcached/MemcachedConnectionTest.java, src/test/manual/net/spy/memcached/emptycollection/GetCountBTreeTestWithElementFlagFilterTest.java
https://github.com/naver/arcus-java-client/issues/482
위에서 논의한 대로 컴파일 워닝 일부를 나오지 않도록 수정했습니다.
=> INTERNAL: Fix some compile warnings.

src/main/java/net/spy/memcached/ArcusClient.java
bop get bulk에서 offset과 count 정보는 객체에 저장되어 있음에도 매개변수로 받아놓고 사용하지 않는 부분을 제거했습니다.
=> INTERNAL: Remove unused parameters offset and count.

src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithLongTypeBkey.java
BTreeGetBulkImpl 클래스의 하위 클래스에서 사용되는 BTreeGetBulkImpl 클래스의 생성자가 불필요해 보여 제거했습니다.
=> INTERNAL: Remove unnecessary constructors in BTreeGetBulkImpl.

src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithLongTypeBkey.java
BTreeGetBulkImpl 클래스를 상속받는 두 클래스, BTreeGetBulkWithByteTypeBkey 클래스와 BTreeGetBulkWithLongTypeBkey 클래스에 중복되는 로직이 있어서 BTreeGetBulkImpl 클래스로 로직을 옮겼습니다.
- decodeKeyHeader() 메소드의 경우 두 concrete 클래스에 완전히 동일한 로직으로 있어서 그대로 BTreeGetBulkImpl 클래스로 옮겼습니다.
- decodeItemHeader() 메소드의 경우 완전히 동일하진 않지만 매우 유사한 로직으로 있어서 서로 다른 부분만 abstract 메소드로 각 concrete 클래스에서 구현하도록 하고 동일한 부분은 BTreeGetBulkImpl 클래스로 옮겼습니다.
=> INTERNAL: Remove duplicated logic in concrete classes that extends BTreeGetBulkImpl.

README.md, docs/05-set-API.md, docs/07-btree-API.md, docs/10-log-message.md
https://github.com/jam2in/arcus-works/issues/338 이슈 작업을 위해 document 수정 중 일부 indent가 "\t"로 되어 있는 것을 확인했습니다. Markdown viewer에 따라 출력이 일관적이지 않을 수 있어서 .md 파일에 한하여 "\t"를 "    "(space 4개)로 바꿨습니다.
=> DOC: Replace "\t" to "    ".

src/main/java/net/spy/memcached/collection/BTreeGetBulk.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
https://github.com/naver/arcus-java-client/pull/490 에서 논의된 내용입니다.
BTreeGetBulkOperationImpl에서 element count를 decode 하는 곳을 BTreeGetBulkImpl.decodeKeyHeader() 메소드로 옮겼습니다.
OperationStatus의 경우 matchStatus() 메소드가 필요한데, 이 메소드는 OperationImpl 클래스에 정의되어 BTreeGetBulkImpl 클래스에서 사용할 수 없었습니다. 그래서 status를 decode 하는 곳은 변경하지 않았습니다.
=> INTERNAL: Move key header decode from BTreeGetBulkImpl to BTreeGetBulkOperationImpl.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeSMGet.java, src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java, src/main/java/net/spy/memcached/collection/SMGetElement.java, src/main/java/net/spy/memcached/ops/BTreeSortMergeGetOperation.java, src/main/java/net/spy/memcached/ops/BTreeSortMergeGetOperationOld.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java, src/test/manual/net/spy/memcached/collection/btree/SMGetElementTest.java
https://github.com/jam2in/arcus-works/issues/341
smget 연산 수행 시 eflag 정보를 가져오지만 연산의 결과가 되는 SMGetElement 객체에는 저장하지 않던 점을 수정했습니다.
=> FIX: Add eflag field in SMGetElement class.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ops/BTreeGetBulkOperation.java, src/main/java/net/spy/memcached/ops/BTreeSortMergeGetOperation.java, src/main/java/net/spy/memcached/ops/BTreeSortMergeGetOperationOld.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/naver/arcus-java-client/pull/496#discussion_r897527021
Bop Get Bulk와 smget 연산의 callback에서 매개변수 순서가 `key, subkey, flags, eflag, data`인 것을 `key, flags, subkey, eflag, data`로 변경했습니다.
=> INTERNAL: Change the order of parameter subkey and flags.

src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java
SMGet Item Header decode 과정에서 space splitted tokens count를 data 포함하여 측정한 것을 고쳤습니다.
=> FIX: Fix BTreeSMGetImpl.decodeItemHeader()

src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGet.java, src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
https://github.com/naver/arcus-java-client/pull/486#pullrequestreview-1008422907
BTreeGetBulkImpl 클래스와 BTreeSMGetImpl 클래스에서 변하지 않는 필드들을 final로 선언하고 사용되지 않는 필드는 제거했습니다.
=> CLEANUP: Refactored BTreeGetBulkImpl and BTreeSMGetImpl.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/OperationFactory.java, src/main/java/net/spy/memcached/ops/BTreeGetBulkOperation.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/naver/arcus-java-client/pull/486#discussion_r898640644
BTreeGetBulkOperation.Callback에 불필요한 generic 선언을 제거했습니다.
=> CLEANUP: Remove unnecessary generic type in BTreeGetBulkOperation.Callback.

src/main/java/net/spy/memcached/ops/MultiOperationCallback.java
MultiOperationCallback 클래스를 이전 구현으로 rollback 했습니다.
=> FIX: Rollback MultiOperationCallback.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java
https://github.com/naver/arcus-java-client/pull/504#issuecomment-1157486255
기존 MultiOperationCallback.recievedStatus()의 구현은 originalCallback.receivedStatus()를 호출하지 않는 것이었습니다.
이를 SMGet의 migration 기능을 지원하기 위해 MultiOperationCallback.recievedStatus()의 구현을 originalCallback.receivedStatus()를 호출하도록 바꾸었습니다.
에러 원인은 Mock 객체로 만들어진 originalCallback을 통해 recievedStatus()를 호출하면 unexpected invocation 테스트 실패가 뜨는 것입니다.
MultiOperationCallback.recievedStatus()에서 originalCallback.receivedStatus()를 호출하지 않도록 바꾸고, MultiBTreeSortMergeGetOperationCallback.recievedStatus()에서만 originalCallback.receivedStatus()를 호출하도록 바꿨습니다.
=> CLEANUP: Comment the receivedStatus().

docs/12-arcus-future-get-API.md
#509 의 잘못된 API 명을 수정 했습니다.
- asyncBulkGet() -> asyncGetBulk()
- asyncBulkGets() -> asyncGetsBulk()
=> DOC: fixed the name of async get bulk API in getSome().

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/test/manual/net/spy/memcached/collection/list/LopGetTest.java, src/test/manual/net/spy/memcached/collection/map/MopGetTest.java, src/test/manual/net/spy/memcached/emptycollection/GetWithDropSetTest.java
#439
- 생략가능한 인자를 제외한 list/set/map API를 구현하였습니다.
- asyncLopGet, asyncSopGet, asyncMopGet 메소드에서 withDelete, dropIfEmpty 인자를 명시하지 않아도 동작합니다.
- unit test 완료하였습니다.
=> INTERNAL: add omitted parameter methods - list/set/map

src/main/java/net/spy/memcached/MemcachedConnection.java
#511 반영한 pr입니다.
pool 정보와 service code 정보 추가하였습니다.
```
/192.168.0.33:11211 exceeded continuous timeout threshold. >10(count), >-1(duration) (#Tops=1 #iq=0 #Wops=0 #Rops=1 #CT=0 #TD=0 #TR=-1) ArcusClient(1-1) for debug
/192.168.0.33:11211 exceeded timeout ratio threshold. >10 (#Tops=1 #iq=0 #Wops=0 #Rops=1 #CT=0 #TD=0 #TR=0) ArcusClient(1-1) for debug
```
=> ENHANCED: add pool and service code information on timeout message

src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArrayModNodeLocator.java, src/main/java/net/spy/memcached/KetamaNodeLocator.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MigrationState.java, src/main/java/net/spy/memcached/MigrationType.java, src/main/java/net/spy/memcached/NodeLocator.java
Migration 위한 node locator 준비 작업의 PR 입니다.
아래 메소드를 추가 제공하도록 확장 되었습니다.
```java
/**
* Get all alter memcached nodes.
*/
Collection<MemcachedNode> getAlterAll();
/**
* Get an alter memcached node which contains the given socket address.
*/
MemcachedNode getAlterNode(SocketAddress sa);
/**
* Remove the alter nodes which have failed down.
*/
void updateAlter(Collection<MemcachedNode> toDelete);
/**
* Prepare migration with alter nodes and migration type.
*/
void prepareMigration(Collection<MemcachedNode> toAlter, MigrationType type);
/**
* Update(or reflect) the migratoin range in ketama hash ring.
*/
void updateMigration(Long spoint, Long epoint);
```
=> FEATURE: Prepared the node locator for data migration

docs/07-btree-API.md, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java
#521 
- CollectionAsync...와 같이 여러 Collection과 관련된 메소드는 subkey 용어를 사용합니다.
- AsyncBopIncr, AsyncMopGet과 같이 하나의 Collection과 관련된 메소드는 각 Collection에서 사용 되는 키(bkey, mkey)를 용어로 사용합니다.
- 문서는 수정할 것이 크게 없어 오타 수정만 하였습니다.
=> INTERNAL: separate usage of subkey and bkey/mkey

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
#439 
- withDelete, dropIfEmpty 인자만 생략한 asyngBopGet() API를 제공합니다.
- byte array형식의 bkey를 사용하는 API들을 일관성 있게 위치 조정하였습니다.
=> INTERNAL: add omitted parameter method - asyncBopGet()

src/main/java/net/spy/memcached/OperationFactory.java, src/main/java/net/spy/memcached/ops/BaseOperationFactory.java
기존 구현은 key index를 받아 redirect 해야 할 key를 구했습니다.
바뀐 구현은 index를 받지 않고 redirect 해야 할 key를 바로 받습니다.
=> INTERNAL: Change first parameter type of OperationFactory.cloneMultiOperation() from List<Intreger> to List<String>.

src/main/java/net/spy/memcached/collection/SetPipedExist.java
SetPipedExist 연산이 중간에 중단되었을 때 중단된 지점부터 다시 수행할 수 있도록 수정했습니다.
=> INTERNAL: Prepare SetPipedExist to redirect in migration.

src/main/java/net/spy/memcached/AddrUtil.java, src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArrayModNodeLocator.java, src/main/java/net/spy/memcached/KetamaNodeLocator.java, src/main/java/net/spy/memcached/NodeLocator.java
NodeLocator에 NOT_MY_KEY 응답의 owner MemcachedNode를 찾는 기능을 추가했습니다.
=> INTERNAL: Prepare NodeLocator to redirect in migration.

src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
```java
if (status.isSuccess()) {
cb.receivedStatus((successAll) ? END : FAILED_END);
} else {
cb.gotStatus(insert.getKey(index), status);
cb.receivedStatus(FAILED_END);
}
```
if문과 else문 모두 callback.receivedStatus() 메소드를 호출하는데, 아래와 같이 if문에 무관하게 메소드를 1회 호출하도록 변경했습니다.
```java
if (!status.isSuccess()) {
cb.gotStatus(insert.getKey(index), status);
successAll = false;
}
cb.receivedStatus((successAll) ? END : FAILED_END);
```
=> CLEANUP: Simplified code in CollectionBulkInsertOperation.handleLine() when operation is not piped.

src/main/java/net/spy/memcached/collection/SetPipedExist.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java
SetPipedExist 연산의 handleLine() 메소드에서 itemCount가 1인지 아닌지 비교하는 if문이 있는데, isNotPiped를 의미합니다.
isNotPiped() 메소드를 호출하기 위해 SetPipedExist 클래스에서 CollectionPipe 클래스를 상속하도록 수정했습니다.
=> INTERNAL: Inherit CollectionPipe class to SetPipedExist class to call same semantic method isNotPiped().

src/main/java/net/spy/memcached/MemcachedConnection.java
`((Buffer) rbuf).clear();` 메소드 호출을 공통 로직으로 옮겼습니다.
=> INTERNAL: Move Buffer.clear() method call.

src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/manual/net/spy/memcached/LoggerSetter.java, src/test/manual/net/spy/memcached/collection/BaseIntegrationTest.java
현재 구현으로 Logger 객체는 한 번 만들어진 이후에는 교체가 되지 않습니다. 테스트 코드를 수행할 때 original memcached 테스트 코드가 먼저 수행되는데, 이 때 Logger 설정이 존재하지 않아 DefaultLogger를 사용합니다. 이렇게 되면 arcus memcached 테스트 코드를 수행할 때도 DefaultLogger를 사용하게 됩니다. 
이러한 Logger 설정을 original memcached 테스트 코드와 arcus memcached 테스트 코드 모두 같은 Logger를 사용할 수 있도록 변경했습니다. 현 PR은 arcus memcached 테스트 코드에서 설정한 Log4JLogger를 사용하도록 해뒀으며 쉽게 다른 Logger로 교체(이미 만들어진 Logger의 교체가 아닌 최초에 만들 Logger 타입 교체)할 수 있도록 구현했습니다.
=> TEST: Set logger to Log4jLogger when running test.

src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
https://github.com/naver/arcus-java-client/issues/534
위 이슈를 해결하기 위해 Test가 실패하는 부분에 일시적으로 로그 레벨을 DEBUG로 두었다가 Test가 실패하는 부분을 벗어나면 다시 INFO로 되돌립니다.
=> TEST: Set log level to DEBUG temporarily to dig CI failure issue.

src/main/java/net/spy/memcached/BulkService.java
Generic 클래스에 generic 타입을 주지 않아서 생기는 warning을 해결했습니다.
참고로 `Collection`을 그냥 쓰는 것과 `Collection<?>`을 쓰는 것은 컴파일 결과는 같습니다.
=> FIX: Resolve generic warning

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
redundant usage of StringBuilder warning 입니다.
원리에 대해선 아래 문서를 참고해 주세요.
https://stackoverflow.com/questions/47605/string-concatenation-concat-vs-operator
=> FIX: Resolve unnecessary usage of StringBuilder warning.

src/test/java/net/spy/memcached/ConsistentHashingTest.java
StringBuffer 클래스는 thread-safe 합니다. 때문에 multi-threaded가 아닌 경우 StringBuilder에 비해 성능이 떨어집니다.
multi-threaded가 아닌 환경에서 StringBuffer를 사용하려고 하여 생긴 warning입니다.
=> FIX: Resolve unnecessary usage of StringBuffer warning.

src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
static field는 클래스 이름에 의해 참조하는 것이 올바른 사용법입니다.
=> FIX: Resolve static variable should be qualified by type name warning.

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
switch case 문에서 어느 한 case에서 break문 없이 다음 case로 계속 수행하도록 구현하면 fall through warning이 발생합니다.
구현상 해당 warning이 뜨지 않아도 될 것 같아서 무시하도록 했습니다.
=> FIX: Suppress fall through warning.

src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java, src/test/manual/net/spy/memcached/LongKeyTest/BaseLongKeyTest.java, src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java, src/test/manual/net/spy/memcached/collection/btree/BopSortMergeTest.java
```java
List<String> a = new ArrayList<String> {
{
add("a");
add("b");
}
}
```
기존 코드가 위와 같을 때, 이는 아래의 코드와 같습니다.
```java
public class AnnonymousClass1 extends ArrayList<String> {
}
AnnonymousClass1 a = new AnnonymousClass1();
a.add("a");
b.add("b");
```
문제는 ArrayList 클래스가 Serializable 인터페이스를 상속받습니다.
Serializable 인터페이스를 상속받는 클래스가 `private final static long serialVersionUID` 필드를 갖지 않으면 warning을 띄웁니다.
```java
new ArrayList<String> {
{
add("a");
add("b");
}
}
```
위 코드로 인해 생성되는 익명 클래스도 `private final static long serialVersionUID` 필드를 가져야 합니다.
하지만 객체의 용도에 따라 해당 필드가 필요하지 않아 보여서 다른 방식으로 warning을 해결했습니다.
=> FIX: Resolve the serializable class does not declare a static final serialVersionUID field of type long warning.

src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/CacheMonitor.java, src/test/java/net/spy/memcached/CacheMonitorTest.java
오프라인으로 논의된 사항을 적용했습니다.
```java
if (zk.exists(ARCUS_BASE_CACHE_LIST_ZPATH + serviceCode, false) != null) {
arcusReplEnabled = false;
cfb.internalArcusReplEnabled(false);
getLogger().info("Connected to Arcus cluster (seriveCode=%s)", serviceCode);
}
```
논의되지 않은 코드도 추가되었습니다. 실제로 이런 상황이 일어나진 않겠지만, EE 버전 사용 중 -> ZK 연결 끊김 -> Community 버전으로 교체 -> ZK 연결 되는 상황을 가정하고 방어 코드를 추가했습니다.
=> FIX: Fix buggy code.

.github/workflows/ci.yml
Reopen #572 
`ci.yml`에서 중복된 maven 의존성 캐싱 step을 제거하였습니다. `actions/setup-java@v2`는 `actions/cache`를 내장하고 있습니다.
**AS-IS**
```yml
- name: Set up JDK 11
uses: actions/setup-java@v2
with:
java-version: '11'
distribution: 'temurin'
cache: maven
- name: Cache Maven Dependencies
uses: actions/cache@v3.0.0
with:
path: ~/.m2
key: ${{runner.os}}-maven
```
**TO-BE**
```yml
- name: Set up JDK 11
uses: actions/setup-java@v2
with:
java-version: '11'
distribution: 'temurin'
cache: 'maven'
```
- [actions/setup-java#caching-maven-dependencies](https://github.com/actions/setup-java/tree/v2#caching-maven-dependencies)
=> FIX: remove duplicate maven dependency caching

src/main/java/net/spy/memcached/CacheMonitor.java
`cache_list` 혹은 `cache_list/<service code>` znode가 제거되었을 때 ZK 연결을 끊고, ZK 연결 시작부터 다시 수행 하도록 수정했습니다.
=> ENHANCE: Reconnect to ZK when cache_list znode is deleted.

src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
#534
위 이슈를 해결하기 위해 DEBUG 레벨의 로그를 찍는 부분을 제거했습니다.
=> INTERNAL: Remove DEBUG level log for #534

src/main/java/net/spy/memcached/MemcachedConnection.java
https://github.com/naver/arcus-java-client/pull/596
위 PR의 후속 PR 입니다.
inactive node로 Operation Cancel 시 Operation의 담당 Node가 정해지지 않아 에러 메세지에 Node 정보가 출력되지 않는 점을 수정했습니다.
=> FIX: Set handling node to print node information in "inactive node" cancel message.

src/main/java/net/spy/memcached/MemcachedConnection.java
Migration이 이미 진행 중인 Cluster에 Client가 붙은 경우 에러가 발생하는 것을 수정했습니다.
=> FIX: Fix bug that is occurred when client is attached to Arcus cluster that is doing migration type=LEAVE.

src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/test/java/net/spy/memcached/MemcachedConnectionTest.java
- https://github.com/jam2in/arcus-works/issues/378
- 위 이슈와 관련된 사전 PR 입니다.
- cache_list와 alter_list의 변경 사항을 Queue로 관리하지 않고 마지막 변경 사항만 적용하도록 수정했습니다.
- 이번 PR을 먼저 하는 것은 처음에 설계할 때 Queue로 관리하지 않고 마지막 변경 사항만 적용하도록 했기 때문입니다.
=> INTERNAL: Use last nodes change.

src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java, src/main/java/net/spy/memcached/internal/CollectionFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java
- CollectionFuture가 OperationFuture을 상속받도록 구조를 변경하는 PR입니다.
- https://github.com/jam2in/arcus-works/issues/403 해당 이슈와 관련된 PR입니다.
=> CLEANUP: Refactor CollectionFutrue to extend OperationFuture

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java
https://github.com/jam2in/arcus-works/issues/403 기반 PR입니다.
1. 아래의 연산들을 asyncStore api와 내부 로직이 일관되도록 변경
- asyncSetBulk(2개)
- asyncStoreBulk(2개)
- asyncDeleteBulk
2. 변경된 내부 로직은 다음과 같다.
- 변경 전 : api 호출 -> return문과 동시에 future 생성자 호출 -> future의 생성자에서 createOp()를 통해 op 인스턴스들 생성
- 변경 후 : api 호출 -> future 생성 -> api 내부 로직에서 op 인스턴스들 생성 -> return future
3. 위 작업에 의해 BulkOperationFutrue가 추상 클래스에서 일반 클래스로 변경됨
- 추상 메서드인 createOp()가 없어지고 기존의 createOp()의 로직은 위 api 함수들의 내부 로직으로 이전시킴
=> INTERNAL: Changed the usage and implementation of BulkOperationFuture.

src/main/java/net/spy/memcached/ArcusClient.java, src/test/manual/net/spy/memcached/btreesmget/SMGetErrorTest.java, src/test/manual/net/spy/memcached/collection/btree/BopGetBulkTest.java, src/test/manual/net/spy/memcached/collection/btree/longbkey/BopGetBulkTest.java
- 해당 이슈와 관련하여 작업했습니다.  https://github.com/jam2in/arcus-works/issues/380
- 아래 로직을 `validateKeys(keyList)`로 치환하게 되면 null 검사 뿐만아니라 empty 검사를 함께 수행합니다.
```java
if (keyList == null) {
throw new IllegalArgumentException("Key list is null.");
}
```
- 만약 empty 검사를 하지 않으면 groupingKeys() 메서드 내에서 for Loop을 돌지 않아 **empty Collection을 반환**하게 됩니다.
- 기존에는 List<String> keyList가 empty로 들어올 경우 예외를 발생 시키지 않고 size 0인 컬렉션을 반환했습니다.
- 저는 해당 사항 또한 예외를 통해 사용자에게 상황을 알려줘야한다고 생각하여 empty check를 수행했습니다.
- ~~List<String> 요소가 Duplication인 경우는 기존에는 예외를 발생시켰는데 저는 자동으로 중복 요소를 걸러서 연산을 진행하도록 변경했습니다.~~
- 위 두 사항으로 인해 일부 테스트 코드에 변경이 있었습니다.
- 위 두 가지 부분에 대해서 의견 부탁드립니다.
=> ENHANCE: Optimize groupingKeys() logic

src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/naver/arcus-java-client/pull/619로부터 파생된 작업입니다.
=> FIX: size of mergedOpStatus list in pipedCollectionOperation.

.github/workflows/ci.yml
https://github.com/jam2in/arcus-works/issues/417 이슈에 대한 PR입니다.
기존의 actions/setup-python@v3가 더이상 python2에 대한 지원을 하지 않아
이를 MatteoH2O1999/setup-python@v1으로 변경했습니다.
우선 CI 검사를 위해 위 action을 사용합니다.
추후 python2 자체를 memcached 레포에 넣어 이로부터 python2를 설치하는 작업이 필요할 것 같습니다.
=> TEST: change python install script in ci.yml

src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/naver/arcus-java-client/pull/619
로부터 파생된 PR입니다.
piped 연산에서 getOperationStatus의 로직을 수정했습니다.
=> FIX: getOperationStatus method in asyncCollectionPipedInsert/Update.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
https://github.com/jam2in/arcus-works/issues/403 관련 PR입니다.
piped operation Future 생성 후, CollectionFuture 상속 받도록하였습니다.
=> INTERNAL: Creating piped collection operation future.

src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java, src/test/manual/net/spy/memcached/bulkoperation/PipeInsertTest.java, src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertListWithAttrTest.java
아래 예는 [A,E] 리스트에 [B,C,D] 리스트의 elements를 
`asyncLopPipedInsertBulk(Key, 1, elements, attr)` API로 삽입할 경우의 결과입니다.
현재 동작은 고정된 index 값을 사용하여 의도하지 않은 결과를 만듭니다.
따라서, 이를 수정하여 아래의 변경 후 동작의 결과로 만들고자 합니다.
```
// 현재 동작
[A,E] -> [A,D,C,B,E]
// 변경 후 동작
[A,E] -> [A,B,C,D,E]
```
1. CollectionPipedInsert.java에서 서버에 요청을 보낼 때 사용되는 index값을 1 증가 시킴으로서 해결하였습니다.
2. PipeInsertTest.java에 요소들의 Index에 대한 test case 추가하였습니다.
3. PipeBulkInsertListWithAttrTest.java의 테스트 내용 변경하였습니다.
4. PipeBulkInsertSetWithAttrTest.java의 경우 PipeBulkInsertListWithAttrTest와 동일한 테스트를 수행하고 있어서 Set Api를 사용하도록 변경하였습니다.
=> FIX: Element sequence when using asyncLopInsert api.

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/GetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java
https://github.com/jam2in/arcus-works/issues/406 관련 PR입니다.
asyncGet 호출 시 put() 로직 수행을 IO 쓰레드에서 응용의 워커 쓰레드로 변경하였습니다.
=> ENHANCE: change put method logic in LocalCacheManager in aysncGet.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
기존의 CollectionBulkInsert 연산은 수행 시 
**복수개의 Collection에 동일한 value를 Insert해주는 연산**이다.
위 로직을 수행할 때 추가할 value를 
Insert할 대상(CollectionBulkInsert) **객체를 만들 때마다 encode해주는 로직이 존재**한다.
**즉, 필요없는 다수의 `tc.encode()` 로직이 응용의 worker thread에서 발생**한다.
api마다 `insertValue`라는 값을 한번의 `tc.encode(value)`를 통해 얻어낸다.
이후 `insertValue`를 `CollectionBulkInsert`의 생성자의 인수로 사용한다.
(기존에는 tc와 value가 인수로 사용되었다.)
async(Sop,Lop,Mop,Bop)InsertBulk api 4가지 모두 한번의 endcode만 수행하도록 변경한다.
Bop의 경우는 bKey의 형태에 때문에 두 가지 변경지점이 발생한다.
추가적으로 테스트 코드 통과를 위한 테스트코드 변경도 일부 존재합니다.
=> ENHANCE: Remove repeating encode logic in CollectionBulkInsert.

src/main/java/net/spy/memcached/internal/OperationFuture.java
https://github.com/jam2in/arcus-works/issues/419
기존의 단일 Op를 가지는 Future의 cancel 로직은 아래와 같은 문제가 있다.
아래의 세가지 경우를 고려하지 않고 
모든 case에 대해 op.cancel()을 호출시킨다.
그리고 `OperationState.WRITE_QUEUED`를 기준으로
cancel()의 성공 및 실패 여부를 알려준다.
- op 진행 전 cancel() 요청
- op 진행 중 cancel() 요청
- op 완료 후 cancel() 요청
만약 op가 완료 된 후, cancel() 요청이 들어올 경우
응답값은 false로 정상적으로 돌려준다.
하지만 cancel() 요청 후, get() 메서드를 호출할 경우엔 
`ExecutionException`을 발생시킨다.
**즉, 작업의 완료로 인해 cancel이 실패하였음에도 
cancel에 의한 예외가 발생한다.**
정상 동작은 예외가 발생하지 않고 완료된 결과를 리턴해줘야한다.
- op 진행 전 cancel() 요청 : return True, ExecutionException 발생
- op의 state : `OperationState.WRITE_QUEUED`
- op 진행 중 cancel() 요청 : return True, ExecutionException 발생
- op의 state : `OperationState.READING` , `OperationState.WRITING`
- op 완료 후 cancel() 요청 : return False, Future의 get() 호출 시 정상 응답
- …
=> FIX: change cancel method logic in OperationFuture.

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheBulkGetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java
MemcachedClient asyncBulkGet내의 FrontCache 로직을 FrontCacheClient로 이전 작업을 수행했습니다.
=> ENHANCE: Seperate FrontCacheLogic in asyncGetBulk from MemcachedClient to FrontCacheClient.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java
기존의 multi-op를 가지는 Future의 cancel은 
Operation 객체의 완료 여부에 관계 없이 모두 
`op.cancel()`을 호출하도록 되어 있다.
이를 아래의 기준을 통해 호출되도록 변경한다.
- 모든 op 완료 : `return false` 반환 및 `op.cancel()` 호출X
- 일부 op 완료 : `return true` 반환 및 완료되지 않은 op들의 `op.cancel()` 호출
- 모든 op 진행 중 : `return true` 반환 및 모든 op들의 `op.cancel()` 호출
위의 3가지 경우를 기준으로 multi op를 가지는 Future의 cancel 메서드 로직 수정
https://github.com/jam2in/arcus-works/issues/419
=> FIX: Change cancel method logic in multi-operation Future.

src/main/java/net/spy/memcached/ArcusClient.java
Piped 연산의 Elem의 개수가 500개 이하인 경우와 초과하는 경우에 대해
각각의 메서드를 통해 연산 로직 수행
이를 하나의 메서드로 합쳐서 로직 수행하도록 변경
https://github.com/naver/arcus-java-client/pull/619 로부터 파생된 PR입니다.
https://github.com/jam2in/arcus-works/issues/414
=> CLEANUP: Change logic in single CollectionPipedCollection op.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
https://github.com/jam2in/arcus-works/issues/423
1. PipedCollectionFuture 생성자의 `updateList.size()` 인자 삭제
2. `rv.addOperation(op);`와 `addOp(key, op);`의 호출 순서 변경
=> INTERNAL: Refactor pipe insert and pipe update api.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java
https://github.com/jam2in/arcus-works/issues/403
기존의 `asyncCollectionInsertBulk2` 메서드는 
내부적으로 익명 Future 클래스를 구현하여 리턴한다.
이러한 구조를 다른 api들과 동일하게 
`Future rv 생성 -> 연산 결과를 rv에 전달 -> rv 리턴`
구조로 변경한다.
참고로 `asyncCollectionInsertBulk2`는 
여러 컬렉션에 동일한 Elem을 삽입하는 api에서 사용된다.
기존에 존재하는 `BulkOperationFuture `를 사용하여 Future를 생성합니다.
=> INTERNAL: Refactor Future in asyncCollectionInsertBulk2 method.

src/main/java/net/spy/memcached/ArcusClient.java
기존의 getVersion에서 동시성 이슈 해결은 synchronized 블럭을 통해 진행한다.
이는 쓰레드의 blocking을 야기해 성능의 문제가 존재한다.
또한 **현재 synchronized 블럭의 인자인 `VERSION`은
synchronized 블럭 내에서 참조가 변경될 수 있다.**
즉, threadA가 lock을 걸고 내부 로직에서 참조를 변경하면
threadB가 lock을 거는 참조 대상이 달라져
**동기화가 제대로 이루어지지 않을 가능성이 존재**한다.
이러한 문제를 AtomicReference를 통해 해결합니다.
기존과 동일하게 버전 파싱 중 예외 발생 시는 "NONE"을 대입합니다.
=> FIX: Change syncronization tool in getVersion().

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ops/CollectionGetOperation.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/naver/arcus-java-client/pull/634
위 PR에서 BTreeGet의 eflag는 CollectionGet 인스턴스의 
내부 field을 통해 얻어져 Element를 생성할 때 사용된다.
eflag의 경우에도 bKey,data와 마찬가지로 콜백의 gotData를 호출할 때
인자로 넘겨주면 일관성 있는 구조로 변경된다.
변경을 통해 위 PR을 구현할 때에 eflag 값을 
gotData()를 통해 곧바로 얻어올 수 있다.
또한 gotData()의 key 인자의 경우 api인자로 들어온 값과
api 인자를 통해 설정된 동일한 값을 assert를 통해
불필요한 비교를 진행한다.
그래서 key 인자의 경우 삭제시킨다.
CollectionGetOperation의 콜백의 gotData() 메서드의 인자가 변경되었습니다.
=> INTERNAL: Add eflag parameter in collectionGetOperation callback.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/main/java/net/spy/memcached/ops/Operation.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
https://github.com/jam2in/arcus-works/issues/419
오프라인에서 논의된 syncronized를 사용한 동시성 발생 문제를 
AtomicBoolean, volatile을 사용하여 해결하도록 변경한다.
스레드가 block이 되지 않기 때문에 기존의 논의된 사항보다
스레드가 가지는 overhead가 감소한다.
1. Operation 내의 cancel 메서드의 리턴 타입, 로직
2. Operation 내의 transitionState 메서드의 로직 
3. cancelld 변수 -> `atomicBoolean`로 타입 변경 , state 변수 -> `volatile` 추가
=> FIX: sync problem in Operation cancel and transitionState method

src/main/java/net/spy/memcached/ArcusClient.java
smget 연산의 최종결과를 계산할 때 사용되는 getSubList의 로직을 변경한다.
기존의 로직보다 간결한 로직으로 수정하여 가독성을 증가시킨다.
- 삼항연산자 -> Math.min 사용
- 조건문 Depth 감소
=> INTERNAL: Change logic in getSubList method.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/CachedData.java, src/main/java/net/spy/memcached/internal/CollectionGetFuture.java, src/main/java/net/spy/memcached/ops/CollectionGetOperation.java, src/test/java/net/spy/memcached/transcoders/CachedDataTest.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/jam2in/arcus-works/issues/406
기존에는 collection get을 호출할 경우 decode 로직이 IO 쓰레드에서 수행됩니다.
이러한 decode 로직을 appilcation의 Worker 쓰레드에서 수행하도록 변경하였습니다.
응용이 get()을 호출할 경우 decode를 진행하는 로직으로 변경하였습니다.
변경된 로직은 아래와 같은 절차를 거칩니다.
1. 응용에서 collection get api 호출한다.
2. api 내에서 CollectionGetFuture 생성을 하고 decode 수행에 필요한 TransCoder 주입한다.
3. IO 쓰레드에 의해 callback 함수 gotData() 호출되고 decode 시 필요한 CachedData 인스턴스를 생성하고 이를 CollectionGetFuture 인스턴스에 put 또는 add한다.
4. 응용은 리턴 받은 CollectionFuture의 get() 함수를 호출한다.
5. CollectionGetFuture의 get()이 호출되면 super class로부터 collection의 타입에 맞게 리턴할 value를 받아온다. 이후 tc.decode()를 수행한다. 그 결과로 나온 T타입의 객체를 결과 value(list, map, set 중 하나)에 추가하고 사용자에게 value를 리턴한다.
기존 PR에서는 CollectionGetFuture 내에서 분기 처리를 통해
Lop,Sop,Bop,Mop를 구별하여 처리해주었습니다.
하지만 이는 코드를 읽기 쉽지 않아서
CollectionGetFuture …
=> ENHANCE: Modify decoding logic in collection get api.

src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java
오버라이드된 메서드의 경우 
상위 클래스에서 동일한 메서드가 호출되어도
오버라이드된 메서드가 호출된다.
FrontCacheMemcachedClient 클래스에서 위 사항을 반영하지 않고 
작성된 불필요한 메서드들을 모두 제거한다.
=> INTERNAL: Remove redundant method in FrontCacheMemcachedClient.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java
기존의 Flush 동작은 가장 최근 연산된 
op 인스턴스의 결과값만을 반영한다.
즉, 실패한 연산이 있더라도 최근 연산이 성공일 경우
성공으로 최종 결과가 연산된다.
실패한 연산이 있는 경우만 결과를 false로 설정하도록 구현을 변경한다.
https://github.com/naver/arcus-java-client/pull/646
=> FIX: Incorrect boolean result in asycn flush() method.

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java
https://github.com/naver/arcus-java-client/issues/636
기존에는 무한 대기하던 시간을
**(BulkGetFuture가 가진 Ops의 크기 * DefaultTimeout)** 으로 변경하였습니다.
합리적으로 생각해보면 하나의 Op가 처리될때 700L로 timeout이 설정됩니다.
여러 op가 있을 경우는 ops의 크기만큼 timeout을 가지면
가장 단순한 접근으로 해결할 수 있다고 생각합니다.
timeout 설정에 대해 다른 생각이 있으시면 코멘트 부탁드립니다.
=> FIX: Infinity waiting with get method in BulkGetFuture.

src/main/java/net/spy/memcached/ArcusClient.java
asyncCollectionExist의 경우 현재 Transcoder를 인자로 사용한다.
asyncCollectionExist 내에서는 tc가 사용되지 않고 wrapper 메서드인 
asyncSopExist 내의 SetExist 생성자를 통해 tc.encode를 수행한다.
추후 다른 자료구조들의 Exist api 확장을 고려한다해도
encode는 현재와 마찬가지로 asyncLopExist, asyncBopExist 등에서 수행시키면 된다.
asyncCollectionExist내에서는 decode를 수행하는 경우를 고려할 수 있는데
서버로부터의 응답값이 자료구조 내의 value가 아닌 EXIST, NOT_EXIST이기 때문에
docode로직 또한 사용되지 않는다고 예상할 수 있다.
결론적으로 Transcoder 인자를 제거할 수 있다.
그 외 사항으로는 삼항 연산자 로직을 간결하게 변경한다.
=> INTRENAL: Refactor asyncCollectionExist api.

src/main/java/net/spy/memcached/collection/BTreeGet.java, src/main/java/net/spy/memcached/collection/CollectionGet.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
smget, bopBulkGet 등의 bop Get api들의 
서버 응답을 파싱하는 로직을 리팩토링 하기 위해
가장 간단한 형태의 api인 bop get의 로직을 분석하고 리팩토링한다.
기존의 로직은 decodingItemHeader 메서드에는
의미가 불분명한 변수명과 하드코딩된 상수값들이 존재한다.
코드를 읽기 쉽게 하기 위해 이러한 값들을
적절히 변경한다.
또한 handleRead 메서드 내에 사용되지 않는 변수 제거 및
String 객체 사용 최적화를 진행한다.
=> INTERNAL: Refactor collectionGetOp and BTreeGet.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetFuture.java, src/main/java/net/spy/memcached/ops/BTreeFindPositionWithGetOperation.java, src/main/java/net/spy/memcached/ops/BTreeGetByPositionOperation.java, src/main/java/net/spy/memcached/ops/BTreeInsertAndGetOperation.java, src/main/java/net/spy/memcached/ops/CollectionGetOpCallback.java, src/main/java/net/spy/memcached/ops/CollectionGetOperation.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/jam2in/arcus-works/issues/406
아래 3가지 api는 IO 쓰레드가 역직렬화 작업을 수행하도록 구현되어있다.
- asyncBopFindPositionWithGet
- asyncBTreeInsertAndGet
- asyncBopGetByPosition
역직렬화 작업을 응용의 worker thread가 get을 호출하여
api의 결과를 받고자 할 때, 수행하도록 변경한다.
https://github.com/naver/arcus-java-client/pull/634
- 위의 PR과 마찬가지로 **Future에서 콜백을 호출하여 decode를 수행하도록 변경**하였습니다.
- positon이 사용되는 api의 경우 해당 position 값을 콜백에서 처리하도록 변경하였습니다.
- 기존에는 gotData의 인자로 넘어 왔는데 해당 값을 Map의 key로 사용하면 bKey를 저장하지 못하는 문제가 발생하여 이와 같이 변경했습니다.
- `BTreeStoreAndGetFuture`의 경우 아래와 같은 문제가 있습니다.
- 기존 구현은 getElement를 통해 연산의 Element의 참조를 바로 반환합니다.
- 만약 연산이 완료되지 않은 상황에서 getElement를 호출할 경우 부정확한 값이 리턴됩니다.
- 이러한 문제를 내부에서 get()을 통해 연산이 완료됨을 보장하고 Element를 리턴하도록 변경했습니다.
=> INTERNAL: Change decode logic in asyncBopGet APIs.

pom.xml
JDK 17 이슈 대응을 위한 ZK Client 의존성 버전 업데이트입니다.
```xml
<arg>-Xlint:-classfile</arg> 
```
[ZK Client 3.5.9에 포함된 의존성 중 하나](https://github.com/apache/zookeeper/blob/release-3.5.9/pom.xml#L454-L460)가 scope provided로 포함되어 있습니다.
arcus-java-client 컴파일 옵션에 `-Xlint:-classfile`을 추가하는 이유는 위 의존성의 scope가 provided이기 때문입니다.
provided는 컴파일 하는 시점에 참조되지만, 컴파일 결과물에는 포함되지 않습니다.
ZK Client 3.5.9에서 이 의존성을 사용하면서도 scope를 provided로 명시했기 때문에 ZK Client 빌드 결과물에 포함되지 않습니다.
따라서 arcus-java-client를 컴파일 하려고 하면 어노테이션을 찾을 수 없다고 컴파일 워닝이 찍힙니다.
```
[WARNING] Cannot find annotation method 'value()' in type 'edu.umd.cs.findbugs.annotations.SuppressFBWarnings': class file for edu.umd.cs.findbugs.annotations.SuppressFBWarnings not found
[WARNING] Cannot find annotation method 'justification()' in type …
```
=> INTERNAL: Upgrade ZK Client dependency version from 3.4.14 to 3.5.9

src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java, src/main/java/net/spy/memcached/collection/BTreeGet.java, src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java, src/main/java/net/spy/memcached/collection/CollectionGet.java, src/main/java/net/spy/memcached/collection/ListGet.java, src/main/java/net/spy/memcached/collection/MapGet.java, src/main/java/net/spy/memcached/collection/SetGet.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/jam2in/arcus-works/issues/433
기존 item Header를 파싱하는 로직은
handleRead 내에서 eFlag 유무와 eachRecordParseCompleted()의 여부에 따라
decodeItemHeader를 2번 호출하는 복잡한 로직이다.
이러한 로직을 버퍼로부터 데이터를 받고 space를 만날 때 마다
파싱 대상을 String 단위로 `List<String>`에 추가해주고
해당 List의 길이를 통해 eFlag 여부를 확인하도록 변경한다.
- 슈퍼 클래스인 CollectionGet에 추상 메서드 `decodeItemHeader(List<String>)` 생성
- 이의 구현체들 중 sopGet,bopGet,lopGet,MopGet은 위 함수를 통해 handleRead() 로직 수행
- 나머지 BTreeFPG 등은 위 함수의 구현 없이 기존 `decodeItemHeader(String)`를 통해 로직 수행
- BTreeFPG 등은 컴파일 에러 방지를 위해 함수 선언과 비어있는 body로 구현되어 있음
- 이는 해당 PR이 merge되고 나서 점진적으로 변경 예정
=> INTERNAL: Change parsing itemHeader logic in CollectionGetOpImpl.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java, src/test/manual/net/spy/memcached/collection/btree/BopInsertAndGetTest.java
기존 `BTreeInsertAndGet`의 경우 
`CollectionInsert<T>`를 상속 받아 구현된다.
이러한 점은 아래와 같이 서버로부터 Data를 read하는 연산들과 일관성이 없는 구현이다.
- collectionGet
- BTreeGetByPosition
- BTreeFindPositionWithGet
그래서 상속 대신 구성을 통해 `CollectionInsert<T>`의 기능을 그대로 가져오는 구현으로 변경한다.
이러한 변경은 자식 클래스가 사용하지 않는 부모 클래스의 기능들을 상속받지 않아도 되며,
다른 api들과의 일관성 또한 가질 수 있다.
또한 내부적으로 사용되던 enum 타입이 존재하는데
이는 코드의 가독성을 감소시키고 구현을 복잡하게 만든다.
이를 외부에서 선언하여 간결하게 변경한다.
마지막으로 not trimmed인 경우에 대한 테스트 케이스를 추가하였다.
아래 PR이 merge 되고
- https://github.com/naver/arcus-java-client/pull/661
해당 PR이 approve 되면 BTreeInsertAndGet의 
handleRead() 로직을 변경하는 구현에 대한 PR 올리겠습니다.
=> INTERNAL: Refactor BTreeInsertAndGet to extend CollectionGet.

src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java
기존 BTreeStoreAndGetFuture의 getElement 동작은 
곧바로 element 변수를 리턴하는 로직인데
이는 Future의 get()이 완료되지 않을 경우 
리턴되는 결과가 부정확하다.
**즉, 응용의 Worker Thread가 Blocking되어 정확한 결과값을 리턴받도록 변경**해야한다.
getElement() 내부적으로 get()을 호출하여
정확한 element를 리턴하도록 변경한다.
=> FIX: getElement logic in BTreeStoreAndGetFuture.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeGetResult.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/ops/BTreeGetBulkOperation.java, src/main/java/net/spy/memcached/ops/MultiBTreeGetBulkOperationCallback.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/jam2in/arcus-works/issues/406
BopGetBulk 연산의 경우에도 읽어야하는 Value의 decode() 수행은 IO 쓰레드가 담당한다.
이러한 로직을 addResult() 메서드를 통해 WAS의 worker 쓰레드가 담당하도록 변경한다.
해당 연산의 경우, 사용자가 받게 될 result는 아래와 같은 구조이다.
```
----------------------------------------
BTreeKey1(not BKey) | BTreeGetResult1
BTreeKey2(not BKey) | BTreeGetResult2
BTreeKey3(not BKey) | BTreeGetResult3
----------------------------------------
```
BTreeGetResult 객체의 내부에 TreeMap이 null이 아닌 경우는 
서버로부터 받은 elem이 존재하고 null인 경우는 elem이 없는 BTree를 조회한것이다.
**즉, TreeMap이 null인 경우는 addResult()를 수행하지 않아도 된다.**
참고로 해당 로직은 콜백의 gotKey()의 elemCount 파라미터를 통해 수행된다.
그외, TreeMap이 null이 아닌 경우는 첫번째 get() 호출에서만 
addResult() 로직을 수행하기 위해 isEmpty 검사를 진행한다.
결론적으로 기존의 addResult 메서드 구현보다 검증해야할 부분이 많이 존재한다.
그 외 나머지 사항은 기존의 Decode 로직 변경 PR들과 유사하다.
아래 PR을 참고 할 …
=> ENHANCE: Change decode logic in BTreeGetBulk api.

src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java
https://github.com/jam2in/arcus-works/issues/441
기존 구현은 사용자가 TCP Keep Alive 옵션을 설정하는 인터페이스를 제공하지 않는다.
이를 `ConnectionFactoryBuilder`를 통해 사용자가 설정할 수 있도록 제공한다.
keepAlive의 기본 옵션은 `false`이다.
=> FEATURE: Add TCP connection keep-alive option.

src/test/java/net/spy/memcached/SocketTest.java
https://github.com/jam2in/arcus-works/issues/441
아래와 같이 생성된 소켓에 대해 keepAlive 옵션의 
활성화 여부를 가져올 수 있다.
이를 통해 해당 TCP 연결에 keepAlive 옵션이 적절히 적용되었는지 테스트 가능하다.
=> TEST: Add Socket keepAlive option test.

src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/jam2in/arcus-works/issues/438
아래 PR로부터 파생되어 변경사항을 단계적으로 반영하기 위한 PR입니다.
https://github.com/naver/arcus-java-client/pull/669
=> ENHANCE: Remove redundant lock and sync tool.

src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/collection/BTreeGetBulk.java, src/main/java/net/spy/memcached/collection/BTreeSMGet.java, src/main/java/net/spy/memcached/internal/BulkFuture.java, src/main/java/net/spy/memcached/ops/APIType.java, src/main/java/net/spy/memcached/transcoders/InspectObjectSizeTranscoder.java, src/main/java/net/spy/memcached/util/KetamaNodeLocatorConfiguration.java
#671
명시할 필요 없는 접근 제어자를 제거하였습니다. 제거한 경우는 다음과 같습니다.
`interface`는 항상 공개된 메서드만 제공합니다. 다시 말해 `public`와 같은 접근 제어자는 명시하지 않는 것이 좋습니다.
`interface`는 `static`이라는 키워드는 명시할 필요가 없습니다. 붙이지 않더라도 동일하게 동작합니다.
`enum`은 항상 `static`으로 존재하므로 키워드가 필요하지 않으며, 별도로 명시하는 것은 권장되지 않는 방법입니다.
`enum`은 외부에서 생성하는 객체가 아니므로 항상 `private` 접근 제어자의 생성자를 가집니다. 따라서 명시하지 않는 것이 좋습니다.
=> INTERNAL: Remove unnessesary access modifiers

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/collection/ElementMultiFlagsFilter.java, src/main/java/net/spy/memcached/collection/MapDelete.java, src/main/java/net/spy/memcached/collection/MapGet.java, src/main/java/net/spy/memcached/internal/BroadcastFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
자료형의 직접적인 사이즈 비교 대신 `isEmpty` 메서드를 사용하여 요소가 비었는지를 확인하도록 수정하였습니다.
=> INTERNAL: Use isEmpty method to simplify empty checking

src/test/java/net/spy/memcached/ProtocolBaseCase.java
현재 testGetStats 관련 테스트 코드들은
mc가 1개만 띄워져 있는 상황을 가정하여 테스트 코드가 작성되어있다.
mc가 여러개 띄워진 상태에서 해당 테스트 코드를 
수행할 시 fail이 발생한다.
그래서 연결된 client의 nodes 수만큼 검증하도록 변경한다.
추후 Github action을 3개의 mc가 띄워진 형태로 변경할 예정입니다.
현재 Local에서 3개의 mc을 띄우고 아래 테스트 코드를 실행하면 fail이 발생합니다.
=> TEST: Fix expected result invoking getStat.

.github/workflows/ci.yml
docker compose를 사용하여 arcus 환경 설치를 위한
Github Action 변경입니다.
아래와 같은 변경이 발생합니다.
- 시간 단축
- multi node 테스트
=> TEST: Change github action config.

src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java
https://github.com/jam2in/arcus-works/issues/470
위 이슈를 해결하는 PR 입니다.
=> TEST: Fix test failure due to unsupported reflection operation on JDK 12+

.github/workflows/ci.yml
CI에서 2개의 테스트를 1개의 명령어로 수행하는 부분을 2개의 명령어로 분리했습니다.
1개의 명령어로 수행할 경우, 테스트 실패 메세지가 나왔을 때 어느 옵션의 테스트에서 비롯된 실패 메세지인지 파악하기 힘듭니다.
2개의 명령어로 분리할 경우, CI에서 각 테스트 단계가 분리되어 있기 때문에 어느 옵션의 테스트에서 비롯된 실패 메세지인지 파악하기 쉽습니다.
또한 2개의 명령어로 분리했더라도, 앞의 명령어가 실패하면 뒤의 명령어는 수행하지 않는 점은 동일합니다.
=> TEST: Separate CI into 2 phases, NOT using ZK and using ZK.

.github/workflows/ci.yml
동일한 PR 혹은 브랜치에 새로 커밋이 Push 되었을 때, 이전에 CI가 돌아가는 중이었다면 이전 CI를 자동으로 취소합니다.
- 돌아가고 있는 Github Action을 서로 구분할 논리적 이름입니다.
- 동일한 group을 갖고 있으면 `cancel-in-progress` 값의 여부에 따라 이전 Github Action을 취소할 수 있습니다.
- 현재 돌아가는 Github Action의 이름입니다. 
- ci.yml 파일에 `name: CI`로 되어 있으므로, `CI` 값이 들어갑니다.
- PR의 번호입니다. 
- 예를 들어 https://github.com/naver/arcus-java-client/pull/691 PR 같은 경우, `691` 값이 들어갑니다.
- PR이 아닌 경우에 사용되는 브랜치 이름, 혹은 태그 이름입니다.
- master 브랜치에 Push 했다면 `master` 값이 들어갑니다.
- Push에 태그 이름이 함께 특정되었을 경우, 예를 들어 태그가 `1.13.5`라면 `1.13.5` 값이 들어갑니다.
- 이전에 돌아가던 Github Action 중, 새로 돌아가야 하는 Github Action의 그룹과 동일한 그룹이 있으면 이전 Github Action을 취소합니다.
- false이면 취소하지 않습니다.
=> TEST: Cancel previous CI when PR or branch is pushed.

src/main/java/net/spy/memcached/ArcusClient.java
네트워크 지연이 있는 상태에서, ArcusClint 객체의 Operation Queue에 많은 Operation이 쌓여 있는 경우, 기존의 ArcusClient.shutdown()을 수행하면 반드시 2초(SHUTDOWN_TIMEOUT_MILLISECONDS)를 기다려야 합니다.
ArcusClient의 부모 클래스인 MemcachedClient 클래스의 shutdown(long, TimeUnit)을 통해 기다리는 시간을 조절할 수 있으나, CacheManager.shutdown()를 수행할 수 없다는 문제가 있습니다.
따라서 ArcusClient.shutdown(long, TimeUnit)을 추가하여 기다리는 시간도 조절하고, CacheManager.shutdown()도 수행할 수 있도록 했습니다.
=> FEATURE: Add overriden method "shutdown(long, TimeUnit)" to ArcusClient.

docs/07-btree-API.md, src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java
- asyncBopGetBulk 메서드와 asyncBopSortMergeGet 메서드의 count, offset에 대한 조건이 잘못 명시되어 있던 것을 수정합니다.
=> FIX: apply limits of count and offset to bop bulk methods

docs/05-set-API.md
현재 문서를 구현에 맞춘 형태로 변경하였습니다.
https://github.com/jam2in/arcus-works/issues/455
=> DOCS: Fix return value in asyncSopPipedExistBulk api.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/main/java/net/spy/memcached/internal/result/SMGetResult.java, src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/SMGetResultOldImpl.java
SMGetFuture를 추상 클래스에서 일반 클래스로 변경했습니다.
일반 클래스로 변경하면서 각 smget 메소드에서 구현했던 추상 메소드를 SMGetFuture 내로 옮겼습니다.
SMGetFuture를 통해 접근 가능한 여러 필드들은 SMGetResult 클래스를 만들어 접근하도록 했습니다.
SMGetResult 객체에 직접 참조를 통해 필드에 Write 하게 했는데, 간접 참조로 바꿔야 더 명확하다면 간접 참조로 바꾸겠습니다.
- 직접 참조 예시 : `r.addToMergedResult(eachResult);`
- 간접 참조 예시 : `r.getMergedResult().addAll(eachResult)`
SMGetFuture 내의 필드로 `SMGetResult<?> smGetResult`를 두었는데, `SMGetResult<T>`가 아닌 이유는 smget 메소드의 return type이 `SMGetFuture<List<SMGetElement<G>>>`이기 때문입니다.
`class SMGetFuture<T>`에서 `T = List<SMGetElement<G>>`로부터 내부의 `<G>`를 가져올 수 없어 `SMGetResult<?>` 형태의 필드를 둔 것입니다.
또한 현재 형태의 리팩토링은 Future 클래스에서 public으로 노출하는 메소드를 getter에 한정하게 되어 다음의 이슈를 해결할 수 있는 방안 중 하나가 될 것 같습니다.
- https://github.com/naver/arcus-java-client/issues/632
=> CLEANUP: Refactored SMGetFuture.

src/main/java/net/spy/memcached/internal/GetFuture.java
GetFuture.rv 필드는 내부적으로만 사용해야 하는 객체입니다.
그럼에도 getter 메소드가 있었던 것은 `public GetFuture(GetFuture parent)` 생성자에서 `this.rv = parent.getRv()`를 호출하기 위함인 것으로 보입니다.
그러나 GetFuture.rv 필드는 GetFuture 클래스 내부라면 서로 다른 객체 간이라도 접근이 가능하므로, getter가 필요 없습니다.
=> INTERNAL: Remove unintentionally exposed public method, GetFuture.getRv()

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/GetFuture.java, src/main/java/net/spy/memcached/internal/result/GetResult.java
TranscoderService는 별도의 Thread Pool에서 비동기적으로 decode를 수행합니다.
TranscoderService의 Thread Pool은 coreSize 1, maxSize 10으로 되어 있습니다.
CPU 리소스가 부족하거나, 동시에 decode 해야 할 데이터가 너무 많이 쌓이면 TranscoderService의 Thread Pool이 제시간 내에 decode를 수행하지 못할 수 있습니다.
따라서 TranscoderService를 통해 decode 하는 것이 아니라, 응용의 Worker Thread가 get 연산의 결과를 가져가려고 하는 순간에 decode를 수행하도록 변경했습니다.
변경 사항으로 인한 기대 효과는 get 연산의 성능 향상 및 CPU 리소스 부족 혹은 동시에 decode 해야 하는 대상이 너무 많아서 생기는 Timeout 오류 빈도 감소입니다.
=> CLEANUP: Remove TranscoderService from asyncGet()

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
https://github.com/jam2in/arcus-works/issues/482
위 이슈 일부를 반영했습니다.
1. 인자 순서 변경
2. smgetMode => boolean unique
3. ~hasDuplicateBKeyResult() 메소드 추가~
4. ~EachResult가 empty result인 경우 고려~
=> CLEANUP: Refactored parameter of smget()

src/main/java/net/spy/memcached/internal/result/SMGetResult.java, src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/SMGetResultOldImpl.java
https://github.com/jam2in/arcus-works/issues/482
위 이슈 일부를 반영했습니다.
- hasDuplicateBKeyResult() 메소드 추가
=> INTERNAL: Add hasDuplicatedBKeyResult() to SMGetResult.

src/main/java/net/spy/memcached/internal/result/SMGetResultOldImpl.java
https://github.com/jam2in/arcus-works/issues/482
위 이슈 일부를 반영했습니다.
- EachResult가 empty result인 경우 고려
=> FIX: Consider emptiness of each result when merge in old SMGetResult.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/result/SMGetResult.java, src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/SMGetResultOldImpl.java
https://github.com/jam2in/arcus-works/issues/482
위 이슈 일부를 반영했습니다.
- OperationStatus List 타입 제거
=> INTERNAL: Change failedOpreationStatus and resultOperationStatus from List<OperationStatus> to CollectionOperationStatus.

src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
New SMGetResult의 Merge 메소드에 주석을 추가했습니다.
=> INTERNAL: Add comments to new SMGetResult merge method.

src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
new SMGetResult.makeResultOperationStatus()의 불필요한 TRIMMED_KEYS 결과를 제거하는 부분의 주석을 보강하고 comp 변수를 사용하도록 했습니다.
=> INTERNAL: Enhance comments to new SMGetResult make result method.

src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/SMGetResultOldImpl.java
Old, New 포함 SMGetResult의 Merge 메소드의 불필요한 Indent Depth를 줄였습니다.
=> CLEANUP: Reduce indent depth of SMGetResult merge method.

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/result/GetResult.java, src/main/java/net/spy/memcached/internal/result/GetResultImpl.java
아래 PR로부터 파생된 PR입니다.
https://github.com/naver/arcus-java-client/pull/711
인터페이스 기반의 GetReuslt 사용을 위해 기존의 GetResult 구현을 변경하였습니다.
CachedData 레퍼런스를 외부에서 생성자 주입을 통해 전달하도록 변경했습니다.(기존에는 setter 주입)
=> INTERNAL: Use GetResult interface in asyncGet api.

src/main/java/net/spy/memcached/MemcachedClient.java
asyncGetBulk와 asyncGetsBulk에서 사용되는
addKeyToChunk 메서드의 인자 리팩토링과 주석을 추가하였습니다.
또한 메서드 내의 변수명을 직관적으로 변경하였습니다.
=> INTERNAL: Refactor logic and add comments in addKeyToChunk.

src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/GetFuture.java, src/main/java/net/spy/memcached/internal/result/GetsResultImpl.java, src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
- 오전에 오프라인으로 논의된 asyncGets API의 Future 리턴 타입을 `OperationFuture` -> `GetFuture`로 변경하였습니다.
- 아래의 코멘트의 Transcoder 문제 때문에 `CASGetResult<T>`를 사용해서 구현하였습니다.
- https://github.com/naver/arcus-java-client/pull/710#discussion_r1437921170
- GetResult 인터페이스를 통해 아래 문제를 해결하였습니다.
- ~~이를 해결하기 위해 해당 PR은 생성자 내에서 `super(null)`을 사용하였습니다. 아래 코멘트는 다른 방안들입니다.~~
- https://github.com/naver/arcus-java-client/pull/710#discussion_r1439119905
- `@Deprecated`를 사용하려면 `asyncGetsNew()` 와 같은 새로운 함수를 정의하고 기존`asyncGets()`에 `@Deprecated`을 붙여줘야합니다. 메서드의 리턴값만 다를 경우 오버로딩이 적용되지 않기 때문입니다. 우선은 로직에 대한 리뷰를 먼저 받기 위해 기존 메서드의 리턴값을 바로 변경하였습니다. 
- ~~GetResult 생성자에서 CachedData를 외부로부터 주입 받는 로직은 별도의 PR로 반영하겠습니다.~~
=> INTERNAL: Change asyncGets return future type.

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/test/java/net/spy/memcached/ProtocolBaseCase.java
asyncGetBulk, asyncGetsBulk 연산에서 TranscoderService를 사용하지 않고
decode()를 WAS의 worker thread 수행하도록 변경하였습니다.
기존 테스트 코드에서는 테스트 코드의 메인 쓰레드가 decode될 동안 Blocking이 되어 IO 스레드로부터예외인 `ExecutionException e`이 발생하였고, 
현재 구현에서는 테스트 메인 쓰레드가 Decode 작업을 수행하여 AssertionError가 발생하기 때문에 Throwable를 인자로 받도록 변경하였습니다.
=> INTERNAL: Remove transcoder service logic in bulkGet apis.

src/main/java/net/spy/memcached/internal/BulkGetFuture.java
`FrontCacheBulkGetFuture` 타입을 리턴받은 응용이
부모 클래스의 메서드인 `isTimeout()`을 호출할 경우 
정확한 값을 리턴하지 않는 문제가 있다.
`AtomicBoolean`을 이용해서 
copy의 대상이 되는 `BulkGetFuture`의 `isTimeout` 값을 
새로 생성될 `FrontCacheBulkGetFuture`에서 `isTimeout()`을
호출할 때 사용하도록 한다.
호출되는 값의 결과가 연산 완료 전/후에 따라 변경되기에
`AtomicBoolean`을 사용하였다.
=> FIX: Invalid isTimeout value when creating BulkGetFuture with another object.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
- future에 있는 변수명과 함수명을 이해하기 쉽게 변경합니다.
- PipedCollectionFuture에서 mergedResult에 항상 실패한 Operation에 대한 상태만 들어있기 때문에 failedResult로 변경합니다.
- BulkOperationFuture 에서 setOperations 메서드는 새로운 값을 필드에 할당하는 것이 아닌 기존 필드에 데이터를 추가(add)하는 로직이기 때문에 addOperations 로 변경합니다.
=> CLEANUP: rename variable clearer in futures

.github/workflows/ci.yml
아래 테스트는 ZK와 함께 구동될 경우 Skip 되는 테스트 클래스입니다.
(assumeTrue 사용)
- ObserverTest
ZK 없이 테스트하는 경우 Single cached node에 테스트 코드를 수행하는 경우라서
클러스터 환경에서 나머지 테스트 케이스들을 커버합니다.
위 테스트를 제외한 나머지 테스트 케이스들의 중복 수행을 수정하는 PR입니다.
(6min -> 3min 으로 CI 시간 단축)
아래는 기존에 실행되던 테스트 방식에서 skip 되는 테스트 케이스들에 대한 정리입니다.
https://www.notion.so/jam2in/skip-test-case-94ac9e83e6024ec68e722b3ac67a287f?pvs=4
=> TEST: Remove duplicated test case regardless ZK is running or not.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/test/java/net/spy/memcached/ArcusTimeoutTest.java, src/test/java/net/spy/memcached/BinaryClientTest.java, src/test/java/net/spy/memcached/CancellationBaseCase.java, src/test/java/net/spy/memcached/DoLotsOfSets.java, src/test/java/net/spy/memcached/ProtocolBaseCase.java, src/test/java/net/spy/memcached/TimeoutTest.java, src/test/manual/net/spy/memcached/bulkoperation/BulkDeleteTest.java, src/test/manual/net/spy/memcached/frontcache/LocalCacheManagerTest.java, src/test/manual/net/spy/memcached/test/MultiNodeFailureTest.java
- https://github.com/jam2in/arcus-works/issues/517
- 가변 인자를 사용하는 API를 Deprecate 시킵니다.
- 이에 필요없는 테스트 코드를 제거하고, 테스트 코드에서 Deprecated된 메서드를 사용하지 않도록 변경하였습니다.
=> CLEANUP: deprecate APIs using varargs

src/main/java/net/spy/memcached/internal/result/SMGetResult.java, src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
https://github.com/naver/arcus-java-client/pull/715
위 PR의 New smget 버전입니다.
작업 방식은 위 PR과 동일합니다.
=> INTERNAL: Add new merge method with improved performance to new SMGetResult.

src/main/java/net/spy/memcached/collection/BKeyObject.java
https://github.com/jam2in/arcus-works/issues/525
BKeyObject의 생성자를 long 타입과 byte[] 타입을
각각 인자로 가지는 생성자만 유지하도록 변경합니다.
=> INTERNAL: Refactor BKeyObject constructor.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeGetResult.java, src/main/java/net/spy/memcached/internal/BTreeStoreAndGetFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetFuture.java, src/main/java/net/spy/memcached/internal/result/BopGetBulkResultImpl.java, src/main/java/net/spy/memcached/internal/result/BopGetByPositionResultImpl.java, src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/BopStoreAndGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/LopGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/MopGetResultImpl.java, src/main/java/net/spy/memcached/internal/result/SopGetResultImpl.java, src/main/java/net/spy/memcached/ops/BTreeFindPositionWithGetOperation.java, src/main/java/net/spy/memcached/ops/BTreeGetBulkOperation.java, src/main/java/net/spy/memcached/ops/BTreeGetByPositionOperation.java, src/main/java/net/spy/memcached/ops/BTreeInsertAndGetOperation.java, src/main/java/net/spy/memcached/ops/CollectionGetOpCallback.java, src/main/java/net/spy/memcached/ops/CollectionGetOperation.java, src/main/java/net/spy/memcached/ops/MultiBTreeGetBulkOperationCallback.java, src/main/java/net/spy/memcached/util/BTreeUtil.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/jam2in/arcus-works/issues/486
1. 기존에 addResult 콜백을 사용하던 모든 api들의 `decode()` 로직 수행을 콜백 메서드가 아닌 XXXResult 객체를 통해 수행하도록 변경하였습니다.
2. ArcusClient에 존재하던 `makeBTreeElement` 메서드를 삭제하고 BTreeUtil 클래스의 static 메서드로 변경하였습니다.
3. `BopGetResultImpl`와 `BopGetBulkResultImpl`의 경우 BKey 타입에 따라 생성할 Tree 객체의 타입이 달라집니다. 그래서 해당 트리를 호출 api 내부에서 생성 후 Result 객체로 넘겨주도록 구현하였습니다.
- bopGet은 `BopGetResultImpl`의 생성자의 인자로 넘겨줌
- bopBulkGet은 `gotKey` 콜백 메서드 내부에서 `addEachBTree`의 인자로 넘겨줌
아래 청크 단위로 변경지점 파악하시면 리뷰하는데 수월할 것 같습니다.
- `LopGetResultImpl`
- `MopGetResultImpl`
- `SopGetResultImpl`
- `BopGetByPositoinResultImpl`
- `BopGetResultImpl`
- `BopGetBulkResultImpl`
- `BopStoreAndGetResultImpl`
=> INTERNAL: Change decode logic in collection Get apis.

src/main/java/net/spy/memcached/internal/result/BopGetResultImpl.java
BopGetResultImpl에서 사용하던 `BKeyObject(ByteArrayKey)`의 생성자가 
아래 PR이 머지되면서 사용할 수 없게 됩니다.
https://github.com/naver/arcus-java-client/pull/736
`BKeyObject(byte[])` 생성자를 사용하도록 수정합니다.
=> FIX: Change BKeyObject constructor in BopGetResultImpl

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/internal/BroadcastFuture.java
https://github.com/jam2in/arcus-works/issues/503
Braodcast 연산의 원자성 보장을 위해서
HashMap에 생성된 op를 담아뒀다가 
일괄적으로 node에 전달하는 로직으로 변경했습니다.
`opsMap `의 경우 응용의 worker-thread에 의해서만
접근되어지기에 `HasnMap<>()` 구현체를 사용했습니다.
=> INTERNAL: Using addOperations for atomicity in Broadcast Op.

src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java, src/test/manual/net/spy/memcached/frontcache/LocalCacheManagerTest.java
기존 생성자처럼 `super(new CountDownLatch(0), 1);`을 통해
GetFuture를 초기화 할 경우 다음과 같은 문제가 발생한다.
Future.get()을 호출하면 `Future.get(1L, Mills)`로 동작하게 되고
TimeoutException이 발생하게 된다.
```java
//LocalCache를 활성화 한 뒤 호출
Future<Object> f = client.asyncGet(key);
Object result = f.get(); // TimeoutException 발생
```
1L을 DefaultTimeout 값으로 변경합니다.
기존에  LocalCacheManagerTest가 Ignore 처리되어서
테스트 코드 상에서 확인되지 않았습니다.
참고로 기존에 붙은 `@Ingore`는 java client의 
첫 커밋부터 유지되었기에 그 의도를 파악하기 어렵습니다.
=> FIX: FrontCacheGetFuture default timeout value.

src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java, src/main/java/net/spy/memcached/plugin/LocalCacheManager.java, src/test/manual/net/spy/memcached/frontcache/LocalCacheManagerTest.java
https://github.com/jam2in/arcus-works/issues/398
사용되지 않는 생성자와 get() 메서드의 tracscoder 인자를 삭제시켰습니다.
=> REFACTOR: Remove unused arg and constructor in localCacheManager.

src/main/java/net/spy/memcached/plugin/FrontCacheGetFuture.java
Default 값으로 사용되던 FrontCacheGetFuture의 timeout을
parent의 timeout 값으로 변경합니다.
=> INTERNAL: Change timeout value to parent property.

src/test/manual/net/spy/memcached/frontcache/LocalCacheManagerTest.java
다른 테스트 케이스와 중복되는 key 중복을 방지하기 위해
key에 `System.nanoTime()`을 추가한다.
https://github.com/jam2in/arcus-works/issues/545
=> TEST: Fix LocalCacheManager key list duplication.

src/main/java/net/spy/memcached/collection/BTreeGetBulk.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/160
- 기존에 BTreeGetBulk에서 사용하지 않던 keyHeaderReady 함수를 삭제했습니다.
- smget과 유사하게, header 개수를 의미하는 headerCount 변수를 BTreeGetBulk 인터페이스에 추가했습니다.
- headerCount 변수를 headerReady 함수에서 사용하도록 했습니다.
- 기존에는 space 문자를 만날 때마다 String 객체를 매번 생성합니다.
- spaceCount가 btree 응답 형식 header 개수(3개)일 때만 byteBuffer에서 String 객체를 생성하도록 했습니다.
- 기존에는 서버가 보낸 응답이 ELEMENT로 시작하는지 확인하기 위해서 space마다 String 객체를 만듭니다. 그렇지 않다면 byteBuffer.write를 합니다.
- spaceCount == 3일때만 String을 만들고, 기존 구현과 같은 동작을 하기 위해서 약간의 수정을 했습니다.
- ELEMENT로 시작하지 않는 String의 경우, byteBuffer.write를 실행한 다음, continue로 반복문의 다음 로직을 건너뛰었습니다.
- 기존에는 String을 split하고 decodeItemHeader 함수에서 다시 한번 split합니다.
- 이미 split된 값들을 위 함수에서 재사용하도록 함수 인자를 변경했습니다.
=> REFACTOR: Check spaceCount before String conversion in BTreeGetBulk.handleRead

src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/159
- 다른 handleRead 함수와는 다르게 불필요한 null 변수 선언하는 부분이 있었습니다.
- 나중에 선언후 바로 대입하는 것으로 변경했습니다.
- `BTreeFindPositionOperationImpl`에서 position을 확인하기 위해 `parseInt`를 try-catch 문으로 감싸고 있습니다.
- 서버의 응답값이 `position=string\r\n`과 같은 형태로 반환되는 경우를 처리하는 부분입니다.
- 그런데 catch 문안에서 아무 동작을 하지 않아서 불필요합니다. 그리고 try catch의 유무와 상관없이 테스트 로직이 정상적으로 수행됩니다.
- 일반적인 에러(`NOT_FOUND`)의 경우, if-else로 분기하기 때문에 try 문과 상관없이 정상적으로 처리됩니다.
- 이와 유사한 `BTreeFindPositionWithGetOperationImpl` 클래스에서는 position을 `parseInt`할때 try 문을 사용하지 않습니다.
=> CLEANUP: Remove redundant and inconsistent line in OperationImpl

.github/workflows/ci.yml, pom.xml
https://github.com/jam2in/arcus-works/issues/523
위 이슈와 오프라인에서 논의한 대로, JDK 8로 업그레이드 하면서 업데이트 가능한 라이브러리 버전도 업데이트 합니다.
단, 라이브러리의 인터페이스가 변경되지 않는 선에서만 업데이트를 합니다.
메이븐 플러그인을 제외한 모든 버전은 변수로 관리하도록 변경했고, `maven-dependency-plugin`의 버전을 명시하지 않았을 때 컴파일이 잘 되지 않는 현상이 있어 버전을 명시했습니다.
https://github.com/qos-ch/slf4j/blob/v_2.0.12/.github/workflows/main.yml
다른 오픈 소스 프로젝트를 봤을 때 여러 JDK 버전에서 CI를 수행하고 있음을 확인했습니다.
JDK 8로 업그레이드 한 이후로는 최소 JDK 8에서는 호환이 되어야 할 것으로 보아 LTS 버전인 8, 11, 17에서 테스트 코드를 수행하도록 했습니다.
11은 빼도 될 것 같지만 기존에 사용하던 버전이 11이라서 우선 남겼습니다.
OS도 여러 OS를 선택할 수 있지만 기존에 사용하던 우분투 20.04만 사용합니다.
=> INTERNAL: Upgrade the JDK and dependencies, except for those whose interfaces have changed.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/CacheManager.java, src/test/manual/net/spy/memcached/ArcusClientCreateTest.java, src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java
https://github.com/jam2in/arcus-works/issues/344,
https://github.com/jam2in/arcus-works/issues/490
ArcusClientPool의 PoolIndex와 ArcusClient의 ClientIndex는 각각 서로 다른 counter로 관리합니다.
`ArcusClient(1-4)` ->`ArcusClient-1(1-4)`와 같은 네이밍으로 변경
생성된 ArcusClientPool 중에서 첫번째 풀이고, 4개의 사이즈 중 1번째 클라이언트 인스턴스임을 의미
- 기존 : <사용자가 설정한 String 네임> 또는 "ArcusClient"로 표현됨
- 사용자가 name을 생성자의 인자로 줄 경우 : client-index가 적용되지 않도록 구현했습니다.
- 호출되는 생성자 : `public ArcusClient(ConnectionFactory cf, String name, List<InetSocketAddress> addrs)`
- default 설정된 name(=ArcusClient) 사용 시
- 호출되는 생성자 : `public ArcusClient(ConnectionFactory cf, List<InetSocketAddress> addrs)`
- ArucsClient-2 -> "ArucsClient"는 디폴트 네임이고, ArcusClient객체만 사용하는 2번째 인스턴스라는 의미
=> FEAT: Change the way ArcusClient is named.

src/main/java/net/spy/memcached/DefaultConnectionFactory.java
- https://github.com/jam2in/arcus-works/issues/570
- shouldOptimize의 기본값을 항상 false로 고정합니다.
=> FIX: Set default value of shouldOptimize to false.

.github/workflows/ci.yml, src/main/java/net/spy/memcached/ArcusClient.java, src/test/manual/net/spy/memcached/ArcusClientCreateTest.java
https://github.com/naver/arcus-java-client/pull/738
- 위 PR에서 반영되지 않았던 CI 테스트 설정을 수정했습니다.
- 테스트 코드 통과를 위해 ArcusClient의 기본 네이밍 방식에 있던 버그를 수정했습니다.
- ArcusClient 객체가 여러번 생성되었어도 테스트 코드가 통과하도록 정확한 CLIENT_ID 값이 아닌 정규식을 사용하도록 했습니다.
=> TEST: Add ArcusClient naming test to CI.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java
https://github.com/jam2in/arcus-works/issues/487
1. Security.getProperty(...) -> "networkaddress.cache.ttl" 프로퍼티 사용
2. System.getProperty(...) -> "sun.net.inetaddr.ttl" 프로퍼티 사용
3. `CacheManger`객체 사용 여부 확인
- 가져온 DnsCacheTtl 값이 0 < ttl or ttl > 300 면 invalid 판정
default 값을 true로 설정해서 ArcusClient 인스턴스가 생성될 때매다
기본적으로 검증하도록 구현했습니다.
ArcusClientPool을 사용하더라도 getInstance를 통해 
본 PR에서 변경된 ArcusClient 생성자를 호출합니다.
=> FEAT: Add check DNS cache ttl method.

src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/jam2in/arcus-works/issues/490
기존에 아래와 같은 포맷으로 수집되던 메트릭입니다.
```
net_spy_memcached_StatisticsHandler_747327855_reconnectCount_127.0.0.1:11212_ 0.0
```
이를 아래와 같이 변경하는 PR입니다.
```
net_spy_memcached_StatisticsHandler_reconnectCount_127.0.0.1:11212{name="ArcusClient-1(1-1) for test"}_ 0.0
```
일반화 시키면 아래와 같이 구성됩니다.
```
net_spy_memcached_StatisticsHandler_<수집메트릭>_<hostPort정보>{name=<ArcusClient 생성시 사용되는 name>}_ <값>
```
이슈의 코멘트도 참고부탁드립니다.
https://github.com/jam2in/arcus-works/issues/490#issuecomment-2164178885
=> FEAT: Change ArcusClient mbean name more readable.

src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/VersionOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/159
- if-else 문 마지막에서 `transitionState(OperationState.COMPLETE);`를 한번만 호출하도록 수정합니다.
- `CollectionCountOperationImpl`
- `CollectionExistOperationImpl` 클래스의 `handleLine()` 메서드에서,
`matchStatus()` 메서드를 호출할 때 `NOT_FOUND` 인자가 두 번 사용되는 부분을 한 번만 사용하도록 수정합니다.
- `matchStatus()` 메서드를 호출할 때, 인자가 많아 여러 줄로 작성된 경우 `OperationStatus` 객체를 생성하도록 합니다.
```java
getCallback().receivedStatus(
matchStatus(line, EXIST, NOT_EXIST, NOT_FOUND, NOT_FOUND,
TYPE_MISMATCH, UNREADABLE));
```
```java
OperationStatus status = matchStatus(line, EXIST, NOT_EXIST,
NOT_FOUND, TYPE_MISMATCH, UNREADABLE);
getCallback().receivedStatus(status);
```
=> REFACTOR: Reformat OperationStatus initialization in OperationImpl

src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/jam2in/arcus-works/issues/572
ArcusClient 내의 private으로 설정된 dead 필드의 경우
shutdown() 호출되면 true로 변경된다.
하지만 ArcusClient 클래스 내에서는 어떠한 로직에서 사용되지 않고,
getter가 없어 다른 클래스에서의 접근도 불가하다.
또한 테스트 코드에서 리플렉션을 통해 사용되지도 않는다.
그래서 사용되지 않는 필드을 제거한다.
=> INTERNAL: Remove unused boolean field dead in ArcusClient.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/collection/BTreeGetBulk.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGet.java, src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java, src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java, src/main/java/net/spy/memcached/ops/BTreeGetBulkOperation.java, src/main/java/net/spy/memcached/ops/BTreeSortMergeGetOperation.java, src/main/java/net/spy/memcached/ops/BTreeSortMergeGetOperationOld.java, src/main/java/net/spy/memcached/ops/MultiBTreeGetBulkOperationCallback.java, src/main/java/net/spy/memcached/ops/MultiBTreeSortMergeGetOperationCallback.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- https://github.com/naver/arcus-java-client/issues/521
- btree에서만 사용되는 메서드/필드의 경우 subkey라는 용어 대신 bkey라는 용어를 사용하도록 합니다.
- btree외에 list, set, map에서 함께 사용되는 메서드/필드의 경우 변경하지 않았습니다.
- BinaryOperationFactory에서 사용되지 않는 collectionInsert 메서드를 제거했습니다.
- CollectionGet 추상 클래스의 경우 subkey 필드가 존재하고, 이를 ListGet, MapGet, BTreeGet, BTreeFindPositionWithGet 등 상속클래스에서 사용합니다. 여기서 BTreeGet, BTreeFindPositionWithGet 내부적으로 bkey라는 용어를 사용할 수 없습니다. 이러한 구조는 이슈를 생성해 다른 PR로 개선하도록 하겠습니다.
=> CLEANUP: use bkey instead of subkey when it only related to btree

src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
- https://github.com/naver/arcus-java-client/pull/769#discussion_r1663601360
- getReadonlyCopy() 메소드에서 Lock을 잡는 시점이 올바르지 않은 점을 수정합니다.
- 기존 구현에서 ketamaNodes와 ketamaGroups를 미리 복제해두었는데, 이렇게 하면 TreeMap 객체를 2회 순회하기 때문에 1회만 순회하도록 수정합니다.
=> FIX: Make sure to create readonly copy of locator that has same shape with original one.

src/main/java/net/spy/memcached/ArcusClient.java, src/test/manual/net/spy/memcached/ArcusClientConnectTest.java, src/test/manual/net/spy/memcached/ArcusClientNotExistsServiceCodeTest.java, src/test/manual/net/spy/memcached/ArcusClientPoolReconnectTest.java, src/test/manual/net/spy/memcached/ArcusClientPoolShutdownTest.java, src/test/manual/net/spy/memcached/ArcusClientReconnectTest.java, src/test/manual/net/spy/memcached/ArcusClientShutdownTest.java, src/test/manual/net/spy/memcached/collection/BaseIntegrationTest.java
- https://github.com/jam2in/arcus-works/issues/569 논의 중 ConnectionFactoryBuilder 생략한 팩토리 메서드 제공의 필요성을 찾게 되어 추가합니다.
- ARCUS_CLOUD_ADDR -> ARCUS_ADMIN_ADDR 로 용어를 변경했는데, 위 이슈로 인해 추후 제거될 예정이라면 그대로 두겠습니다.
- 기존 테스트 코드에서 ConnectionFactoryBuilder를 수정하지 않고 그대로 사용하는 경우 새로 생성한 팩토리 메서드를 사용하도록 했습니다.
=> INTERNAL: add factory methods without ConnectionFactoryBuilder for ArcusClient/ArcusClientPool

src/main/java/net/spy/memcached/OperationTimeoutException.java, src/main/java/net/spy/memcached/TimedOutMessageFactory.java, src/main/java/net/spy/memcached/internal/BroadcastFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/CollectionGetFuture.java, src/main/java/net/spy/memcached/internal/GetFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheBulkGetFuture.java
- 하나의 TimeUnit 타입을 인자로 받는 경우 units 대신 unit 이라는 변수명을 사용하도록 합니다.
=> CLEANUP: rename units to unit

src/main/java/net/spy/memcached/ArcusClientPool.java
- 
- 외부에서는 Pool 내에 있는 개별 ArcusClient에 접근하지 못하도록 합니다.
=> INTERNAL: Change the ArcusClient getter methods in ArcusClientPool to non-public.

src/main/java/net/spy/memcached/ArcusClient.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/manual/net/spy/memcached/ArcusClientConnectTest.java, src/test/manual/net/spy/memcached/ArcusClientFrontCacheTest.java, src/test/manual/net/spy/memcached/ArcusClientNotExistsServiceCodeTest.java, src/test/manual/net/spy/memcached/ArcusClientPoolCreateTest.java, src/test/manual/net/spy/memcached/ArcusClientPoolReconnectTest.java, src/test/manual/net/spy/memcached/ArcusClientPoolShutdownTest.java, src/test/manual/net/spy/memcached/ArcusClientReconnectTest.java, src/test/manual/net/spy/memcached/ArcusClientShutdownTest.java, src/test/manual/net/spy/memcached/collection/BaseIntegrationTest.java
- https://github.com/jam2in/arcus-works/issues/569
- zk hostports를 입력받지 않는 정적 팩토리 메서드를 deprecate 시킵니다.
- BaseIntegrationTest 의 정적 필드를 사용하려다보니 네이밍이 조금 안익숙해서 ZK_HOST -> ZK_ADDRESS, ZK_SERVICE_ID -> ZK_SERVICE_CODE로 변경하였습니다.
=> INTERNAL: deprecate static factory method of ArcusClient without zk address

src/main/java/net/spy/memcached/OperationTimeoutException.java, src/main/java/net/spy/memcached/TimedOutMessageFactory.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/test/java/net/spy/memcached/internal/CheckedOperationTimeoutExceptionTest.java
- https://github.com/jam2in/arcus-works/issues/586
- OperationTimeout, CheckedOperationTimeout 클래스의 생성자 중 사용하지 않는 생성자를 제거합니다.
- 생성자를 제거하면서 필요한 변경도 함께 반영합니다.
=> INTERNAL: Remove unused TimeoutException constructors.

src/main/java/net/spy/memcached/ArcusClient.java
- https://github.com/jam2in/arcus-works/issues/425
- API의 반환 타입을 논의하면서 코드가 보기 불편하고 비일관적인 부분이 있어 이를 리팩토링하기로 했습니다.
- 현재 연산 실패가 발생하면  대부분 null을 반환하고, not found element / out of range로 인해 실패하는 경우에만 empty collection을 반환합니다. 따라서 switch-case 문을 제거해도 충분하다고 판단했습니다.
- default 문에서 "Unhandled state" 디버그 로그를 남길 필요가 없습니다. 이미 cstatus 로 응답을 변환할 때 "Unhandled state"  워닝 로그를 남기기 때문에, 디버그 로그는 단지 연산이 실패함만을 남기면 충분합니다.
=> CLEANUP: remove switch-case in receivedStatus

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/TimedOutMessageFactory.java, src/main/java/net/spy/memcached/internal/BroadcastFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/test/java/net/spy/memcached/ArcusTimeoutMessageTest.java
- 
- 오타를 수정합니다.
- https://en.dict.naver.com/#/entry/enko/0e7f7abc1e2b476ebccaeec2bc7ea920
=> CLEANUP: Fix typo, `timedout` to `timedOut`.

src/main/java/net/spy/memcached/MemcachedClient.java
기존 api들의 구현과 동일하게
Operation 생성하고 나서 addOp() 하는 형태로 변경하였습니다.
다른 api들을 살펴본 결과 이러한 형태는 mutate 연산만 가지고 있습니다.
=> INTERNAL: Change addOp logic in mutate api.

src/main/java/net/spy/memcached/TimedOutMessageFactory.java, src/main/java/net/spy/memcached/internal/BroadcastFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/OperationFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/test/java/net/spy/memcached/ArcusTimeoutMessageTest.java, src/test/java/net/spy/memcached/internal/CheckedOperationTimeoutExceptionTest.java
- https://github.com/jam2in/arcus-works/issues/573
- CountDownLatch.await() 수행 전의 시점을 기록한 뒤, Timeout 메세지를 생성할 때 현재 시점과의 차이를 계산합니다.
- CountDownLatch.await() 수행 직후의 시점을 기록하지 않은 이유는 다음과 같습니다.
- CPU가 충분할 경우 : CountDownLatch.await() 수행 직후의 시점과 Timeout 메세지를 생성할 때의 시점에 큰 차이가 없음
- CPU가 부족할 경우 : Timeout 메세지를 생성할 때의 시점을 선택해야 CPU 부족 상태를 더욱 확실하게 인지 가능
=> INTERNAL: Add actual elapsed duration to timeout exception message.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/collection/MapUpsert.java, src/main/java/net/spy/memcached/ops/APIType.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java, src/test/manual/net/spy/memcached/collection/map/MopUpsertTest.java
- https://github.com/jam2in/arcus-works/issues/579
- mop upsert API를 추가합니다. develop 버전 memcached 가 릴리즈되고 난 후에 CI가 통과할 수 있습니다.
=> INTERNAL: add mop upsert API

src/test/java/net/spy/memcached/ProtocolBaseCase.java
- testSyncGetTimeouts() 메소드에서는 타임아웃을 의도적으로 일으키기 위해 기본 Timeout이 1 밀리초인 MemcachedClient를 사용한다.
- 데이터를 저장하기 위해 set 연산을 수행할 때는 타임아웃을 의도하지 않았음에도 1 밀리초만 기다린다.
- 타임아웃을 의도하지 않는 set 연산 수행 시에는 1초를 기다립니다.
=> TEST: Wait for 1 second when store value in testSyncGetTimeouts().

src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
- AssertionError는 `assert`문에 의한 실패도 잡고 fail() 메소드에 의한 실패도 잡는데, 잡아놓은 실패가 무엇인지 확인하지 않고 있다.
- fail() 메소드에 진입하지 않았음을 검증합니다.
=> TEST: Fix `java.net.spy.memcached.protocol.ascii.BaseOpTest` to ensure it tests correctly.

src/main/java/net/spy/memcached/ArcusClientPool.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedClientIF.java, src/test/manual/net/spy/memcached/test/MemcachedThreadBench.java, src/test/manual/net/spy/memcached/test/ObserverToy.java
- https://github.com/jam2in/arcus-works/issues/585
- waitForQueues 메서드를 private으로 변경합니다.
- MemcachedThreadBench 에서 사용되던 waitForQueues는 MemcachedClient#set 의 결과를 받은 후 다시 요청을 보내므로 필요 없어 제거합니다.
- ObserverToy에서 사용되던 waitForQueues는 asyncGet으로 대체합니다.
=> INTERNAL: make waitForQueues method into private

src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java
- https://github.com/jam2in/arcus-works/issues/335 의 일환으로 코드 정리 합니다.
- 용어 변경
- unserialize -> deserialize
- tc_iter -> tcIter
- tc_map -> tcMap
-  동기 방식 메서드 제공 시 future.get 하여 예외처리하는 코드의 중복을 getFromFuture 메서드로 분리
- addKeyToMap 메서드에서 Map.computeIfAbsent 사용하도록 변경
- run 메서드에서 예외 처리 단순화 (CancelledKeyException, ClosedSelectorException은 IllegalStateException의 하위 타입이므로 별도로 체크하지 않아도됨)
=> CLEANUP: tidy MemcachedClient codes

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/test/java/net/spy/memcached/ProtocolBaseCase.java
- https://github.com/naver/arcus-java-client/pull/800#discussion_r1734170061
> addKeyToMap() 메소드를 호출하지 않고,
> 호출 쪽에서 해당 로직을 직접 가지는 것이 좋을 것 같은 데,
> 확인하고 동의한다면 PR 보내 주세요.
- asyncGetBulk, asyncGetsBulk에서 노드에 따라 키를 분배할 때 groupingKeys 메서드를 사용하도록 변경합니다.
- 이를 통해 일관적인 내부 동작을 가질 수 있습니다.
- addKeyToMap, getWholeChunkSize 메서드는 제거하였습니다.
=> INTERNAL: use groupingKeys in asyncGet(s)Bulk

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/BroadcastFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java
- https://github.com/jam2in/arcus-works/issues/408
- future에서 Operation 목록들을 담기 위해 ConcurrentLinkedQueue으로 둘 필요가 없으므로 ArrayList로 변경합니다.
- 참고로 기존에 spymemcached에서 여러 Operation을 담는 BulkGetFuture에서 Arraylist를 사용하였습니다.
=> INTERNAL: use Arraylist instead of ConcurrentLinkedQueue in future

docs/user_guide/02-arcus-java-client.md, src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java, src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java, src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java, src/test/java/net/spy/memcached/transcoders/BaseSerializingTranscoderTest.java
- https://github.com/jam2in/arcus-works/issues/604
- ClassLoaderObjectInputStream 내부 클래스를 추가하여 사용자가 Transcoder 생성 시 클래스로더를 입력할 경우 이를 사용하고, 만약 입력하지 않았다면 기본 클래스로더를 사용하도록 변경합니다.
=> INTERNAL: use custom classloader in transcoder when deserializing

src/main/java/net/spy/memcached/internal/BulkFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/plugin/FrontCacheBulkGetFuture.java
- 
- getSome()에서 Error, Cancel이 발생하더라도 조회가 완료된 결과를 리턴하도록 변경했습니다.
- InterruptException이 발생한 경우에는 그대로 반환합니다.
=> INTERNAL: return partial result if error or cancel occurred in getSome method of BulkGetFuture

src/main/java/net/spy/memcached/ExceptionMessageFactory.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/main/java/net/spy/memcached/internal/CompositeException.java, src/test/java/net/spy/memcached/CancellationBaseCase.java, src/test/java/net/spy/memcached/ProtocolBaseCase.java
- https://github.com/naver/arcus-java-client/issues/27
- get()에서 다수 캐시 노드에서 발생한 예외들을 CompositeException으로 묶어 사용자가 list를 통해 모든 예외 사항을 조회할 수 있도록 변경했습니다.
- +) 참고로 FrontCacheBulkGetFuture의 get()에서는 기존에 모든 예외를 던지고 있고, getSome()에서는 에러가 발생해도 일부 결과를 가져와 로컬 캐시에 넣고, 로컬 캐시 결과와 병합하므로 기존대로 동작해도 문제가 없습니다.
=> INTERNAL: return CompositeException from get method in BulkGetFuture

src/main/java/net/spy/memcached/internal/BroadcastFuture.java, src/main/java/net/spy/memcached/internal/BulkGetFuture.java, src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/internal/CheckedOperationTimeoutException.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/main/java/net/spy/memcached/internal/SMGetFuture.java, src/test/manual/net/spy/memcached/emptycollection/VariousTypeTest.java
- jdk 21 lint 경고를 해결하였습니다. 
위는 직렬화 가능 여부가 명확하지 않아 발생하는 경고 입니다.
`CheckedOperationTimeoutException` 에서는 해당 필드를 직렬화가 가능한 명확한 타입인 ArrayList 로 변경하였습니다. 이에 명확한 타입에 맞추고 사용자가 입력한 순서대로 메세지를 생성하기위해 다른 클래스의 타입 또한 ArrayList 로 통일 하였습니다. 
https://github.com/naver/arcus-java-client/pull/807#issuecomment-2362586772
`VariousTypeTest` 에서는 직렬화 가능한 명확한 타입인 ArrayList 를 활용하였습니다.
=> INTERNAL: Fix transient field

src/main/java/net/spy/memcached/ops/OperationException.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/test/java/net/spy/memcached/protocol/ascii/OperationExceptionTest.java, src/test/manual/net/spy/memcached/collection/btree/BopMutateTest.java
- 
- OperationException에 Operation을 담당하던 노드의 정보를 담도록 수정합니다.
=> INTERNAL: add node information into OperationException

pom.xml, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java, src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
- https://github.com/jam2in/arcus-works/issues/600
- ehcache version 3 로 업그레이드
- cacheManger 변경
ehcache2 에서는 cacheManger 를 싱글톤으로 관리하며 전체 어플리케이션에서 하나의 cacheManger 만을 사용합니다. 하지만, ehcache3 의 경우에는 여러 cacheManger 를 둘 수 있습니다. 따라서 이번 버전업 에서는 코드 자체에 싱글톤 패턴을 적용시켜 기존과 동일하게 cacheManger 를 어플리케이션에서 하나만 가지도록 하였습니다.
- Element 객체의 삭제
ehcahce2 의 Element 객체가 ehcache3 에서는 삭제되었습니다. 삭제된 후에 Cache 에 직접 저장하는 형태로 바뀌어 이를 수정하였습니다.
- CacheConfiguration 변경
기존 설정이 사라지거나 기본 디폴트 설정으로 변경되었습니다.
`.copyOnRead(copyOnRead), .copyOnWrite(copyOnWrite)` : 이 설정은 사라지고 원래 false 로 설정을 하였는데 이것이 기본동작이 되었습니다.
`diskExpiryThreadIntervalSeconds` : 해당 설정은 사라졌습니다.
`LRU policy` : 해당 설정은 디폴트 값입니다.
이 외 설정은 인터페이스가 바뀌어 그에 따라 수정하였습니다.
- 기존의 ehcahe2 에서는 cacheManger가 하나로 이를 싱글톤으로 관리하였는데 이를 생성자 마다 하나씩 가지도록 변경했습니다.
- TTL 만을 설정하도록 변경했습니다.
=> INTERNAL: Upgrade ehcache version

src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/test/java/net/spy/memcached/MemcachedConnectionTest.java
https://github.com/jam2in/arcus-works/issues/379
- 위 이슈 기반의 PR입니다.
기존에는 String 타입으로 cacheListChange 및 alterListChange를 관리한다.
이러한 경우에는 ArcusClientPool 내에 있는 모든 ArcusClient들이 
`String -> List<InetSocketAddress>`로의 변환을 반복한다.
이러한 반복을 제거하기 위해 znode로부터 `List<String>`을 
받았을 때 `List<InetSocketAddrress>`로 바로 변환하도록 변경한다.
=> REFACTOR: Change cachelist and alterList parsing logic.

src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/ConcatenationOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MGetsOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/OptimizedSetImpl.java
- jdk 21 lint 의 `possible 'this' escape before subclass is fully initialized` 를 일부 해결하였습니다.
위는 아직 final 클래스가 아닌 클래스에 대하여 초기화가 끝나지 않았을때, 다른 클래스에서 해당 클래스를 참조하는 경우에 발생합니다.
따라서 경고를 해결하기 위해서는
1. final class 로 선언
2. 생성자가 끝난 후 다른 함수에서 경고가 발생하는 (this 를 외부로 넘기는) 메서드를 호출합니다.
3. 외부 클래스에 this 를 넘기지 않아도 되는 경우 생성자에서 해당 역할을 합니다.
해당 pr 에서는 2, 3번에 해당하는 방법으로 해결할 수 있는 코드를 수정하였습니다.
1. `ConnectionFactoryBuilder` 의 `frontCacheName` 은 필드 초기화 부분에서 this.hashCode() 를 호출하여 해당 경고가 발생하였습니다. 
2. `ConnectionFactoryBuilder` 를 제외한 자식 클래스의 생성자는 부모 클래스의 필드를 초기화 할때 부모 클래스의 메서드를 호출하여 초기화를 시키고 있습니다. 이에 생성자 안에서 외부 클래스로 this 를 넘기게 되어 경고가 발생하였습니다.
1. `frontCacheName` 은 `get` 을 통해 호출되어 `get` 메서드에 초기화 부분을 넣어 수정하였습니다.
2. 부모 클래스의 해당 필드의 접근자를 protected 로 변경하여 해당 필드를 자식 클래스의 생성자에서 초기화 …
=> INTERNAL: Resolved the jdk lint "this-escape" warning in the final class manner.

src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java, src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
- 
- FrontCacheMemcachedClient를 더 이상 사용하지 않게 된 경우, Ehcache3의 CacheManager 객체에 할당된 리소스를 즉시 해제합니다.
=> INTERNAL: Close Ehcache CacheManager when shutdown FrontCacheMemcachedClient.

src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- https://github.com/naver/arcus-java-client/pull/810#discussion_r1774846955
기존의 `setupForAuth()` 메서드는 `authLatch` 초기화 외에 `TCPMemcachedNodeImpl` 인스턴스의 버퍼와 큐등 필드들을 **초기화** 시키는 역할을 합니다. 
하지만, 생성자에서는 이미 초기화 된 형태이므로 `authLatch` 외의 필드를 초기화 하는 것은 불필요하여 **제거**하였습니다.
제거함에 따라 기존의 `getLogger().warn()` 호출로 발생하던 `this-escape` 경고 또한 피할 수 있습니다.
기존 코드의 `setupForAuth()` 에서는 `inputQ`, `readQ`, `writeQ` 와 버퍼들을 빈 상태로 초기화 하는 역할을 수행하는데, 생성자에서 호출하는 경우 이미 빈 상태이기 때문에 `authLatch` 만을 초기화 하여도 충분합니다.
=> INTERNAL: Divide  method for constructor

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/auth/AuthThread.java, src/main/java/net/spy/memcached/auth/AuthThreadMonitor.java, src/main/java/net/spy/memcached/compat/SyncThread.java
- final class 가 아닌 class 의 생성자에서 thread의 메서드 를 호출하여 `this-escape` warning 이 발생합니다. 따라서 이를 피하기 위해 생성자가 아닌 생성자를 호출하는 곳에서 thread 의 메서드를 따로 호출하도록 하였습니다.
https://www.baeldung.com/java-thread-constructor
https://stackoverflow.com/questions/5623285/why-not-to-start-a-thread-in-the-constructor-how-to-terminate
=> INTERNAL: Divide thread method from constructor

src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
- 
- final class 에 알맞지 않은 접근제어자 protected 를 private 으로 변경하였습니다.
=> CLEANUP: Protected visibility in final class

docs/user_guide/03-key-value-API.md, docs/user_guide/04-list-API.md, docs/user_guide/05-set-API.md, docs/user_guide/06-map-API.md, docs/user_guide/07-btree-API.md
- user_guide 한번에 -> 한 번에 띄어쓰기 수정
- 03-key-value-API.md 한번에 -> 한 번에 7개 수정
- 04-list-API.md 한번에 -> 한 번에 1개 수정
- 05-set-API.md 한번에 -> 한 번에 3개 수정
- 06-map-API.md 한번에 -> 한 번에 3개 수정
- 07-btree-API.md 한번에 -> 한 번에 1개 수정
- 참고 : https://www.goodwriter.or.kr/bbs/board.php?bo_table=s0301&wr_id=2933
=> DOCS: user_guide Typo spacing correction

src/main/java/net/spy/memcached/CacheManager.java
- https://github.com/jam2in/arcus-works/issues/568#issuecomment-2393092639
- 스레드가 시작된 후에 로그를 출력하도록 하였습니다.
=> INTERNAL: Move logger code

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java
- `ArcusClient`, `MemcachedClient` 에 `suppress-warning` 을 적용하였습니다.
`ArcusClient` 의 경우에는 위 처럼 메서드를 따로 호출해야 하는 경우 다른 필드들도 public 으로 접근제어를 변경해야합니다.
`MemcachedClient` 의 경우에는 상속을 하는 클래스가 많아서 이를 위와 같은 방식, 메서드를 떼어내는 방식으로 수정하게 되면 수정 사항이 많아집니다.
또한 `MemcachedClient` 는 현재 상속을 하고 있기 때문에 final class 를 적용할 수 없습니다.
`ArcusClient` 또한 상속 가능성이 있다고 말씀해 주셔서 모두 `suppress-warning` 을 적용하였습니다.
=> INTERNAL: Suppress-warning for `this-escape`

src/main/java/net/spy/memcached/ArcusReplNodeAddress.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/CacheMonitor.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/MemcachedReplicaGroupImpl.java, src/main/java/net/spy/memcached/MemcachedReplicaGroupROImpl.java, src/main/java/net/spy/memcached/MigrationMonitor.java
상속이 필요없는 클래스에 대해 final 클래스로 만듭니다.
`CacheMonitor`, `MigrationMonitor`, `MemcachedReplicationGroupImpl`, `CacheManager`, ArcusReplNodeAddress`,
`MemcachedNodeROImpl`, `MemcachedReplicaGroupImpl`, `MemcachedReplicaGroupROImpl` 클래스들을 final 로 변경합니다.
=> INTERNAL: Make final class which is not inherit

src/main/java/net/spy/memcached/collection/BTreeCount.java, src/main/java/net/spy/memcached/collection/BTreeCreate.java, src/main/java/net/spy/memcached/collection/BTreeDelete.java, src/main/java/net/spy/memcached/collection/BTreeFindPosition.java, src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java, src/main/java/net/spy/memcached/collection/BTreeGet.java, src/main/java/net/spy/memcached/collection/BTreeGetBulk.java, src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java, src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- 
- Collection 폴더 하위의 btree 관련 파일을 sonarLint 규칙에 맞추어 수정하였습니다
- 상수인 변수 (final, interface 의 필드) 들을 네이밍 컨벤션에 맞추어 대문자로 변경하였습니다.
- 필요없는 케스팅 문법을 삭제하였습니다. (문자열에 숫자를 이어 붙이면 묵시적 변환)
- 상위 클래스 필드의 이름과 같은 필드의 이름을 변경했습니다. `range` -> `posRange`
=> CLEANUP: Collection Btree

src/main/java/net/spy/memcached/ArcusClient.java, src/test/manual/net/spy/memcached/collection/btree/BopFindPositionWithGetTest.java
- https://github.com/jam2in/arcus-works/issues/425
- bop find position with get 에서 not found element인 경우 empty map 반환하도록 변경합니다.
=> INTERNAL: return empty map if response is NOT_FOUND_ELEMENT

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java, src/main/java/net/spy/memcached/MemcachedClient.java
https://github.com/jam2in/arcus-works/issues/624
- replication 사용하며 flush 연산 시, master 노드에만 연산 보내도록 변경
- Locator 내의 allGroups에 대해 IO 스레드가 write하고 여러 worker thread가 read하는 동시성 문제 방지를 위해 ConcurrentHashMap 적용
=> FIX: Send flush op to master node only.

src/main/java/net/spy/memcached/ExceptionMessageFactory.java, src/main/java/net/spy/memcached/internal/CompositeException.java, src/test/java/net/spy/memcached/compat/log/LoggingTest.java, src/test/java/net/spy/memcached/internal/CompositeExceptionTest.java
- https://github.com/naver/arcus-java-client/pull/839#discussion_r1846040585
- CompositeException 객체의 printStackTrace() 메서드를 통해 예외에 대한 스택을 확인할 때, 아래와 같이 각각의 예외들에 대한 stacktrace가 찍히도록 합니다.
=> INTERNAL: stacktrace all exceptions

src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
- https://github.com/jam2in/arcus-works/issues/639
- BaseOperationImpl의 callback 필드를 private으로 변경합니다.
=> INTERNAL: make callback field in BaseOperationImpl private

src/test/manual/net/spy/memcached/bulkoperation/BopInsertBulkTest.java, src/test/manual/net/spy/memcached/bulkoperation/BopPipeUpdateTest.java, src/test/manual/net/spy/memcached/collection/set/SopBulkAPITest.java
- https://github.com/jam2in/arcus-works/issues/640
- 파이프 operation들에 대해서 파이프 연산이 아닌 경우에 동작을 테스트 하였습니다.
`CollectionBulkInsertOperationImpl`은 `asyncBopInsertBulk`,
`CollectionPipedInsertOperationImpl`은 `asyncSopPipedInsertBulk`,
`CollectionPipedUpdateOperationImpl `은 `asyncBopPipedUpdateBulk`
각각 위에 연산에 대하여 위 연산들을 실행하는 테스트 파일에 테스트를 추가한다.
시나리오는 아이템을 하나씩만 주어 파이프와 벌크 연산의 handleLine 에서 isNotPiped()를 테스트한다.
이때 연산이 성공하는 경우와 연산이 실패하는 경우를 모두 다룬다.
=> TEST: Feat not piped test

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedReplicaGroup.java, src/main/java/net/spy/memcached/MemcachedReplicaGroupImpl.java
https://github.com/jam2in/arcus-works/issues/650
삭제 시킨 메서드
- public void setMasterCandidate(MemcachedNode masterCandidate -> `this.masterCandidate = masterCandidate;`로 대체
- void setMasterCandidateByAddr(ArcusReplNodeAddress address) -> `setMasterCandidateByAddr(Addr인스턴스.getIPPort())` 호출로 대체
=> REFACTOR: setMasterCandidate in MemcachedReplicagroup.

src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/623
- final 클래스에 불필요하게 선언된 final 메서드 표시를 제거합니다.
- handleLine에서 SERVER_ERROR는 현재 읽을 수 없는 상태이므로 상태 체크에서 제거합니다.
=>  INTERNAL: tidy operation codes

src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/623
- Operation 클래스들의 initialize 메서드에서 디버깅목적으로 사용되는 replaceAll 메서드를 replace 메서드로 교체합니다.
- 이를 통해 로그에 `\r\n`이 정상적으로 보여지도록 합니다.
=>  CLEANUP: use replace method instead of replaceAll

src/test/manual/net/spy/memcached/MemcachedConnectionReplTest.java
- https://github.com/jam2in/arcus-works/issues/598
- https://github.com/jam2in/arcus-works/issues/620
- https://github.com/jam2in/arcus-works/issues/637
- 복제 관련 코드 리팩토링 진행 시 기존 로직과 달라진 경우를 로컬 개발 단계에서 바로 확인할 수 있도록 단위 테스트를 추가합니다.
=> TEST: Add unit tests for `MemcachedConnection.handleCacheNodesChange()` method in replication mode.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/test/java/net/spy/memcached/ArcusTimeoutTest.java, src/test/manual/net/spy/memcached/bulkoperation/SopInsertBulkMultipleValueTest.java, src/test/manual/net/spy/memcached/collection/list/LopBulkAPITest.java, src/test/manual/net/spy/memcached/collection/map/MopBulkAPITest.java, src/test/manual/net/spy/memcached/collection/set/SopBulkAPITest.java, src/test/manual/net/spy/memcached/collection/set/SopPipedExistTest.java
https://github.com/jam2in/arcus-works/issues/654#event-15614575064
getMaxPipedItemCount 메서드 제거
=> REFACTOR: remove unused getMaxPipeCount.

src/main/java/net/spy/memcached/MemcachedConnection.java
- https://github.com/jam2in/arcus-works/issues/637
- switchoverMemcachedReplGroup() 메소드의 첫 인자 타입을 `MemcachedNode`에서 `MemcachedReplicaGroup`으로 변경합니다.
=> CLEANUP: Refactored `MemcachedConnection.switchoverMemcachedReplGroup()` method.

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/ops/OperationState.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CASOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/DeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/FlushByPrefixOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/FlushOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/662
- switchover 용어 변경합니다.
- OperationState.MOVING -> OperationState.NEED_SWITCHOVER
- receivedMoveOperations -> prepareSwitchover
=> INTERNAL: rename switchover method and state

src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/jam2in/arcus-works/issues/656
reverse 변수 제거 후, 인자 값으로 불리언 처리
=> INTERNAL: remove reverse local variable.

src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/test/java/net/spy/memcached/OptimizeTest.java
- https://github.com/jam2in/arcus-works/issues/648
- `asyncGetBulk`의 연산의 키 제한 개수와 같게 200개의 제한을 두었습니다.
- 초기에 getOperation에서 key의 개수를 세어 limit을 넘지 않는 경우 limit을 넘지 않을때 까지 operation을 모아 get <keys>로 optimize 시킵니다.
- 과거 optimize는 getOperation이 두개 이상 연속되어야만 유효했습니다.
이를 하나만 있어도 되도록 변경했습니다.(optimized 를 사용하기 위해 get이 두개 이상 연속 되었는지 판단 할 필요 사라짐)
=> INTERNAL: Limit bulk get keys size

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedReplicaGroup.java
https://github.com/jam2in/arcus-works/issues/638
아래 코멘트 참고
- https://github.com/jam2in/arcus-works/issues/638#issuecomment-2565170046
=> FEAT: Change switch-over handling logic by using master candidate.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeGet.java
https://github.com/jam2in/arcus-works/issues/656
private 접근 제어인 asyncBopGet, asyncBopExtendedGet의
reverse 인자를 제거하고
이를 BopGet 인스턴스의 isReverse로 대체한다.
=> INTERNAL: Remove reverse arg in bopGet and bopExtendedGet

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeDelete.java, src/main/java/net/spy/memcached/collection/ListDelete.java, src/main/java/net/spy/memcached/collection/MapDelete.java, src/main/java/net/spy/memcached/collection/SetDelete.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolBTreeDeleteTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolListDeleteTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolMapDeleteTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolSetDeleteTest.java
- https://github.com/jam2in/arcus-works/issues/665
- delete command 객체 (ListDelete, SetDelete, ..) 에서 안쓰는 생성자를 제거하고 생성자 인자 순서를 변경합니다.
=> CLEANUP: remove useless constructor and change parameter order in delete command class

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeCount.java, src/main/java/net/spy/memcached/collection/BTreeGet.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java, src/test/manual/net/spy/memcached/emptycollection/ProtocolBTreeGetTest.java
- https://github.com/jam2in/arcus-works/issues/665
- btree command class에서 불필요한 생성자를 제거하고 parameter 순서를 조정합니다.
=> CLEANUP: remove useless constructor and change parameter order in btree command class

src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java, src/main/java/net/spy/memcached/protocol/ascii/GetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OptimizedGetImpl.java, src/test/java/net/spy/memcached/protocol/ascii/OptimizeOperationTest.java
- https://github.com/jam2in/arcus-works/issues/649
- optimize 시 캐시 서버의 mget 지원 여부에 따라 get or mget 명령을 선택할 수 있도록 수정합니다.
=> INTERNAL: choose get/mget when optimize get commands

src/main/java/net/spy/memcached/internal/BulkOperationFuture.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java, src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
- https://github.com/jam2in/arcus-works/issues/616
- 본 PR에서는 파이프 연산 요청에서 에러(CLIENT_ERROR, ERROR, SERVER_ERROR) 응답 시 `PIPE_ERROR`를 끝까지 읽도록 변경한다.
- 기존에는 에러 응답 시 즉시 예외를 생성해 던졌기 때문에 `PIPE_ERROR`를 읽지 않았다.
- 동기 파이프 연산 처리 시 에러로 인해 수행되지 않은 연산을 failedResult를 통해 알려야 하는데, 기존 형태에서는 에러 시 바로 예외를 던지므로, 에러 발생으로 인해 수행되지 않은 연산에 대해 callback.gotStatus()를 호출할 수 없다.
- 따라서 `PIPE_ERROR`를 읽도록 변경만 해두고, 수행되지 않은 연산에 대한 gotStatus() 호출은 #795 에 추가하도록 한다.
=> INTERNAL: read while PIPE_ERROR received in the pipe operation

src/main/java/net/spy/memcached/OperationFactory.java, src/main/java/net/spy/memcached/auth/AuthThread.java, src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java, src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java, src/main/java/net/spy/memcached/protocol/binary/SASLAuthOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/SASLBaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/SASLStepOperationImpl.java
- jam2in/arcus-works#672
1. Operation의 `initialize()`에서 `SaslClient`를 생성하는 대신,
AuthThread가 SaslClient를 생성하여 명령 인자로 전달하도록 합니다.
2. 각 연결에 대한 인증 과정에서 하나의 SaslClient 객체를 사용함으로써 multi-step auth mechanism에서 상태 정보를 유지할 수 있습니다.
=> INTERNAL: Handle SaslClient on AuthThread

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ops/CollectionBulkInsertOperation.java, src/main/java/net/spy/memcached/ops/CollectionPipedExistOperation.java, src/main/java/net/spy/memcached/ops/CollectionPipedInsertOperation.java, src/main/java/net/spy/memcached/ops/CollectionPipedUpdateOperation.java, src/main/java/net/spy/memcached/ops/MultiCollectionBulkInsertOperationCallback.java, src/main/java/net/spy/memcached/ops/PipedOperationCallback.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java, src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- https://github.com/naver/arcus-java-client/pull/872#discussion_r1924920050
- pipe 연산 callback을 PipedOperationCallback으로 통합합니다.
- bulk insert 연산의 callback에서 주어진 index에 해당하는 key를 찾을 수 있으므로 인터페이스 통합이 가능합니다.
- 콜백 객체의 gotStatus() 메서드 내부에서 status의 성공 여부를 판단해 처리하도록 수정했습니다.
- piped exist 연산의 경우 not my key로 인해 redirect될 수 있고 이 과정에서 일부 서버에 단일 연산이 보내지고 응답받을 수 있습니다. 하지만 단일 연산 처리 시 successAll를 고려하지 않고 있어 이를 고려하도록 수정했습니다.
=> INTERNAL: integrate piped operation callbacks

src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/PipeOperationImpl.java
- 앞으로 pipe operation implementation 변경 지점이 많아질 것을 고려하여 PipeOperationImpl 클래스를 추가하여 이를 각각의 클래스가 상속받도록 합니다.
- 또한, 이전에 pipe_error까지 읽는 로직을 CollectionPipedInsertOperationImpl에만 적용했었기 때문에, 하나의 추상 클래스를 상속받도록 하여 CollectionPipedUpdateOperationImpl, CollectionPipedExistOperationImpl, CollectionBulkInsertOperationImpl에도 적용하고자 합니다.
- handleLine, initialize 등의 메서드 중복과 static 필드 중복을 제거하였습니다.
- handleLine에서 각 연산(insert/exist/update/bulk insert)마다 다르게 처리해야 하는 부분은 추상 메서드로 빼 각 클래스에서 구현하도록 하였습니다.
- wasCancelled 메서드는 연산마다 다룰 CANCELLED 상태가 달라 각 클래스에서 구현하도록 하였습니다.
- getInsert/ getExist / getUpdate 메서드는 형변환이 필요하기 때문에 각 클래스에서 구현하도록 하였습니다.
=> INTERNAL: add PipeOperationImpl to reduce duplicate code

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/MemcachedReplicaGroup.java
캐시 서버로부터의 응답을 통해 master candidate를 설정하고 난 뒤,
zk로부터 비정상적인 switchover를 감지하는 경우에 대한 처리이다.
|상태|ROLE1|ROLE2|처리로직
|:----:|:-----:|:-----:|:-----:|
|초기상태|M|S|
|SwitchOver 응답 후 상태|M|S(masterCandidate)|
|정상 상태 (1st ZK 변경)|S|S|Invalid Group 처리
|정상 상태 (2nd ZK 변경)|S|M|switch-over 로직이 처리
|비정상1|X|M|Fail-Over 로직이 처리
|비정상2|M|X| **처리필요**
|비정상3|X|X|그룹 제거(기존 로직이 처리)
|상태|ROLE1|ROLE2|ROLE3|처리로직
|:----:|:-----:|:-----:|:-----:|:-----:|
|초기상태|M|S1|S2
|SwitchOver 응답 후 상태|M|S1(masterCandidate)|S2
|정상 상태 (1st ZK 변경)|S3|S1|S2|Invalid Group 처리
|정상 상태 (2nd ZK 변경)|S3|M|S2|switch-over 로직이 처리
|비정상1|S3|M|X| Switch-Over 로직이 처리
|비정상2|X|M|S2| Fail-Over 로직이 처리
|비정상3|S3|X|M| **처리필요**
|비정상4|X|M|X| Fail-Over 로직이 처리
|비정상5|X|X|M| Fail-Over 로직이 처리
|비정상6|M|X|X| **처리필요**
|비정상7|X|X|X|그룹 제거(기존 로직이 처리)
참고로 아래와 같은 케이스들은 zk 시퀀스 넘버에 의한 …
=> FIX: Handling abnormal swithover from zk.

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java, src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java, src/main/java/net/spy/memcached/collection/ListGet.java, src/main/java/net/spy/memcached/collection/MapDelete.java, src/main/java/net/spy/memcached/collection/MapGet.java
- https://github.com/jam2in/arcus-works/issues/666
- 명령 객체의 생성자에서 값을 검증하도록 하고 getter를 제거했습니다.
- 객체 내부에서만 사용되는 public 메서드를 private 메서드로 변경했습니다.
=> CLEANUP: remove or modify methods in command classes

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/MemcachedClient.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/RedirectHandler.java, src/test/java/net/spy/memcached/protocol/ascii/OperationExceptionTest.java
https://github.com/jam2in/arcus-works/issues/686#issuecomment-2646933197
위 이슈에서 파생됨
기존 로직에서는 ReplicaPick.Slave 또는 ReplicaPick.RR 시,
Operation의 타입에 상관없이 선택된 노드에 연산을 처리한다.
즉, write 연산인 경우에도 Slave 노드에 연산이 처리될 수 있다.
대략 아래의 흐름에서 문제가 발생한다.
- Repl 사용하는 응용에서 api 호출로 인해 Operation 객체 생성
- addOp 호출
- addOperation 호출 
- 내부에서 cache key에 해당하는 node 찾기 위한 findNodeByKey 호출
- findNodeByKey에서 ReplicatkPick.Slave 설정 시 Slave 노드에 해당하는 node 리턴
- 해당 node에 op 객체를 inputQ에 삽입
- 해당 op가 write 연산일 경우 slave 노드에 write 연산을 삽입하는 문제가 발생
1. addOperation 호출 시, 해당 op의 write / read 여부를 확인 후 ReplicaPick을 찾도록 변경
2. groupingKeys의 경우, op 객체가 생성되기 전에 수행되는 로직이다. 그래서 이를 호출하는 api의 타입을 직접 보고 read / write 여부를 인자로 넘겨서 확인 가능하도록 변경
=> FIX: Input the operation to none master node.

src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java, src/test/manual/net/spy/memcached/collection/transcoder/CollectionTranscoderTest.java
- https://github.com/jam2in/arcus-works/issues/451
- CollectionTranscoder에 optimize 옵션을 추가하여, 기본적으로는 기존대로 동작하도록 하고 disableOptimize를 사용하여 Transcoder를 생성해야만 위 이슈를 해결할 수 있도록 하였습니다.
- 빌더 패턴을 추가하여 생성자 종류가 많아지는 것을 줄였습니다.
- 문서의 경우 현재 ConnectionFactoryBuilder 인자들에 대한 설명이 담긴 문서가 없어 해당 문서 추가할 때 이에 대한 설명도 추가하도록 하겠습니다.
=> INTERNAL: add option to disable optimization in CollectionTranscoder

src/main/java/net/spy/memcached/MemcachedConnection.java
https://github.com/jam2in/arcus-works/issues/686 
MoveOperationTask 생성자에서 사용되는 cancelNonIdempotent를 제거한다.
이후 MoveOperationTask 내부에서는 true 값을 통해
무조건 non-idempotent 연산은 cancel 하도록 한다.
기존에 해당 값이 false로 설정된 로직들은 아래와 같다.
- slave -> master 로의 op 이동하는 경우
- zk로부터 swtichover 이벤트 먼저 감지하고 non-idempontent 연산이 없는 경우
그 외는 아래 코멘트에 적힌 버그입니다.
https://github.com/jam2in/arcus-works/issues/686#issuecomment-2646920539
=> INTERNAL: Remove cancelNoneIdempotent arg in MoveOperationTask

src/main/java/net/spy/memcached/MemcachedNode.java, src/main/java/net/spy/memcached/MemcachedNodeROImpl.java, src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java, src/test/java/net/spy/memcached/MockMemcachedNode.java
- https://github.com/jam2in/arcus-works/issues/678
- TCPMemcachedNodeImpl 클래스를 정리했습니다.
- transitionWriteItem 메서드를 제거합니다.
- getBuffer 메서드를 한번만 호출하도록 합니다.
=> CLEANUP: tidy TCPMemcachedNodeImpl

src/main/java/net/spy/memcached/ArcusClient.java, src/test/manual/net/spy/memcached/bulkoperation/PipeInsertTest.java
- https://github.com/naver/arcus-java-client/pull/795/files#r1953855345
- 기존에 500개 이상의 원소를 파이프를 이용해 리스트에 추가하고자 할 때 인덱스를 똑같은 값으로 주어 사용자가 입력한 원소 순서대로 리스트에 저장하지 않는 문제가 있었습니다.
- 원소 500개마다 생성하는 ListPipedInsert 객체의 index를 증가시키며 할당하여 이전 ListPipedInsert 객체 원소 뒤에 추가될 수 있도록 하였습니다.
=> FIX: use proper index when lop piped insert

checkstyle.xml, pom.xml
- 
- 인텔리제이 IDE에서 체크스타일 플러그인을 지원하는데, 지원하는 가장 오래된 버전이 9.1입니다.
- 하지만 현재 체크스타일은 8.42 이전 버전에서만 사용 가능합니다.
- 따라서 8.42 이상 버전에서 모두 사용가능하도록 수정합니다.
- 현재 maven 테스트 진행 시 사용하는 의존성의 경우 기본 checkstyle 버전이 8.29이므로 9.3 버전을 기본으로 사용하도록 의존성 버전을 높였습니다.
- http://maven.apache.org/plugins/maven-checkstyle-plugin/history.html
=> FIX: Support for checkstyle versions 8.42 and higher

src/main/java/net/spy/memcached/ArcusReplNodeAddress.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/MemcachedConnection.java
https://github.com/jam2in/arcus-works/issues/620#issuecomment-2505369614
기존 로직의 경우 findChangedGroups을 통해
해시링의 형상과 zk로부터의 형상을 먼저 비교합니다.
그 후에 변경이 있는 Group에 대해서만 루프를 돌며 update를 수행합니다.
변경된 로직은 해시링의 형상(old)을 순회를 돌며
해당 해시링 기준, zk로부터의 형상(new)을 곧바로 비교하면서
update를 수행합니다.
리뷰를 위해 이슈 관련 히스토리도 아래에 정리합니다.
1. findChangedGroups가 알고보니, M / S 정보를 비교해서 변경을 감지하는것을 발견
2. 1번 문제는 특정 상황에서 switchover가 원복하는 문제가 그대로 남아 있음
3. 2번 상황 해결을 위해 masterCandidate를 사용하는 방안 사용
4. 3번 상황의 엣지 케이스 발견 및 해결
결론적으로 기존의 findChangedGroups가 가진 문제는 해결된 상태에서의 PR인점을 참고해주세요.
추가적으로 아래 코멘트 사항에서 언급된 경우도 처리합니다.
https://github.com/naver/arcus-java-client/pull/874#issuecomment-2673876201
기존에는 for 루프 내에서 group 별로 처리하는 경우를
for 루프 앞단에서 일괄적으로 이전 delayed switchover를 처리하도록 변경했습니다.
=> INTERNAL: Refactoring updateReplConnections.

src/main/java/net/spy/memcached/MemcachedConnection.java, src/main/java/net/spy/memcached/RedirectHandler.java, src/main/java/net/spy/memcached/ops/APIType.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
enum 타입의 필드가 불변으로 바뀌지 않아서
부정확한 read / write OperatoinType이 발생하는 문제 
(아래 코멘트 참고)
https://github.com/naver/arcus-java-client/pull/879#issuecomment-2677460078
다양한 구현들을 생각해보았는데, 앞서 언급된 의견들 전부 고려해서
현재 PR이 제일 깔끔하다고 생각들었습니다.
XopGet의 경우 기본적으로는 read opType을 가지고,
op 생성자 내에서 delete 옵션이 true인 경우
setter를 통해 op 타입을 write로 변경합니다.
기존 findNodeByKey의 경우는 APIType을 인자로 받고 해당 인자내의 OpType을 사용했었는데요,
이 대신 Op 자체를 넘겨서 setter를 통해 변경된 Op를 사용하도록 변경했습니다.
groupingKeys와 같은 Op 인스턴스가 생기기전에 노드를 찾아야 하는 경우에만
기존의 APIType을 인자로 받는 findNodeByKey를 호출하도록 변경했습니다.
=> FIX: Invalid opType in XopGet operation instance.

src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java, src/main/java/net/spy/memcached/protocol/binary/OptimizedSetImpl.java, src/test/java/net/spy/memcached/internal/CheckedOperationTimeoutExceptionTest.java
- https://github.com/naver/arcus-java-client/pull/885#discussion_r2002328855 
위 코멘트의 요구사항에 대한 PR 입니다.
- `BaseOperationImpl`이 `Operation`을 구현하도록 변경하고, 기존 하위 클래스에서 `implements Operation`을 제거하였습니다.
=> INTERNAL: Implement Operation interface in BaseOperationImpl

src/main/java/net/spy/memcached/ArcusClient.java
- https://github.com/jam2in/arcus-works/issues/677
- `ArcusClient` 클래스 내 중복된 코드를 제거하기 위해, Transcoder 인자가 없는 메서드들이 Transcoder 인자를 받는 오버로딩 메서드를 호출하도록 리팩토링했습니다.
=> INTERNAL: Refactor ArcusClient using overloaded methods

docs/user_guide/02-arcus-java-client.md
- `Object`가 보여지지 않는 문제를 수정합니다.
- `<`, `>` 문자 앞에 `\` 추가합니다.
=> DOCS: Add backslash before `<`, `>`

.github/workflows/ci.yml
- ubuntu 20.04 버전이 CI에서 사라져, 캐시 서버의 CI와 동일하게 ubuntu latest 버전을 사용하도록 합니다.
-
=> FIX: use ubuntu latest version to prevent error

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/715
> new CollectionOperationStatus(new OperationStatus(...)) 로 생성하는 부분은 비효율적으로 객체를 두번 생성하는 것이므로 new CollectionOperationStatus(true, "XX", CollectionResponse.XX)로 수정한다.
- `new CollectionOperationStatus(new OperationStatus(...))` 형태로 사용하는 부분을 `new CollectioOperationStatus(.. , .., )` 형태로 수정했습니다.
- Collection 연산에서 OperationStatus를 생성해 사용하던 부분을 CollectionOperationStatus를 생성하도록 수정했습니다.
=> INTERNAL: use CollectionOperationStatus in collection API

src/main/java/net/spy/memcached/ConnectionFactory.java, src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java, src/main/java/net/spy/memcached/DefaultConnectionFactory.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/test/java/net/spy/memcached/ClientBaseCase.java
https://github.com/jam2in/arcus-works/issues/694#issuecomment-2791501998
- 기존에는 ApiType을 인자로 주지 않고, 결과를 Map을 리턴하고 리턴된 값의 Map.get(ApiType)을 통해  ReadPriority를 얻어왔다.
- 이를 getAPIReadPriority 메서드를 호출할때 인자로 ApiType을 사용하고 Map아닌 ReadPriority를 곧바로 리턴하는 구현으로 변경한다.
=> INTERNAL: change getApiReadPriority args to APIType.

src/main/java/net/spy/memcached/lock/ArcusLock.java
- https://github.com/jam2in/arcus-works/issues/681
- Arcus 전용 분산 락 인터페이스인 `ArcusLock`을 새로 추가했습니다.
- 재진입 기능과 `leaseTime`을 지원하는 메서드를 정의했습니다.
- 설계에 기반하여 JavaDoc 주석을 작성했습니다.
- 의미 전달이 불분명한 주석 내용을 수정했습니다.
- ExecutionException이 발생할 수 있는 부분에 try-catch 구문을 적용하고, 해당 예외를 ArcusLockException으로 래핑해 throw하도록 변경했습니다.
- 관련 메서드 시그니처에서 throws ExecutionException을 제거했습니다.
=> FEATURE: Add ArcusLock interface

src/main/java/net/spy/memcached/collection/CollectionResponse.java
- 
- 사용되지 않는 CollectionResponse의 일부 타입을 제거합니다.
=> INTERNAL: remove unused CollectionResponse type

src/main/java/net/spy/memcached/collection/CollectionResponse.java, src/main/java/net/spy/memcached/ops/CollectionOperationStatus.java, src/main/java/net/spy/memcached/ops/StatusCode.java
https://github.com/jam2in/arcus-works/issues/710#issuecomment-2820012306
기존의 reconnect 하지 않는 실패 응답값들에 대한 처리는 아래와 같습니다.
미리 static으로 설정된 아래의 OperationStatus를 matchStatus의 인자로 넘겨줍니다. 
인자로 설정된 OperationStatus와 응답값과 일치할 경우 해당 OperationStatus를 
Future에 설정하게 되는 것입니다.
```java
private static final OperationStatus END = new CollectionOperationStatus(
true, "END", CollectionResponse.END);
private static final OperationStatus OK = new CollectionOperationStatus(
true, "OK", CollectionResponse.OK);
```
INVALID가 응답으로 들어올 경우는 조금 다르게 구현했습니다.
동일하게 handleLine 에서 처리되어 내부의 matchStatus를 호출합니다.
다만, INVALID는 미리 static하게 설정해둔 OperationStatus가 없습니다.
이는 INVALID와 함께 오는 msg 값을 사용자에게 전달하기 위함입니다.
(ex - "INVALID too many count")
모든 INVALID 상황에 맞는 응답 메세지를 가지는 static 인스턴스를
Operation 클래스 내에 만드는것 이상한 것 같습니다.
matchStatus의 …
=> FEAT: Add INVALID response without reconnecting.

src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java, src/main/java/net/spy/memcached/protocol/ascii/StatsOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/226
- mget, stats 명령어에 대하여 INVALID 응답이 올 때의 처리를 추가합니다.
=> INTERNAL: Add matchStatus() call to handle unknown response for mget and stats commands.

src/main/java/net/spy/memcached/ops/CollectionOperationStatus.java, src/main/java/net/spy/memcached/ops/StatusCode.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/test/manual/net/spy/memcached/ops/OperationStatusTest.java
- https://github.com/jam2in/arcus-works/issues/715
- CollectionOperationStatus에 항상 StatusCode가 들어갈 수 있도록 수정합니다.
- 성공 응답인 `DELETED_DROPPED`, `CREATED`, `CREATED_STORED`, `REPLACED`, `UPDATED`의 경우 SUCCESS 코드를 가지도록 통합했습니다. 사용자가 어떤 작업을 요청해 성공했든 상관 없이, 성공했다는 의미만 반환해도 문제 없다고 생각합니다.
- 실패 응답에는 기본적으로 `ERR_` 로 시작하도록 했습니다.
- fromAsciiLine 메서드에서 String 타입을 StatusCode 타입으로 변환하기 위해 구동 시 Map에 캐싱해두도록 하고, 변환 시 Map에서 get()하도록 합니다.
=> INTERNAL: set StatusCode in CollectionOperationStatus

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/ArcusClientIF.java, src/main/java/net/spy/memcached/ArcusClientPool.java, src/test/java/net/spy/memcached/ArcusTimeoutTest.java, src/test/manual/net/spy/memcached/LongKeyTest/BaseLongKeyTest.java, src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetErrorTest.java, src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetIrregularEflagTest.java, src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetTest.java, src/test/manual/net/spy/memcached/btreesmget/SMGetErrorTest.java, src/test/manual/net/spy/memcached/btreesmget/SMGetTest.java, src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java, src/test/manual/net/spy/memcached/btreesmget/SMGetWithEflagTest.java, src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
- 
- 기존에 private old smget API만 deprecate되어 있어서, public old smget API를 deprecate시킵니다.
- 어떤 캐시 서버 버전부터 new smget을 사용할 수 있는지 javadoc에 명시하면 좋을 것 같은데, 어디에서 찾아야할 지 모르겠습니다.
- 테스트 코드에서 클래스 자체에 suppress한 것은 테스트코드 전역적으로 old smget을 사용하는 경우이고, 메서드 사용시에만 suppress한 것은 특정 테스트 케이스에서만 old smget을 사용하는 경우입니다.
=> INTERNAL: deprecate old smget API

src/main/java/net/spy/memcached/ArcusClientIF.java
- `ArcusClient` 클래스는 `MemcachedClient` 클래스를 확장하는 클래스이므로 `ArcusClientIF` 인터페이스 또한 `MemcachedClientIF` 를 상속하도록 구조를 변경하였습니다.
=> FEATURE: Inherit MemcachedClientIF in ArcusClientIF

src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
- 이 PR은 SMGetResultImpl 클래스의 refineTrimmedKeys 메서드를 개선하여 Java 8의 removeIf 기능을 활용합니다.
- 기존 코드의 Iterator를 사용한 방식에서 removeIf 메서드를 사용하는 방식으로 변경했습니다
- "FIXME: use removeIf with entrySet() when upgrading java version 8" 주석을 제거했습니다
- 코드의 가독성 및 유지보수성을 향상시켰습니다
- 사용하지 않는 import 문을 제거하였습니다. (Iterator, Map, BKeyObject)
=> INTERNAL: improve refineTrimmedKeys method using Java 8 removeIf

src/main/java/net/spy/memcached/ArcusClient.java, src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java
- 현재 ConnectionFactoryBuilder에 setDefaultCollectionTranscoder, getDefaultCollectionTranscoder라는 메서드가 존재하지만 실제로 ArcusClient 객체 생성 시에 사용되지 않습니다.
- ArcusClient 생성 시 이 속성이 반영되도록 합니다.
-
=> INTERNAL: use default collection transcoder

src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java, src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java, src/main/java/net/spy/memcached/collection/SetPipedExist.java
- https://github.com/jam2in/arcus-works/issues/669
- `getAsciiCommand()` 메서드에서 불필요한 encode 작업을 제거하고, 연산 대상 데이터에 따라 적절하게 처리되도록 전체 로직을 리팩토링 하였습니다.
- `nextOpIndex` 이후의 값들만 encode 하도록 로직을 수정했습니다.
- `encodedList`의 구성 방식이 달라짐에 따라, ascii operation string 생성 로직에서 접근하는 인덱스를 올바르게 보정했습니다.
- 기존에는 ListPipedInsert와 SetPipedInsert에서 Collection 타입을 사용하여, 인덱스 기반 접근이 불가능해 Iterator를 통한 순회 방식을 사용했습니다. 
- 코드 일관성 및 효율성 개선을 위해, ListPipedInsert와 SetPipedInsert에서 해당되는 필드와 생성자 인자의 자료형을 Collection에서 List로 변경하고, 하위 로직도 인덱스 기반 for문으로 수정했습니다.
- SetPipedInsert 관련 테스트 코드(MultibyteKeyTest)도 타입 불일치 문제를 해결하도록 수정했습니다. 
- 변수(eSize)를 활용하여 encodedList의 크기 계산을 한 번만 수행하도록 변경했습니다.
=> INTERNAL: Encode elements starting from nextOpIndex

src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- https://github.com/jam2in/arcus-works/issues/722
- ConnectionFactoryBuilder에서 인자로 들어온 값이 잘못된 경우 바로 예외를 던지도록 합니다.
=> INTERNAL: Throw exception when wrong argument came into ConnectionFactoryBuilder

src/main/java/net/spy/memcached/MemcachedConnection.java
- https://github.com/jam2in/arcus-works/issues/723
- cache_list의 변경 사항과 alter_list의 변경 사항을 모든 IO Thread가 공유하는 형태이면서도 각각의 IO Thread가 거기에 Write 연산을 수행하여 문제가 발생한다.
- 각각의 IO Thread가 cache_list의 변경 사항과 alter_list의 변경 사항을 복제한 다음 Write 연산을 수행하도록 합니다.
=> FIX: Prevent concurrent modification by cloning shared `List<InetSocketAddress>` object per thread

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
- 
- ArcusClient에서 CollectionOperationStatus 타입이 아닌지 확인하여 처리하는 부분을 하나의 메서드에 통일해 중복을 제거했습니다.
- warning log 남기는 부분은 matchStatus 메서드에 두도록 수정했습니다.
=> CLEANUP: log unhandled state in matchStatus and remove code duplications

src/main/java/net/spy/memcached/AddrUtil.java, src/main/java/net/spy/memcached/ArcusReplNodeAddress.java, src/main/java/net/spy/memcached/CacheManager.java, src/main/java/net/spy/memcached/MemcachedConnection.java, src/test/java/net/spy/memcached/AddrUtilTest.java, src/test/java/net/spy/memcached/ArcusKetamaHashingTest.java, src/test/java/net/spy/memcached/ArcusKetamaNodeLocatorTest.java, src/test/java/net/spy/memcached/ArcusTimeoutTest.java, src/test/java/net/spy/memcached/AsciiIPV6ClientTest.java, src/test/java/net/spy/memcached/BinaryIPV6ClientTest.java, src/test/java/net/spy/memcached/CancelFailureModeTest.java, src/test/java/net/spy/memcached/CancellationBaseCase.java, src/test/java/net/spy/memcached/ClientBaseCase.java, src/test/java/net/spy/memcached/ConsistentHashingTest.java, src/test/java/net/spy/memcached/DoLotsOfSets.java, src/test/java/net/spy/memcached/KetamaNodeLocatorTest.java, src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java, src/test/java/net/spy/memcached/MemcachedConnectionTest.java, src/test/java/net/spy/memcached/RedistributeFailureModeTest.java, src/test/java/net/spy/memcached/TimeoutTest.java, src/test/manual/net/spy/memcached/MemcachedConnectionReplTest.java, src/test/manual/net/spy/memcached/collection/BaseIntegrationTest.java, src/test/manual/net/spy/memcached/test/AuthTest.java, src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java, src/test/manual/net/spy/memcached/test/LoaderTest.java, src/test/manual/net/spy/memcached/test/MemcachedThreadBench.java, src/test/manual/net/spy/memcached/test/MemoryFullTest.java, src/test/manual/net/spy/memcached/test/MultiNodeFailureTest.java, src/test/manual/net/spy/memcached/test/ObserverToy.java, src/test/manual/net/spy/memcached/test/SASLConnectReconnect.java
- https://github.com/jam2in/arcus-works/issues/723
- https://github.com/jam2in/arcus-works/issues/406
- https://github.com/naver/arcus-java-client/pull/915
ZK에서 Cache List 정보를 가져왔을 때의 흐름은 다음과 같습니다.
- CacheMonitor Thread에서 Cache List 정보를 `List<String>` 형태로 수신
- CacheMonitor Thread에서 `List<String>` 형태를 `String` 형태로 변환
- CacheMonitor Thread에서 `String` 형태를 `List<InetSocketAddress>` 형태로 변환
- CacheMonitor Thread에서 `List<InetSocketAddress>` 형태의 정보를 각각의 IO Thread에게 전달
- 각각의 IO Thread는 `List<InetSocketAddress>` 형태의 정보를 사용하기 전에 먼저 복제한 다음에 사용하고, 복제본에 Write 연산 수행
- CacheMonitor Thread에서 Cache List 정보를 `List<String>` 형태로 수신
- CacheMonitor Thread에서 `List<String>` 형태의 정보를 `List<InetSocketAddress>` 형태로 변환하여 IO Thread에게 전달
- 각각의 IO Thread는 `List<InetSocketAddress>` 형태의 정보를 복제하여 사용하고, 여기에 Write 연산 수행
=> CLEANUP: Remove unnecessary type conversion from `List<String>` to `String` when parsing cache list znodes

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CASOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/PipeOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/StatsOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/698
- 복잡하게 각 Operation마다 정의되어 있던 wasCancelled 메서드의 구현들을 없애고, Collection API여서 receivedStatus() 콜백에서 CollectionOperationStatus를 사용하는 경우에만 BaseOperationImpl에 존재하는 COLLECTION_CANCELLED 상수를 사용하도록 수정합니다.
=> CLEANUP: remove wasCancelled() method

src/main/java/net/spy/memcached/protocol/ascii/PipeOperationImpl.java, src/test/java/net/spy/memcached/protocol/ascii/BaseOpTest.java
- 
- handleError에서 에러 발생 시와 동일하게 OperationStatus를 생성해 Future로 전달하도록 합니다.
- pipe error가 발생하지 않았을 경우에만 END / FAILED_END를 Future로 전달하도록 합니다.
=> FIX: Send ERR_INTERNAL status when pipe error occurred

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/transcoders/BaseSerializingTranscoder.java, src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java, src/main/java/net/spy/memcached/transcoders/IntegerTranscoder.java, src/main/java/net/spy/memcached/transcoders/LongTranscoder.java, src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java, src/main/java/net/spy/memcached/transcoders/TranscoderUtils.java, src/main/java/net/spy/memcached/transcoders/WhalinTranscoder.java, src/main/java/net/spy/memcached/transcoders/WhalinV1Transcoder.java, src/test/java/net/spy/memcached/transcoders/BaseSerializingTranscoderTest.java, src/test/java/net/spy/memcached/transcoders/SerializingTranscoderTest.java, src/test/java/net/spy/memcached/transcoders/TranscoderUtilsTest.java
- https://github.com/jam2in/arcus-works/issues/732
- 공통 상수(SERIALIZED, COMPRESSED, SPECIAL_*)를 TranscoderUtils 클래스로 이동하였습니다.
- encodeString(), decodeString(), setCharset(), examineFlags() 메서드를 TranscoderUtils로 이동하였습니다.
- 각 Transcoder 클래스에서 TranscoderUtils를 통해 공통 상수 및 메서드를 재사용하도록 변경했습니다.
- WhalinTranscoder에서 charset 변수를 활용하기 위해 getter를 추가하였습니다.
- 메서드 이동으로 인해 BaseSerializingTranscoderTest의 일부 테스트 케이스를 TranscoderUtilsTest로 이동시켰습니다.
=> INTERNAL: Refactor common constants and methods into TranscoderUtils

src/test/manual/net/spy/memcached/collection/internal/CancelFutureTest.java
- https://github.com/naver/arcus-java-client/pull/927#issuecomment-3052497966
- 주석 처리하는 대신 cancel 성공하는 경우에만 assert문 수행하도록 변경했습니다.
=> TEST: Assert only if cancel succeed

src/main/java/net/spy/memcached/CASResponse.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java, src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java, src/main/java/net/spy/memcached/protocol/ascii/CASOperationImpl.java
- https://github.com/naver/arcus-java-client/issues/932
- MISSED_KEY, TRIMMED_KEY 의 값들을 matchStatus에서 읽어보지 않도록 하기 위해 readCount라는 값을 활용하여 lineCount가 될 때 까지 읽습니다.
- lineCount만큼 모두 읽은 후에 matchStatus를 수행하여 마지막 응답을 읽도록 합니다.
- 이를 통해 matchStatus에서 `<key>` 혹은 `<key> <cause>` 를 읽지 않도록 하여 Unhandled State 워닝 로그가 뜨지 않도록 합니다.
=> FIX: Do not make unhandledState in matchStatus

src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
- https://github.com/naver/arcus-java-client/issues/932
- matchStatus의 로그 레벨을 INFO로 내립니다.
=> CLEANUP: Lower log level to info in matchStatus()

src/main/java/net/spy/memcached/ArcusClient.java, src/main/java/net/spy/memcached/internal/PipedCollectionFuture.java, src/test/manual/net/spy/memcached/bulkoperation/BopInsertBulkMultipleTest.java, src/test/manual/net/spy/memcached/bulkoperation/BopPipeUpdateTest.java, src/test/manual/net/spy/memcached/bulkoperation/LopInsertBulkMultipleValueTest.java, src/test/manual/net/spy/memcached/bulkoperation/MopInsertBulkMultipleTest.java, src/test/manual/net/spy/memcached/bulkoperation/PipeInsertTest.java, src/test/manual/net/spy/memcached/bulkoperation/SopInsertBulkMultipleValueTest.java
- https://github.com/jam2in/arcus-works/issues/540
- ArcusClient 클래스
- `syncCollectionPipedInsert() / syncCollectionPipedUpdate()` 메서드
- 현재 수행중인 op 한 개가 complete된 후에 다음 op를 MemcachedNode가 처리할 수 있도록 등록한다.
- PipedCollectionFuture
- 초기에 생성된 모든 operation들을 List 필드에 담아두도록 한다.
- 사용자로부터 cancel 요청 시, 기존에 cancel 되지 않은 상태라면 op를 순회하며 cancel을 시도한다.
- 내부적으로 혹은 사용자로부터 온 cancel 요청이 성공하지 않았거나, cancel 요청이 아직 진행중인 경우 isCancelled()는 false를 반환한다.
- 사용자의 cancel 요청(worker thread)과 내부 동작 중 cancel 요청(IO thread)이 동시에 발생할 수 있다.
- BaseOperationImpl의 callbacked 변수로 인해 해당 값을 먼저 점유한 요청이 먼저 cancel을 시도하게 된다.
- 이미 cancel된 후에는 다른 요청이 cancel을 할 수 없게 된다.
- 사용자 요청이 실패했다면 Future에서 다음 op에 대해 cancel 요청을 보낼 것이다.
- 내부 요청이 실패했다면 별다른 처리를 하지 않는다.
=> INTERNAL: make piped insert operations process synchronously

src/main/java/net/spy/memcached/collection/CollectionResponse.java, src/main/java/net/spy/memcached/ops/StatusCode.java, src/main/java/net/spy/memcached/protocol/ascii/PipeOperationImpl.java, src/test/manual/net/spy/memcached/ops/OperationStatusTest.java
- https://github.com/jam2in/arcus-works/issues/750
- Piped 컬렉션 연산이 실패했을 때 StatusCode가 SUCCESS가 반환되지 않도록 합니다.
=> FIX: Add new StatusCode `ERR_FAILED_END` and return it when piped collection operation is failed

src/main/java/net/spy/memcached/auth/AuthThread.java
- https://github.com/jam2in/arcus-works/issues/562
https://rules.sonarsource.com/java/RSPEC-112/
This rule raises an issue when a generic exception (such as Error, RuntimeException, Throwable, or Exception) is thrown.
To fix this issue, make sure to throw specific exceptions that are relevant to the context in which they arise. It is recommended to either:
- Raise a specific exception from the Java standard library when one matches. For example an IllegalArgumentException should be thrown when a method receives an invalid argument.
- Create a custom exception class deriving from Exception or one of its subclasses.
```java
void checkValue(int value) throws Throwable { // Noncompliant: signature is too broad
if (value == 42) {
throw new RuntimeException("Value is 42"); // Noncompliant: This …
```
=> CLEANUP: Throw IllegalStateException instead of RuntimeException in AuthThread constructor

src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java, src/test/manual/net/spy/memcached/collection/internal/CancelFutureTest.java
- https://github.com/jam2in/arcus-works/issues/716
- `CollectionGetBulkFuture#getOperationStatus` 메서드를 deprecate합니다.
=> CLEANUP: Deprecate CollectionGetBulkFuture#getOperationStatus

src/main/java/net/spy/memcached/auth/AuthThread.java, src/main/java/net/spy/memcached/ops/StatusCode.java, src/main/java/net/spy/memcached/protocol/binary/SASLBaseOperationImpl.java
- https://github.com/naver/arcus-java-client/pull/942#discussion_r2320858175
- binary sasl 연산이 최종 성공하면 SASL_OK 메세지를 포함하게 합니다.
- binary sasl 연산이 실패하면 AUTH_ERROR 메세지를 포함하게 합니다.
=> INTERNAL: Change auth messages of binary sasl operations

src/main/java/net/spy/memcached/MemcachedClient.java
- https://github.com/jam2in/arcus-works/issues/756
- asyncGetsBulk 메서드에서 `enabledMGetOp` 대신 `enabledMGetsOp` 를 사용하도록 수정합니다.
=> FIX: Use enabledMGetsOp in asyncGetsBulk method

src/test/java/net/spy/memcached/ProtocolBaseCase.java, src/test/manual/net/spy/memcached/collection/attribute/GetAttrTest.java
- 
- touch 테스트를 다시 활성화합니다.
- https://github.com/naver/arcus-memcached/pull/892 PR이 먼저 반영되어야 합니다.
=> TEST: Enable touch test
