- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/ExtendedBTreeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java
Calculate the length of key string after translate it to byte array.
(issue : https://github.com/naver/arcus-java-client/issues/35)
> https://github.com/naver/arcus-java-client/issues/35 patch

- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java
Calculate the length of key string after translate it to byte array.
(issue : https://github.com/naver/arcus-java-client/issues/35)
> Issue 035 - Additional patch

- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
Added test code for key strings in multi-byte language
https://github.com/naver/arcus-java-client/issues/35
> Added test code for key strings in multi-byte language

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/MemcachedClient.java
- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/MemcachedNode.java
- src/main/java/net/spy/memcached/MemcachedNodeROImpl.java
- src/main/java/net/spy/memcached/auth/AuthThread.java
- src/main/java/net/spy/memcached/internal/BulkGetFuture.java
- src/main/java/net/spy/memcached/internal/CollectionFuture.java
- src/main/java/net/spy/memcached/internal/CollectionGetBulkFuture.java
- src/main/java/net/spy/memcached/internal/OperationFuture.java
- src/main/java/net/spy/memcached/internal/SMGetFuture.java
- src/main/java/net/spy/memcached/ops/Operation.java
- src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/test/java/net/spy/memcached/CancellationBaseCase.java
- src/test/java/net/spy/memcached/MockMemcachedNode.java
@aiceru, @jhpark816 최종 리뷰 부탁드립니다.
> add messages about operation canceled

- src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeStoreAndGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkStoreOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedStoreOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionStoreOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionUpsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/ExtendedBTreeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java
trainling spaces 를 제거한 PR입니다.
@jhpark816 review 부탁드립니다.
> delete trainling spaces

- docs/02-arcus-java-client.md
Enhanced the contents of manual about setting up Logger for Java client
> Logger manual patch

- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
@aiceru, @jhpark816 리뷰 부탁드립니다.
>  add configuration to use replication

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/OperationFactory.java
- src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java
- src/main/java/net/spy/memcached/collection/BTreeGet.java
- src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java
- src/main/java/net/spy/memcached/collection/CollectionGet.java
- src/main/java/net/spy/memcached/collection/ExtendedBTreeGet.java
- src/main/java/net/spy/memcached/collection/ListGet.java
- src/main/java/net/spy/memcached/collection/SetGet.java
- src/main/java/net/spy/memcached/ops/BTreeFindPositionWithGetOperation.java
- src/main/java/net/spy/memcached/ops/BTreeGetByPositionOperation.java
- src/main/java/net/spy/memcached/ops/CollectionGetOperation.java
- src/main/java/net/spy/memcached/ops/ExtendedBTreeGetOperation.java
- src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/ExtendedBTreeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolBTreeGetTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolListGetTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolSetGetTest.java
delete unused generic variables at collection get classes
> delete unused generic variable

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/collection/BTreeGet.java
- src/main/java/net/spy/memcached/collection/CollectionGet.java
- src/main/java/net/spy/memcached/ops/CollectionGetOperation.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
subkey type 을 generic 으로 사용할 필요가 없을 것 같아 String 으로 변환합니다.
확인 부탁드립니다. 
이슈를 통해 이미 리뷰는 하셔서 금방 하실 수 있을 것 같습니다.  :sweat_smile: 
@aiceru, @jhpark816
> change subkey type to String

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/OperationFactory.java
- src/main/java/net/spy/memcached/collection/BTreeDelete.java
- src/main/java/net/spy/memcached/collection/CollectionDelete.java
- src/main/java/net/spy/memcached/collection/ListDelete.java
- src/main/java/net/spy/memcached/collection/SetDelete.java
- src/main/java/net/spy/memcached/ops/CollectionDeleteOperation.java
- src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolBTreeDeleteTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolListDeleteTest.java
https://github.com/jam2in/tasks/issues/72 CollectionDelete generic 사용 검토 PR입니다.
리뷰 부탁드립니다.
@aiceru @jhpark816
> delete unnecessary generic

- src/main/java/net/spy/memcached/collection/SetDelete.java
- src/main/java/net/spy/memcached/collection/SetExist.java
to specify type generics <T> to Transcoder tc parameter.
> Fixed SetDelete and SetExist constructors

- src/main/java/net/spy/memcached/collection/SetDelete.java
- src/main/java/net/spy/memcached/collection/SetExist.java
Reverts naver/arcus-java-client#71
> Revert "Fixed SetDelete and SetExist constructors"

- src/main/java/net/spy/memcached/collection/SetDelete.java
- src/main/java/net/spy/memcached/collection/SetExist.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
(with test code for CollectionExist includes SetExist)
Test code 에 남아있던 문제를 마저 수정하고, build warning 제거 확인하였습니다.
> Fixed SetDelete and SetExist constructors.

- src/main/java/net/spy/memcached/BulkService.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkSetTest.java
BulkWorker, BulkSetWorker 의 constructor 에 valid argument check logic 을 추가하고, call() 에서 매번 호출하는 isDataExist() 를 삭제하였습니다.
review & merge 부탁드립니다.
> Added arguments check logic to BulkWorker and its subclasses

- docs/02-arcus-java-client.md
- src/main/java/net/spy/memcached/ConnectionFactory.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- src/main/java/net/spy/memcached/DefaultConnectionFactory.java
- src/main/java/net/spy/memcached/plugin/FrontCacheMemcachedClient.java
- src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
- src/test/java/net/spy/memcached/ClientBaseCase.java
front cache (ehcache) 에 copy on read / copy on write 기능을 추가.
Default 는 둘 다 false 로 설정함.
review
> Feature : Added CopyOnRead / CopyOnWrite properties to Arcus front cache

- src/main/java/net/spy/memcached/collection/CollectionBulkStore.java
- src/main/java/net/spy/memcached/collection/CollectionCreate.java
- src/main/java/net/spy/memcached/collection/CollectionPipedStore.java
- src/main/java/net/spy/memcached/collection/CollectionStore.java
- src/main/java/net/spy/memcached/collection/CollectionType.java
- src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
- src/test/manual/net/spy/memcached/collection/list/LopOverflowActionTest.java
- src/test/manual/net/spy/memcached/collection/set/SopOverflowActionTest.java
https://github.com/jam2in/arcus-task/issues/87 이슈입니다.
해당 collection 에서 사용 가능한 overflow action 을 지정한 것인지 확인하는 로직을 추가하였습니다.
잘못된 overflow action 을 지정하는 경우 IllegalArguementException 이 발생합니다.
리뷰 부탁 드립니다.
* 본 PR은 https://github.com/naver/arcus-java-client/pull/77 PR 를 취소하고 다시 생성한 내용입니다.
> added available overflow action argument check in collection

- src/main/java/net/spy/memcached/collection/CollectionBulkStore.java
- src/main/java/net/spy/memcached/collection/CollectionPipedStore.java
https://github.com/jam2in/arcus-task/issues/117 이슈 입니다.
ascii protocol 생성 시 누락된 overflow action 과 unreadable 속성을 추가하였습니다.
**reviewer**
> add missing attributes overflowaction and unreadable

- .travis.yml
- ChangeLog
- install-arcus-memcached.sh
- mvnTestConf.json
- pom.xml
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/collection/CollectionBulkStore.java
- src/main/java/net/spy/memcached/collection/CollectionCreate.java
- src/main/java/net/spy/memcached/collection/CollectionPipedStore.java
- src/main/java/net/spy/memcached/collection/CollectionStore.java
- src/main/java/net/spy/memcached/collection/CollectionType.java
- src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
- src/test/java/net/spy/memcached/ClientBaseCase.java
- src/test/java/net/spy/memcached/LongClientTest.java
- src/test/java/net/spy/memcached/ObserverTest.java
- src/test/java/net/spy/memcached/QueueOverflowTest.java
- src/test/manual/net/spy/memcached/ArcusClientConnectTest.java
- src/test/manual/net/spy/memcached/ArcusClientFrontCacheTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
- src/test/manual/net/spy/memcached/collection/list/LopOverflowActionTest.java
- src/test/manual/net/spy/memcached/collection/set/SopOverflowActionTest.java
2016-08-31 [version 1.9.5]
* [Fix] Add overflowAction availability check logic to collection APIs.
* [Fix] Add overflowAction / readable options to collection store APIs.
* [Fix] Remove unnecessary log messages.
* [Fix] Refactor unit tests.
* [Doc] Fix wrong comments about dropIfEmpty options in ArcusClientIf.
* [Other] Update maven surefire plugin version to 2.19.
* [Other] Apply CI tool (Travis-CI).
> Version 1.9.5

- pom.xml
- src/main/java/net/spy/memcached/ArcusClient.java
> Fixed bopGetBulk reverse bug

- src/main/java/net/spy/memcached/collection/BTreeDelete.java
Remove BtreeDelete variable duplicated Initialization.
> Remove BtreeDelete duplicate code

- src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
Hotfix logging for CLIENT_ERROR bad command line format
> Added bad command logging

- src/main/java/net/spy/memcached/MemcachedClient.java
- src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
Added local cache hit logging
reviewer
-  [x] @jhpark816
-  [x] @whchoi83
> Added local cache hit logging

- src/main/java/net/spy/memcached/ArcusClient.java
> FIX: add asyncBopExtendedGet status response default case

- src/main/java/net/spy/memcached/ConnectionFactory.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- src/main/java/net/spy/memcached/DefaultConnectionFactory.java
- src/main/java/net/spy/memcached/MemcachedClient.java
- src/test/java/net/spy/memcached/ClientBaseCase.java
main reviewer
@minkikim89 
final reviewer
@jhpark816 
java client에서 서버와 동일한 invalid prefix check 부분 추가했습니다.
> ENHANCE : add prefix invalidation

- src/main/java/net/spy/memcached/collection/BTreeGetBulk.java
- src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java
- src/main/java/net/spy/memcached/collection/BTreeSMGet.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
- src/main/java/net/spy/memcached/collection/MapDelete.java
- src/main/java/net/spy/memcached/collection/MapGet.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
> CLEANUP: Change from comma-separating to space-separating

- docs/03-key-value-API.md
- src/main/java/net/spy/memcached/ArcusClientPool.java
- src/main/java/net/spy/memcached/MemcachedClient.java
- src/main/java/net/spy/memcached/MemcachedClientIF.java
- src/main/java/net/spy/memcached/OperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/MGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java
> FEATURE: Add mget

- src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java
@jhpark816 
get operation command build 에서
공통 코드 정리, naming 수정 관련 PR 입니다.
확인 요청 드립니다.
> CLEANUP: refactor get operation command build.

- docs/06-btree-API.md
@jhpark816 
asyncBopFindPositionWithGet() API에 대한 설명 추가 PR입니다.
> DOC : add a description of asyncBopFindPositionWithGet

- src/main/java/net/spy/memcached/MemcachedClient.java
first reviewer
final reviewer
getBulk operation에서, node 당 N개의 operation으로 key string을
나누어 보낼수 있도록 하는 기능 PR 입니다.
하나의 operation당 key size는 200개 입니다.
리뷰 요청 드립니다.
> CLEANUP: divide the getBulk operation by N(=200) keys per node.

- src/main/java/net/spy/memcached/MemcachedClientIF.java
- src/test/java/net/spy/memcached/ProtocolBaseCase.java
@jhpark816 
MAX_KEY_LENGTH 증가 관련 PR입니다.
> FEATURE: Increase MAX_KEY_LENGTH: 250 => 32000

- src/main/java/net/spy/memcached/ArcusClient.java
first reviewer
final reviewer
map collection에서 max mkey length를 check 추가에 대한 PR입니다.
ArcusClient 내부에서만 validateMKey()를 사용하지만
MemcachedClient 내부에 둔 이유는 기존 validateKey()와
같은 위치에 동작 코드를 두기 위함 입니다.
확인 요청 드립니다.
> CLEANUP: add max mkey length check in map collection

- src/test/manual/net/spy/memcached/LongKeyTest/BaseLongKeyTest.java
first reviewer
final reviewer
Long key support에 대한 unit test 추가 입니다.
KV, Collection의 기본 operation에 대한 test와
bop GetBulk, SortMergeGet test로 구성되어 있습니다.
확인 요청 드립니다.
> TEST: add long key test.

- docs/06-btree-API.md
@minkikim89 
@jhpark816 
BopFindPositionWithGet 문서 관련 PR입니다.
server response에 대한 설명 수정과 future.get()에 대한 결과로 반환된 객체에 대한 설명 추가입니다.
> DOC : BopFindPositionWithGet(add a description)

- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-btree-API.md
- docs/07-map-API.md
@minkikim89 
@jhpark816 
collection API 설명 추가한 PR입니다.
표내용 수정과 future객체에 대한 설명이 필요한 부분에 대해서는 부가설명을 추가해 두었습니다.
확인 부탁드립니다.
> DOC : add description of collection

- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeTest.java
@jhpark816 
smget unit test 추가 PR입니다.
> TEST : add smget test

- docs/07-btree-API.md
arcus client의 API를 보던 중, 오자를 발견하여 request드립니다.
> typo at btree-API.md

- docs/09-other-API.md
line 16: items을 -> item들을
line 17: items을 삭제하므로 -> item들이 삭제되므로
> korean context modify

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
instance version을 기반으로
MGetOperation 사용 여부를 판단하는 부분의 조건이
잘못되었던 문제를 수정하기 위한 PR 입니다.
> FIX: instance version comparsion change for use MGetOperation

- README.md
README 파일에 travis-ci test status img 추가를 위한 PR 입니다.
@jhpark816 
확인 요청 드립니다.
> TEST: add travis-ci test status image in README.md

- .travis.yml
- mvnTestConf.json
- src/main/java/net/spy/memcached/CacheManager.java
- src/test/java/net/spy/memcached/AsciiClientTest.java
- src/test/java/net/spy/memcached/BinaryClientTest.java
- src/test/java/net/spy/memcached/CancelFailureModeTest.java
- src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
- src/test/java/net/spy/memcached/RedistributeFailureModeTest.java
- src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
> FIX: Bug patch caused by CacheManager(v1.9.8)

- .travis.yml
- mvnTestConf.json
- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/test/java/net/spy/memcached/AsciiClientTest.java
- src/test/java/net/spy/memcached/BinaryClientTest.java
- src/test/java/net/spy/memcached/CancelFailureModeTest.java
- src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
- src/test/java/net/spy/memcached/RedistributeFailureModeTest.java
- src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
reviewer
1.10.0 추가 commit
- add asyncBopExtendedGet status response default case (commit link: naver/arcus-java-client@634bab9)
> FIX: Bug patch caused by CacheManager(v1.10.0)

- .travis.yml
- mvnTestConf.json
- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/test/java/net/spy/memcached/AsciiClientTest.java
- src/test/java/net/spy/memcached/BinaryClientTest.java
- src/test/java/net/spy/memcached/CancelFailureModeTest.java
- src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
- src/test/java/net/spy/memcached/RedistributeFailureModeTest.java
- src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
> FIX: Bug patch caused by CacheManager(v1.10.1-SNAPSHOT)

- .travis.yml
- mvnTestConf.json
- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/test/java/net/spy/memcached/AsciiClientTest.java
- src/test/java/net/spy/memcached/BinaryClientTest.java
- src/test/java/net/spy/memcached/CancelFailureModeTest.java
- src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
- src/test/java/net/spy/memcached/RedistributeFailureModeTest.java
- src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
> FIX: Bug patch caused by CacheManager(v1.10.1)

- .travis.yml
- mvnTestConf.json
- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/test/java/net/spy/memcached/AsciiClientTest.java
- src/test/java/net/spy/memcached/BinaryClientTest.java
- src/test/java/net/spy/memcached/CancelFailureModeTest.java
- src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
- src/test/java/net/spy/memcached/RedistributeFailureModeTest.java
- src/test/manual/net/spy/memcached/test/ExcessivelyLargeGetTest.java
> FIX: Bug patch caused by CacheManager(v1.11.1-SNAPSHOT)

- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/test/java/net/spy/memcached/CacheMonitorTest.java
CacheListZnode 변경 event 처리와 관련되어
naming을 변경을 위한 PR 입니다.
first reviewer
final reviewer
확인 요청 드립니다.
> CLEANUP: renaming of CacheListZnode

- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
@minkikim89 
https://github.com/jam2in/arcus-memcached-EE/issues/624 관련 PR입니다.
확인 부탁드립니다.
> TEST : smget test modified for subversion

- src/test/manual/net/spy/memcached/ArcusClientFrontCacheTest.java
- src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetErrorTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetWithEflagTest.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkSetTest.java
- src/test/manual/net/spy/memcached/bulkoperation/LopInsertBulkMultipleValueTest.java
- src/test/manual/net/spy/memcached/bulkoperation/LopInsertBulkTest.java
- src/test/manual/net/spy/memcached/bulkoperation/MopInsertBulkMultipleTest.java
- src/test/manual/net/spy/memcached/bulkoperation/MopInsertBulkTest.java
- src/test/manual/net/spy/memcached/bulkoperation/SopInsertBulkMultipleValueTest.java
- src/test/manual/net/spy/memcached/bulkoperation/SopInsertBulkTest.java
- src/test/manual/net/spy/memcached/collection/ElementFlagFilterTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopGetBulkTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopUpdateTest.java
- src/test/manual/net/spy/memcached/collection/btree/longbkey/BopGetBulkTest.java
- src/test/manual/net/spy/memcached/test/SASLConnectReconnect.java
https://github.com/jam2in/arcus-memcached-EE/issues/625 관련 PR입니다.
확인 부탁드립니다.
> TEST : check unit test exception handling

- src/main/java/net/spy/memcached/CacheManager.java
CacheManager 에서 address string
parsing 부분에 대한 refactoring 입니다.
@minkikim89 @jhpark816 
확인 요청 드립니다.
> CLEANUP: refactoring of get address

- src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkStoreOperationImpl.java
CollectionBulkStoreOperation에 pipeline response
handling 추가를 위한 PR 입니다.
@minkikim89 @jhpark816 
확인 요청 드립니다.
> CLEANUP: handle correctly the command pipeline response

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/ArcusClientPool.java
- src/main/java/net/spy/memcached/OperationFactory.java
- src/main/java/net/spy/memcached/collection/RangeGet.java
- src/main/java/net/spy/memcached/ops/APIType.java
- src/main/java/net/spy/memcached/ops/RangeGetOperation.java
- src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/RangeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java
통합테스트를 위한 rget operation 관련 java-client 코드 수정입니다.
> FEATURE : rangeget

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
reviewer
Reconnect 로 인한 setupResend() 수행에서 이미 cancel 처리된 write operation에 대해
중복으로 cancel 처리하던 오류 수정을 위한 PR 입니다.
확인 요청 드립니다.
> FIX: do not cancel an operation that already canceled in setupResend

- src/main/java/net/spy/memcached/ConnectionFactory.java
> CLEANUP: edit getMaxReconnectDelay method comment

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/BulkService.java
BulkService 코드에 대해 리팩토링 진행하였습니다.
executor.submit 시에 RejectedExecutionException이 발생할 수 있는 상황인데,
현재는 이에 대한 처리를 해두지 않아 응용에서 바로 이 exception을 받게 되도록
구현되었습니다. 이에 대해 따로 처리를 해야할지는 의문입니다.
> CLEANUP: refactor BulkService

- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
collection의 response format에 대한 주석을 추가하였습니다.
> CLEANUP: update comment for collection response format

- docs/03-key-value-API.md
- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/ArcusClientPool.java
- src/main/java/net/spy/memcached/BulkService.java
- src/test/java/net/spy/memcached/ArcusTimeoutTest.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkDeleteTest.java
bulkService 사용해서 asyncDeleteBulk 개발하였습니다.
> FEATURE: asyncDeleteBulk

- src/main/java/net/spy/memcached/BulkService.java
bulkService 객체들의 인자들 순서를 변경하였습니다.
> CLEANUP: adjust the order of set,delete bulk constructor arguments

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/CASMutator.java
- src/main/java/net/spy/memcached/MemcachedClient.java
https://github.com/naver/arcus-java-client/issues/221 이슈 PR입니다.
> CLEANUP: change some javadoc comments to use code tag

- src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
- src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
assert 문으로 인해 해시 충돌이 일어났을 때 구동 실패하는 버그가 있네요.
수정했습니다.
> FIX: assert failure occurs when there are duplicate nodes

- src/test/java/net/spy/memcached/ArcusKetamaHashingTest.java
ArcusKetamaHashing 테스트 추가하였습니다.
ConsistentHashingTest를 수정하여 만들었으며,
기존 테스트들에 collision케이스를 추가하였습니다.
> TEST: add ArcusKetamaHashingTest

- checkstyle-suppressions.xml
- src/test/java/net/spy/memcached/CacheMonitorTest.java
- src/test/java/net/spy/memcached/MemcachedConnectionTest.java
- src/test/java/net/spy/memcached/internal/CheckedOperationTimeoutExceptionTest.java
- src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetErrorTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopMutateTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopServerMessageTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeTest.java
- src/test/manual/net/spy/memcached/collection/set/SopServerMessageTest.java
> CLEANUP: reduce line length in test sources

- docs/02-arcus-java-client.md
- src/main/java/net/spy/memcached/ConnectionFactory.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- src/main/java/net/spy/memcached/DefaultConnectionFactory.java
- src/test/java/net/spy/memcached/ArcusTimeoutTest.java
- src/test/java/net/spy/memcached/ClientBaseCase.java
bulkService 관련하여 사용하지 않는 함수들에 대해서는 삭제,  관련 API들은 deprecate 하였습니다.
> CLEANUP: deprecate bulkService API

- checkstyle-suppressions.xml
- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/ArcusClientPool.java
ArcusClient 코드에 대해서 line length 100 미만으로 줄였습니다.
> CLEANUP: reduce line length in client sources

- src/main/java/net/spy/memcached/MemcachedConnection.java
socketChannel API 사용하는 부분들에 대해 수정하였습니다.
> CLEANUP: refactor the parts that use socketChannel API

- checkstyle.xml
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/MemcachedClient.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java
- src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java
- src/test/java/net/spy/memcached/transcoders/BaseTranscoderCase.java
- src/test/manual/net/spy/memcached/collection/btree/BopInsertWhenKeyNotExist.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeTest.java
- src/test/manual/net/spy/memcached/collection/list/LopInsertWhenKeyNotExist.java
- src/test/manual/net/spy/memcached/collection/map/MopInsertWhenKeyNotExist.java
- src/test/manual/net/spy/memcached/collection/set/SopInsertWhenKeyNotExist.java
> CLEANUP: replace tab charcter to space

- checkstyle.xml
- src/main/java/net/spy/memcached/HashAlgorithm.java
- src/test/java/net/spy/memcached/CacheMonitorTest.java
> CLEANUP: remove nested block

- checkstyle.xml
- src/main/java/net/spy/memcached/AddrUtil.java
- src/main/java/net/spy/memcached/KeyUtil.java
- src/main/java/net/spy/memcached/compat/CloseUtil.java
- src/main/java/net/spy/memcached/util/BTreeUtil.java
- src/test/java/net/spy/memcached/DoLotsOfSets.java
- src/test/manual/net/spy/memcached/test/MemoryFullTest.java
- src/test/manual/net/spy/memcached/test/MultiNodeFailureTest.java
- src/test/manual/net/spy/memcached/test/ObserverToy.java
static method 만을 가지고 있는 utility class의 생성자 호출을 막도록 수정하였습니다.
> CLEANUP: prevent instantiation of utility classes

- checkstyle-suppressions.xml
- src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetWithEflagTest.java
- src/test/manual/net/spy/memcached/collection/BaseIntegrationTest.java
- src/test/manual/net/spy/memcached/collection/list/LopBulkAPITest.java
- src/test/manual/net/spy/memcached/collection/map/MopBulkAPITest.java
- src/test/manual/net/spy/memcached/collection/set/SopBulkAPITest.java
- src/test/manual/net/spy/memcached/collection/set/SopExistTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolSetDeleteTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolSetExistTest.java
- src/test/manual/net/spy/memcached/emptycollection/VariousTypeTest.java
- src/test/manual/net/spy/memcached/frontcache/LocalCacheManagerTest.java
- src/test/manual/net/spy/memcached/test/MemcachedThreadBench.java
테스트 코드에도 field modifier를 private로 수정하였습니다.
> CLEANUP: change the field modifier to private in test

- checkstyle.xml
- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/StatisticsHandler.java
- src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java
- src/test/java/net/spy/memcached/internal/SingleElementInfiniteIteratorTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopInsertWhenKeyNotExist.java
- src/test/manual/net/spy/memcached/collection/list/LopInsertWhenKeyNotExist.java
- src/test/manual/net/spy/memcached/collection/map/MopInsertWhenKeyNotExist.java
- src/test/manual/net/spy/memcached/collection/set/SopInsertWhenKeyNotExist.java
> CLEANUP: add comment in empty block

- src/main/java/net/spy/memcached/CacheManager.java
IO thread 이름에 pool 번호가 들어가도록 수정했습니다.
> CLEANUP: change IO thread name to detail

- checkstyle.xml
- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/MemcachedNodeROImpl.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
left curly('{'), right curly('}') 의 위치를 조정하였습니다.
> CLEANUP: change the placement of left, right curly braces

- checkstyle-suppressions.xml
- src/test/manual/net/spy/memcached/ArcusClientNotExistsServiceCodeTest.java
- src/test/manual/net/spy/memcached/btreesmget/ByteArrayBKeySMGetErrorTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetErrorTest.java
- src/test/manual/net/spy/memcached/btreesmget/SMGetWithCombinationEflagTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopFindPositionWithGetTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopGetBulkTest.java
- src/test/manual/net/spy/memcached/collection/btree/longbkey/BopGetBulkTest.java
- src/test/manual/net/spy/memcached/collection/set/SopPipedExistTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertBTreeWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertListWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertMapWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertSetWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/VariousTypeTest.java
> CLEANUP: add braces around single-line 'if' statement in test sources

- src/test/java/net/spy/memcached/ProtocolBaseCase.java
E2BIG 에러가 CLIENT_ERROR로 변경되어 관련 테스트 코드를 수정하였습니다.
> FIX: changed E2BIG error as CLIENT_ERROR

- pom.xml
> FEATURE: upgrade to the latest log4j version

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
https://github.com/naver/arcus-java-client/issues/283 이슈에 대한 PR입니다.
> FIX: concurrency problem in input queue offer when moving the operations

- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/main/java/net/spy/memcached/collection/BTreeFindPosition.java
- src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java
- src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java
- src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java
- src/main/java/net/spy/memcached/package.html
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
이슈는 아래 링크 참고 바랍니다.
https://github.com/naver/arcus-java-client/issues/290
> DOC: fixed the javadoc generation errors

- docs/01-arcus-cloud-basics.md
- docs/02-arcus-java-client.md
- docs/03-key-value-API.md
- docs/04-list-API.md
- docs/05-set-API.md
- docs/06-map-API.md
- docs/07-btree-API.md
- docs/arcus-java-client-getting-started.md
c 클라이언트 [PR #109](https://github.com/naver/arcus-c-client/pull/109)와 동일한 목적의 PR입니다.
마찬가지로 헤더 레벨을 하나씩 올렸습니다.
02-arcus-java-client.md 파일은 H3 하부 챕터로 바로 H5가 나오는데, 각각 H2와 H3로 고쳤습니다
> DOC: decrease header level to improve document system's UI

- docs/01-arcus-cloud-basics.md
- docs/02-arcus-java-client.md
- docs/03-key-value-API.md
- docs/07-btree-API.md
- docs/08-attribute-API.md
- docs/09-other-API.md
- docs/10-log-message.md
- docs/11-client-notes.md
- docs/arcus-java-client-getting-started.md
- docs/arcus-java-client-user-guide.md
코드나 로그에 관한 부분을 제외하고 Arcus로 표기된 부분을 ARCUS로 바꾸었습니다.
> Capitalize ARCUS

- src/main/java/net/spy/memcached/CacheManager.java
zk admin address를 보관하는 변수의 이름을 변경하기 위한 PR입니다.
zk admin address는 ip port 형식 뿐만 아니라, 도메인 형식도 될 수 있기때문에
기존 hostPort를 zkConnectString 으로 변경했습니다.
@jhpark816 
확인 요청 드립니다.
> CLEANUP: renaming hostPort in CacheManager

- pom.xml
- src/test/manual/net/spy/memcached/emptycollection/InsertBTreeWithAttrAndEFlagTest.java
- src/test/manual/net/spy/memcached/emptycollection/InsertListWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/InsertMapWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/InsertSetWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertBTreeWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertListWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertMapWithAttrTest.java
- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertSetWithAttrTest.java
https://github.com/naver/arcus-java-client/pull/301 이슈에 대한 PR 입니다.
> TEST: bump junit from 4.4 to 4.13.1 

- docs/02-arcus-java-client.md
- docs/07-btree-API.md
- docs/08-attribute-API.md
> DOC: fix dead link

- checkstyle.xml
- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/compat/log/SLF4JLogger.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/util/ArcusKetamaNodeLocatorConfiguration.java
- src/test/java/net/spy/memcached/AsciiClientTest.java
- src/test/java/net/spy/memcached/BinaryClientTest.java
- src/test/java/net/spy/memcached/CancelFailureModeTest.java
- src/test/java/net/spy/memcached/MemcachedClientConstructorTest.java
- src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java
- src/test/manual/net/spy/memcached/LongKeyTest/BaseLongKeyTest.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkDeleteTest.java
- src/test/manual/net/spy/memcached/collection/CollectionMaxElementSize.java
- src/test/manual/net/spy/memcached/ops/OperationStatusTest.java
#324 에 관련한 pr입니다.
white space checkstyle 주석처리 되어있던 부분을 google style guide에 맞추어 적용하였습니다.
https://github.com/checkstyle/checkstyle/blob/14005e371803bd52dff429904b354dc3e72638c0/src/main/resources/google_checks.xml#L105
whitespace에 관련된 2가지 속성을 추가했습니다.
- [whiteSpaceAfter](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAfterCheck.html)
- 뒤에 whiteSpace가 오는지 체크합니다. 
- [whiteSpaceAround](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/whitespace/WhitespaceAroundCheck.html )
- 앞뒤로 whiteSpace가 오는지 체크합니다.
> CLEANUP: apply WhiteSpace checkstyle 

- docs/arcus-future-get-API.md
- docs/arcus-java-client-user-guide.md
#308 에 대한 pr입니다.
- Future API의 공통적인 설명을 추가
- Future 구현체들을 통해 사용할 수있는 추가적인 API에 대한 설명을 추가
- ImmediateFuture의 경우에는 추가된 API는 없지만 추가될 상황을 고려하여 공백상태로 추가해 두었습니다.
> DOC: add the description of future api

- src/main/java/net/spy/memcached/MemcachedClient.java
#331 에 관련한 pr입니다.
- syncAPI (get, gets, getBulk, getsBulk, cas, incr, decr)의 Exception Catch시에
operation을 cancel합니다.
- cancel에 관련한 주석을 달기 위해 cancel과 관련한 동작을 하나의 method로 통합하여 처리했습니다.
> FIX: the operation was canceled when the exception occured

- src/main/java/net/spy/memcached/ArcusClientPool.java
https://github.com/naver/arcus-java-client/issues/341 이슈에 대한 PR 입니다.
> FIX: support library backward compatibility for arcus-spring

- src/main/java/net/spy/memcached/ArcusClient.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkStoreTest.java
default transcoder를 사용하는 코드가 존재하여 object를 encoding 하거나, byte array를 decoding할 때 실패하는 현상을 수정하였습니다.
> FIX: do not use default transcoder

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/MemcachedClient.java
Javadoc param이 실제 param과 일치하지 않는 부분이 있어 수정하였습니다.
> DOC: fix invalid javadoc param

- README.md
jdk의 최소 요구버전을 README.md에 추가하였습니다.
> DOC : add jdk requirements to README.md

- src/main/java/net/spy/memcached/StatisticsHandler.java
mbean 모니터링시 캐시 리스트가 변경되어도, 추가 혹은 제거된 캐시 노드의 attribute 항목에 업데이트 되지 않는 현상을 수정하였습니다.
추가로 노드의 버전도 mbean 모니터링에서 조회할 수 있도록 추가하였습니다.
> FEATURE: update node statistics when the cache list changes

- src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CASOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/DeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/FlushByPrefixOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/FlushOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/MutatorOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java
replication 삼중화 지원을 위한 pr에서 내용을 분리하여 pr합니다.
- SWITCHOVER , REPL_SLAVE 판단을 위한 hasSwitchedOver 메소드를 추가했습니다.
> CLEANUP : refactored the method to checking switchover

- src/main/java/net/spy/memcached/ArcusReplNodeAddress.java
- src/main/java/net/spy/memcached/MemcachedReplicaGroup.java
#362 의 pr에 선행된 작업입니다.
n개의 node를 가진 replication group을 검증을 할 수 있도록  validate method를 리팩토링 했습니다.
> CLEANUP : refactored the method for validating replication group

- src/main/java/net/spy/memcached/ArcusReplNodeAddress.java
해당 메서드에서 checkstyle로 인해 build 오류가 발생하는 문제를 해결했습니다.
> FIX : add new line for checkstyle

- docs/11-client-notes.md
https://github.com/naver/arcus-java-client/issues/336 이슈와 관련하여
character encoding과 관련한 문서를 추가하였습니다.
> DOC: add the precaution about character encoding

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
https://github.com/naver/arcus-java-client/issues/391 이슈에 관한 PR입니다.
> ENHANCE: filter duplicated operation from not writeQ but readQ

- src/main/java/net/spy/memcached/MemcachedConnection.java
indentation 오류로 인해 컴파일 실패하여 수정하였습니다.
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building Arcus Java Client 1.13.2
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.4.1:clean (default-clean) @ arcus-java-client ---
[INFO]
[INFO] --- maven-checkstyle-plugin:3.1.1:check (validate) @ arcus-java-client ---
[INFO] Starting audit...
[WARN] /home/test/arcus-java-client-version/develop/src/main/java/net/spy/memcached/MemcachedConnection.java:1135: 'if' child has incorrect indentation level 7, expected level should be 6. [Indentation]
[WARN] /home/test/arcus-java-client-version/develop/src/main/java/net/spy/memcached/MemcachedConnection.java:1136 …
```
> CLEANUP: incorrect indentation

- pom.xml
- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/collection/BKeyObject.java
- src/main/java/net/spy/memcached/collection/BTreeCount.java
- src/main/java/net/spy/memcached/collection/BTreeDelete.java
- src/main/java/net/spy/memcached/collection/BTreeGet.java
- src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
- src/main/java/net/spy/memcached/collection/CollectionAttributes.java
- src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java
- src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java
- src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java
- src/main/java/net/spy/memcached/collection/SMGetElement.java
- src/main/java/net/spy/memcached/collection/SMGetTrimKey.java
- src/main/java/net/spy/memcached/util/BTreeUtil.java
- src/test/java/net/spy/memcached/util/BTreeUtilTest.java
#406 pr을 다시 원상복구 합니다.
dependency, test 코드 삭제 및 기존 변경 코드도 다시 원래대로 복구해두었습니다.
> FIX: rollback fixed bkey long type string to unsinged long type string on bkey

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
https://github.com/naver/arcus-java-client/pull/389 PR에 이어서
retry, redistribute 모드일 때 delay reconnect가 발생될 경우, 또는 redistribute하기 위해 operation을 queue에서 제거할 때 READING, WRITING 상태의 operation state를 WRITE_QUEUED로 reset할 수 있도록 수정하였습니다.
> FIX: reset operation state in resend

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/BulkService.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeFindPositionWithGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetByPositionOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BaseStoreOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCountOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionCreateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionDeleteOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionExistOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionMutateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedExistOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionUpdateOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/GetAttrOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/SetAttrOperationImpl.java
debug 메소드 내부에 isDebugEnabled이 조건문으로 분기되어있어, debug 호출 시 한번 더 isDebugEnabled를 체크하는 부분을 삭제하였습니다.
> CLEANUP: isDebugEnabled and isInfoEnabled flag to print debug log

- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
checkstyle로 인한 build 실패로 해당 부분을 수정하였습니다.
> FIX: fail build on checkstyle

- docs/07-btree-API.md
#419 에 관한 pr입니다.
#424 에 반영된 내용들을 문서에 반영했습니다.
> CLEANUP: update btree api doc

- src/main/java/net/spy/memcached/MemcachedConnection.java
복제 클러스터에서 prevAddrMap == null 일 때 제거된 그룹을 제거하지 못하는 문제 https://github.com/naver/arcus-java-client/issues/451 PR 입니다.
prevAddrMap 필드를 제거하고, ArcusReplKetamaNodeLocator 로부터 node list 조회하는 방식으로 수정하였습니다.
> FIX: removed prevAddrMap field to update cachelist correctly.

- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/test/java/net/spy/memcached/MemcachedConnectionTest.java
https://github.com/naver/arcus-java-client/pull/454 PR에 이어서
ReconnectQueue 클래스 리팩토링 하였습니다.
> CLEANUP: refactored ReconnectQueue of MemcachedConnection

- .github/workflows/ci.yml
추후 README.md 뱃지에 추가하기 위해 workflow 이름을 간결하게 바꾸었습니다.
> CLEANUP: change workflow name to CI

- README.md
README.md에 CI, 라이센스 뱃지 추가하였습니다.
> DOC: add ci and license badge

- docs/06-map-API.md
- docs/07-btree-API.md
- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/collection/BTreeCreate.java
- src/main/java/net/spy/memcached/collection/BTreeInsert.java
- src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java
- src/main/java/net/spy/memcached/collection/BTreeUpsert.java
- src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java
- src/main/java/net/spy/memcached/collection/CollectionCreate.java
- src/main/java/net/spy/memcached/collection/CollectionInsert.java
- src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java
- src/main/java/net/spy/memcached/collection/ListCreate.java
- src/main/java/net/spy/memcached/collection/ListInsert.java
- src/main/java/net/spy/memcached/collection/MapCreate.java
- src/main/java/net/spy/memcached/collection/MapInsert.java
- src/main/java/net/spy/memcached/collection/SetCreate.java
- src/main/java/net/spy/memcached/collection/SetInsert.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
CollectionBulkInsert 와 CollectionPipedInsert 의 생성자 코드를 정리하였습니다.
> CLEANUP: remove createKeyIfNotExist field and duplicate codes in collection insert classes.

- src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
- src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
- src/main/java/net/spy/memcached/MemcachedClient.java
- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/MemcachedNode.java
- src/main/java/net/spy/memcached/MemcachedNodeROImpl.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/test/java/net/spy/memcached/MockMemcachedNode.java
node shutdown시 selection key를 cancel 하여 selector key에서 제거될 수 있도록 수정하였습니다.
> FEATURE: add closeChannel interface in MemcachedNode

- src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
- src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
updateHash() method 를 리팩토링하였습니다.
- insertHash(), removeHash() 두 메서드로 분리
- ketama hashpoint 얻는 작업을 별도 함수로 정의하여 호출
> CLEANUP: refactor updateHash() method of ArcusKetamaNodeLocator.

- src/main/java/net/spy/memcached/ops/MultiGetOperationCallback.java
- src/main/java/net/spy/memcached/ops/MultiGetsOperationCallback.java
- src/main/java/net/spy/memcached/ops/MultiOperationCallback.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
Migration - clone operations 사전 작업으로 Override annotation을 추가했습니다.
> INTERNAL: Add @Override annotations to migration related methods.

- src/main/java/net/spy/memcached/collection/BTreeSMGet.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationOldImpl.java
SMGet 연산의 migration 지원을 위해 사전 작업을 수행했습니다.
BTreeGetBulkImpl 클래스를 추가하여 migration 사전 작업을 수행한 것 처럼 BTreeSMGetImpl 클래스를 추가했습니다.
> INTERNAL: Prepare BTreeSMGet to clone operations.

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ops/CollectionGetOperation.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionGetOperationImpl.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
https://github.com/naver/arcus-java-client/pull/497 에서 빠진 부분을 수정했습니다.
> INTERNAL: Change the order of parameter subkey and flags.

- src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java
https://github.com/naver/arcus-java-client/pull/486#pullrequestreview-1008739907
리뷰 내용이 리팩토링 관련이라 사전 PR로 수정했습니다.
clone operations에서 추가되는 생성자는 clone operations PR에서 수정하도록 하겠습니다.
> CLEANUP: Refactored parameter lines of BTreeSMGet constructor.

- src/main/java/net/spy/memcached/OperationFactory.java
- src/main/java/net/spy/memcached/collection/BTreeGetBulk.java
- src/main/java/net/spy/memcached/collection/BTreeGetBulkImpl.java
- src/main/java/net/spy/memcached/collection/BTreeGetBulkWithByteTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeGetBulkWithLongTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGet.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetImpl.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithByteTypeBkeyOld.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkey.java
- src/main/java/net/spy/memcached/collection/BTreeSMGetWithLongTypeBkeyOld.java
- src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java
- src/main/java/net/spy/memcached/ops/BTreeGetBulkOperation.java
- src/main/java/net/spy/memcached/ops/BaseOperationFactory.java
- src/main/java/net/spy/memcached/ops/MultiBTreeGetBulkOperationCallback.java
- src/main/java/net/spy/memcached/ops/MultiBTreeSortMergeGetOperationCallback.java
- src/main/java/net/spy/memcached/ops/MultiCollectionBulkInsertOperationCallback.java
- src/main/java/net/spy/memcached/ops/MultiGetOperationCallback.java
- src/main/java/net/spy/memcached/ops/MultiOperationCallback.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeGetBulkOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
수정된 clone operation 로직입니다. 수정된 사항은 다음 코멘트에 남기도록 하겠습니다.
> INTERNAL: Clone operations to prepare migration.

- .github/workflows/ci.yml
#501 에 연속된 pr입니다.
pip 설치에 caching 하도록 하여 pip 설치 시간을 줄이도록 했습니다.
> FIX: add pip dependency install

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/ArcusClientPool.java
- src/test/manual/net/spy/memcached/collection/map/MopDeleteTest.java
- mkeyList를 통해 Map의 elements를 삭제할 수 있는 메소드를 추가하였습니다.
> INTERNAL: add asyncMopDelete method - delete by mkeyList

- src/main/java/net/spy/memcached/ArcusClientPool.java
#439 , #516
- CI fail을 토대로 CheckStyle 적용해 개선 완료하였습니다.
> FIX: adjust checkstyle to mopDelete()

- src/main/java/net/spy/memcached/collection/CollectionBulkInsert.java
- src/main/java/net/spy/memcached/collection/CollectionPipe.java
- src/main/java/net/spy/memcached/collection/CollectionPipedInsert.java
- src/main/java/net/spy/memcached/collection/CollectionPipedUpdate.java
- src/main/java/net/spy/memcached/collection/SetPipedExist.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionBulkInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedInsertOperationImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/CollectionPipedUpdateOperationImpl.java
redirect 사전 PR 입니다. itemCount - nextOpIndex == 1 조건문을 통해 pipe 연산의 마지막 커맨드를 처리하는 부분을 의미 있는 이름의 메소드로 대체했습니다. 대체 과정에서 중복된 코드를 추상 클래스로 통합하고 final 키워드를 붙일 수 있는 필드에 final 키워드를 붙였습니다.
> INTERNAL: Refactored CollectionPipedInsert, CollectionPipedUpdate and ColletionBulkInsert.

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkSetVariousTypeTest.java
- src/test/manual/net/spy/memcached/collection/map/MopServerMessageTest.java
final로 선언할 수 있는 필드를 final로 선언했습니다.
> FIX: Resolve final field warnings.

- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
Java 스타일 배열 선언은 다음과 같습니다.
```
Type[] arrayName;
```
> FIX: Resolve C-style array declaration warning.

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/test/java/net/spy/memcached/protocol/TCPMemcachedNodeImplTest.java
https://pvs-studio.com/en/docs/warnings/v6074/
위 문서에 warning에 대한 설명과 해결법이 있습니다.
> FIX: Resolve non-atomic modification of volatile variable warnings.

- src/test/manual/net/spy/memcached/collection/CollectionFutureTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeOldTest.java
- src/test/manual/net/spy/memcached/collection/btree/BopSortMergeTest.java
- src/test/manual/net/spy/memcached/ops/OperationStatusTest.java
- src/test/manual/net/spy/memcached/test/MutateWithDefaultTest.java
https://github.com/naver/arcus-java-client/issues/534
위 이슈 관련 PR 입니다.
> FIX: Call Future.get() in test setup.

- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/MigrationMonitor.java
- src/main/java/net/spy/memcached/MigrationState.java
- src/main/java/net/spy/memcached/MigrationType.java
지난 PR을 닫아야 새 PR을 열 수 있어서 지난 PR을 닫고 새 PR을 열였습니다.
> INTERNAL: Prepare to migration.

- src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
https://github.com/naver/arcus-java-client/issues/582
위 이슈 PR 입니다.
> FIX: Checkstyle violation

- src/main/java/net/spy/memcached/CacheManager.java
https://github.com/naver/arcus-java-client/issues/580
위 이슈 관련 PR 입니다.
> INTERNAL: Wait a second before reinit CacheMonitor or MigrationMonitor.

- .github/workflows/ci.yml
https://github.com/naver/arcus-java-client/issues/586
위 이슈 관련 PR 입니다.
> INTERNAL: Change CI command to detect Checkstyle violation.

- src/main/java/net/spy/memcached/MemcachedConnection.java
https://github.com/jam2in/arcus-works/issues/374
위 이슈를 해결한 커밋입니다.
> FIX: Fix operation redirection.

- src/main/java/net/spy/memcached/ops/Operation.java
- src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
> INTERNAL: Remove unnecessary flag 'moved' in Operation.

- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/RedirectHandler.java
- Migration LEAVE시 Cache List에서 빠질 때 Alter List에 있는지 검사하여 Alter List에 있으면 Operation을 캔슬하지 않도록 수정했습니다.
- Cache List에서 빠질 때 Migration에 의해 빠지는 것인지 Cache List에 의해 빠지는 것인지 구분하기 위해 enum 타입을 하나 추가했습니다.
- NodeLocator의 alterNodes 자료구조가 HashSet 이지만 MemcachedNode 타입에서 hashCode() 메소드를 구현하지 않아, 주소 값이 동일한 MemcachedNode 객체가 주어지는 경우에만 O(1) 탐색이 가능합니다.
- 임의의 MemcachedNode 객체가 주어졌을 때 해당 객체가 alterNodes 안에 있는지 O(1) 탐색하기 위해 HashMap<SocketAddress, Boolean> 타입의 자료구조 isInAlterNodes 객체를 추가했습니다.
- alterNodes에 MemcachedNode가 추가되면 해당 객체의 SocketAddress를 key로 하고 value를 true로 하여 isInAlterNodes에 넣습니다.
- alterNodes에서 MemcachedNode가 제거되면 해당 객체의 SocketAddress를 key로 하고 value를 false로 하여 isInAlterNodes에 넣습니다.
- IO Thread에 의한 read와 ZK Thread에 의한 write가 동시에 발생할 수 있으므로 ConcurrentHashMap과 AtomicBoolean을 사용했습니다.
> FIX: Not to cancel operations in node that not in cache list but in alter  list.

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
https://github.com/naver/arcus-java-client/issues/591
위 이슈 PR 입니다.
> FIX: Fix readQ, writeQ size error.

- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/ops/Operation.java
- src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
MemcachedNode의 API인 addOpToInputQ, insertOp, resetOperation 메소드와 관련된 리팩토링을 진행했습니다.
> INTERNAL: Refactoring addOpToInputQ, insertOp, resetOperation.

- src/main/java/net/spy/memcached/protocol/ascii/OperationImpl.java
창섭사원과 함께 고민해본 사항은 다음과 같습니다.
-  if-else 블록을 return과 continue를 통해 펼쳤습니다.
- 기존 방식은 이렇습니다.
1. 출력된 결과의 시작을 파싱하여 if-else를 통해 ERROR, CLIENT_ERROR, SERVER_ERROR로 시작하면 각각 enum 반환
2. 반환된 enum을 기준으로 부모 클래스에 정의된 handleError 호출 및 if-else로 사용자 정의 예외 던짐
- 변경된 방식은 이렇습니다.
1. enum에 각각 해당 문자열 필드 매칭
2. enum.values() 메소드를 통해 모든 enum 클래스 순회
3. enum에 매칭된 문자열을 만족하면, for문 내부에서 바로 예외 생성
4. 마지막에 예외 던짐
- 바뀔 CRLF 검사 로직
1. 커서를 기준으로 연속된 문자가 CRLF를 만족하면 true를 반환시킵니다.
2. CR, LF둘중 하나만 만족할 경우 assert를 통해 예외를 던집니다.
3. 둘 다 아닐 경우 false를 반환합니다.
- true일 때
- 줄바꿈이 일어났으므로 offset을 저장하고 반복문 break;
- false일 때
- byte buffer에 해당 문자 write
```java
while (data.remaining() > 0) {
if (getState() == OperationState.COMPLETE || isReplicationOrMigration()) {
return;
}
if (readType == OperationReadType.DATA) {
handleRead(data);
continue;
}
int …
```
> INTERNAL: refactor OperationImpl.readFromBuffer method

- src/main/java/net/spy/memcached/ArcusClient.java
- https://github.com/jam2in/arcus-works/issues/388 에 대한 PR입니다.
> INTERNAL:fix piped op futrue get

- src/main/java/net/spy/memcached/MemcachedConnection.java
- src/main/java/net/spy/memcached/MemcachedNode.java
- src/main/java/net/spy/memcached/MemcachedNodeROImpl.java
- src/main/java/net/spy/memcached/TimedOutMessageFactory.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/test/java/net/spy/memcached/MockMemcachedNode.java
서로 다른 정보를 출력하는 MemachedNode.toString() 메소드와 MemcachedNode.getStatus() 메소드를 통합했습니다.
> ENHANCE: Enhance MemcachedNode.toString().

- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/CacheMonitor.java
- src/main/java/net/spy/memcached/MemcachedConnection.java
https://github.com/jam2in/arcus-works/issues/378
위 이슈 관련 PR 입니다.
> FIX: Fix migration JOIN bug.

- src/main/java/net/spy/memcached/CacheManager.java
- https://github.com/jam2in/arcus-works/issues/402 기반 PR입니다.
- 현재는 버전 정보를 아래와 같이 소수점까지 함께 보여주는 구조입니다.
1. 11.0.4
2. 1.8.0
- 자바 버전을 표기하는 방식에 대해서 의견 있으시면 남겨주세요
> ENHANCE: Added a JRE version in client_list znode.

- src/main/java/net/spy/memcached/internal/BulkOperationFuture.java
- https://github.com/jam2in/arcus-works/issues/405 기반 PR입니다.
> INTERNAL: Overriding idDone() in BulkOperationFuture

- docs/03-key-value-API.md
https://github.com/jam2in/arcus-works/issues/410 관련 PR입니다.
> DOC:Fixed how to receive the result value of asyncStroeBulk Future.

- src/main/java/net/spy/memcached/ArcusClient.java
https://github.com/jam2in/arcus-works/issues/411 관련 PR입니다.
> Fix: getVersion method concurrency error.

- pom.xml
- src/main/java/net/spy/memcached/ArcusClientPool.java
- src/main/java/net/spy/memcached/MemcachedClient.java
- src/main/java/net/spy/memcached/MemcachedClientIF.java
- src/main/java/net/spy/memcached/OperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/AsciiMemcachedNodeImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/AsciiOperationFactory.java
- src/main/java/net/spy/memcached/protocol/ascii/BaseGetOpImpl.java
- src/main/java/net/spy/memcached/protocol/ascii/ReactiveGetOperationImpl.java
- src/main/java/net/spy/memcached/protocol/binary/BinaryOperationFactory.java
- src/main/java/net/spy/memcached/reactive/internal/ReactiveOperationFuture.java
- src/main/java/net/spy/memcached/reactive/internal/SpyCompletableFuture.java
- src/main/java/net/spy/memcached/transcoders/TranscodeService.java
asyncGet에서 CompletableFuture를 반환하도록 합니다.
- resolve https://github.com/jam2in/arcus-works/issues/394
- resolve https://github.com/jam2in/arcus-works/issues/397
> INTERNAL: change asyncGet to perform concurrently

- src/test/manual/net/spy/memcached/emptycollection/PipedBulkInsertSetWithAttrTest.java
TEST: fix testcase in PipedBulkInsertSetWithAttrTest.
> TEST: fix testcase in PipedBulkInsertSetWithAttrTest.

- src/main/java/net/spy/memcached/internal/BulkGetFuture.java
기존의 bulk 관련 Future와 동일한 로직을 수행하도록 변경하였습니다.
> FIX: Fix isCancelled,cancel method logic in BulkGetFuture.

- src/main/java/net/spy/memcached/ArcusClient.java
기존의 `groupingKeys` 메서드의 로직은 Map, Entry, index 변수의
의미가 불분명하게 사용되어 로직을 파악하기 어렵다.
해당 메서드는 가장 쉽게 설명하면 keyList로 들어온 
key들의 해당하는 `MemcachedNode`를 찾아주는 메서드이다.
다만, key마다 동일한 `MemcachedNode` 를 가질 수도 있다.
이러한 경우 `MemcachedNode`가 가지는 
key List의 크기는 인자인 `groupSize`가 최대 크기이다.
**즉, groupSize보다 key List의 크기가 클 경우 새로운 Entry 인스턴스를 생성**한다.
https://github.com/jam2in/arcus-works/issues/381
> INTERNAL: refactoring groupingKeys method logic in ArcusClient.

- src/main/java/net/spy/memcached/ArcusClient.java
> FIX: Change keyGroup size comparing logic in groupingkeys method.

- src/main/java/net/spy/memcached/protocol/BaseOperationImpl.java
https://github.com/naver/arcus-java-client/pull/643
> INTERNAL: Remove volatile keyword and change cause format.

- src/main/java/net/spy/memcached/collection/BTreeGet.java
INTERNAL: Change comments in BTreeGet.
> CLEANUP: Change comments in BTreeGet.

- src/main/java/net/spy/memcached/collection/BTreeInsertAndGet.java
- src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java
BTreeInsertAndGetOpImpl내의  handleRead() 로직을 
최근 변경된 bop get 로직과 동일하게 수정한다.
> INTERNAL: Change handleRead logic in BTreeInsertAndGetOpImpl.

- src/main/java/net/spy/memcached/ArcusClient.java
- src/main/java/net/spy/memcached/ArcusClientIF.java
- src/main/java/net/spy/memcached/ArcusClientPool.java
- src/test/manual/net/spy/memcached/collection/btree/BopOverflowActionTest.java
- src/test/manual/net/spy/memcached/collection/list/LopGetTest.java
- src/test/manual/net/spy/memcached/collection/map/MopDeleteTest.java
- src/test/manual/net/spy/memcached/collection/map/MopGetTest.java
- src/test/manual/net/spy/memcached/emptycollection/GetWithDropSetTest.java
INTERNAL: Add comment in collection get apis.
추가된 api들을 주석 처리 하였습니다.
> INTERNAL: Add comment in collection get apis.

- ChangeLog
- README.md
- docs/arcus-java-client-getting-started.md
- pom.xml
ChangeLog는 메일로 논의한 사항과 같습니다.
~이 외에 자체 maven repository 업로드를 위해 `com.navercorp.arcus`를 `com.jam2in.arcus`로 변경했습니다.~
> version 1.13.4

- .github/workflows/ci.yml
Github action의 python 설치를 위한 version 변경 PR
> TEST: Change setup python2.7 version.

- ChangeLog
> DOC: Fix release date in ChangeLog.

- src/main/java/net/spy/memcached/ArcusClient.java
현재 smget api의 콜백은 여러가지 메서드들을 구현한다.
특히 receivedStatus()의 경우 여러 op들에 의해
생성된 eachResult들을 merge-sort하는 로직을 가진다.
해당 로직의 구현이 읽기 쉽지 않아 이를 좀 더 readable한 구현으로 변경한다.
또한 대체 가능한 변수인 stopcollect, processSMGetCount 등을 제거한다.
https://github.com/jam2in/arcus-works/issues/438
> ENHANCE: Optimize smget callback method logic.

- .github/workflows/ci.yml
Docker의 경우 github action에서 기본 설치되어있습니다.
> TEST: Remove docker install step.

- src/test/java/net/spy/memcached/ProtocolBaseCase.java
간헐적으로 실패하는 테스트 코드를 수정했습니다.
1만개의 Operation을 요청해두고, shutdown을 수행하는데 걸리는 시간이 700ms를 초과해야 통과하는 테스트입니다.
1만개의 Operation으로는 간헐적으로 테스트 코드가 실패하여, 100만개의 Operation을 요청해두도록 했습니다.
> TEST: Fix intermittent test failure.

- src/main/java/net/spy/memcached/AddrUtil.java
- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- src/main/java/net/spy/memcached/util/DefaultKetamaNodeLocatorConfiguration.java
- src/test/java/net/spy/memcached/MockMemcachedNode.java
https://github.com/jam2in/arcus-works/issues/471
위 이슈를 해결하는 PR 입니다.
> INTERNAL: Remove "/<unresolved>" from InetSocketAddress.toString() for backward compatibility on JDK 14+

- src/main/java/net/spy/memcached/internal/result/SMGetResultOldImpl.java
Old SMGetResult의 Merge 메소드에 주석을 추가했습니다.
> INTERNAL: Add comments to old SMGetResult merge method.

- src/main/java/net/spy/memcached/TimedOutMessageFactory.java
https://github.com/jam2in/arcus-works/issues/489
> INTERNAL: Add Not Connected log in TimoutExceptionMsg.

- src/main/java/net/spy/memcached/MemcachedConnection.java
> CLEANUP: remove outdated comment

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature-refactoring-request.md
- .github/PULL_REQUEST_TEMPLATE.md
- issue template과 pr template을 추가합니다.
> DOCS: create issue/pr templates

- src/main/java/net/spy/memcached/MemcachedClient.java
- https://github.com/jam2in/arcus-works/issues/516
- 기존에 asyncGetBulk, asyncGetsBulk 메서드에서 GET_BULK_CHUNK_SIZE를 기준으로 나눈 Collection들의 리스트를  `Map<MemcachedNode, List<Collection<String>>>`으로 저장하던 것을 `Map<MemcachedNode, List<String>>` 로 관리하도록 합니다.
> REFACTOR: split chunks by sublist in asyncGet

- docs/07-btree-API.md
- https://github.com/jam2in/arcus-works/issues/478
- 반환 값이 실제와 문서와 다른 부분을 수정합니다.
> DOCS: fix mismatched return value

- src/main/java/net/spy/memcached/protocol/ascii/BTreeSortMergeGetOperationImpl.java
- https://github.com/jam2in/arcus-works/issues/343
- 기존에는 space를 발견할 때마다 `split` 함수를 호출합니다.
- `if (smGet.headerReady(spaceCount))`일 때만 호출하도록 변경했습니다.
- 기존에 `chunk[3]`이 `eflag`인지 확인하기 위해 이중 중첩 if문을 사용합니다.
- 2개의 조건을 and 연산자로 합쳤습니다.
- `byteBuffer.toString()`을 따로 2번 호출합니다.
- 처음에 결과(`itemHeader`)를 저장하고, 이를 `decodeItemHeader`에서 재사용하도록 합니다.
> REFACTOR: Reduce split method calling in smget read

- .gitignore
- .idea/codeStyles/Project.xml
- .idea/codeStyles/codeStyleConfig.xml
- src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
- src/main/java/net/spy/memcached/protocol/ascii/StoreOperationImpl.java
- src/main/java/net/spy/memcached/util/BTreeUtil.java
- src/test/java/net/spy/memcached/ProtocolBaseCase.java
- src/test/java/net/spy/memcached/RedistributeFailureModeTest.java
- src/test/java/net/spy/memcached/TimeoutTest.java
- src/test/manual/net/spy/memcached/test/MultiNodeFailureTest.java
- https://github.com/jam2in/arcus-works/issues/547
- `.idea/codeStyles/Project.xml` : 설정 파일입니다.
- `.idea/codeStyles/codeStyleConfig.xml`
-  설정 파일을 IDE가 자동으로 인식하여 사용하게 해주는 파일입니다.
- 예전에 처음 arcus-java-client에 import 설정을 적용할 때 이 파일을 포함하지 않아서 개발자마다 위의 `Project.xml` 파일을 불러오는 과정이 필요했습니다.
- 이 파일이 있으면 clone을 받을 때마다 기본값으로  `Project.xml` 설정이 사용 상태가 됩니다.
> INTERNAL: Adjust new auto import setting.

- src/main/java/net/spy/memcached/ArcusKetamaNodeLocator.java
- src/main/java/net/spy/memcached/ArcusReplKetamaNodeLocator.java
https://github.com/jam2in/arcus-works/issues/558
중복으로 호출되는 ketamaNodes TreeMap에 대한 조회를 최적화하였다.
> ENHANCE: Change getNodeForKey logic in locator.

- src/main/java/net/spy/memcached/MemcachedClient.java
https://github.com/jam2in/arcus-works/issues/584
동기적으로 동작하는 mutate 메서드가 내부적으로 Future를 사용하도록 변경
> REFACTOR: sync mutate api to use OperationFuture.

- src/main/java/net/spy/memcached/internal/BulkGetFuture.java
- https://github.com/naver/arcus-java-client/pull/768#discussion_r1668408851 
- internalGet() 메소드를 리팩토링합니다.
> CLEANUP: Refactored internalGet() method of BulkGetFuture.

- docs/user_guide/11-client-notes.md
- https://github.com/naver/arcus-java-client/issues/740
- DNS Cache TTL 설정 관련 내용을 추가합니다.
> DOC: Add DNS Cache TTL notice.

- docs/user_guide/06-map-API.md
- mop upsert API에 대한 문서를 추가합니다.
> DOCS: add mop upsert API

- ChangeLog
- README.md
- docs/arcus-java-client-getting-started.md
- pom.xml
> version 1.14.0

- .github/workflows/ci.yml
- 
- CI를 수행하지 않아도 되는 경우에는 수행하지 않습니다.
> TEST: Do not run CI if the PR is in draft.

- src/main/java/net/spy/memcached/protocol/ascii/BTreeInsertAndGetOperationImpl.java
- naver/arcus-memcached#785
- https://github.com/naver/arcus-java-client/commit/186510d5d5fdd494bd3ff6da78f14b5a617ce945
- trimmed data 응답 주석을 변경합니다.
> INTERNAL: Update comment of getrim response

- src/main/java/net/spy/memcached/internal/result/SMGetResult.java
- src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
- https://github.com/naver/arcus-java-client/issues/770
- 적절한 동기화 기법을 적용합니다.
> FIX: Apply appropriate synchronization on fields of SMGetResult class.

- src/main/java/net/spy/memcached/CacheManager.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- deprecated된 repl 옵션 설정 삭제
- 2017년 쯤 deprecated 되어서 제거해도 될 것 같습니다.
- public -> defualt로 접근 제어자 변경
> REFACTOR: Remove deprecated repl setter.

- src/main/java/net/spy/memcached/plugin/LocalCacheManager.java
- https://github.com/jam2in/arcus-works/issues/398
- 생성한 이후로 변하지 않는 변수는 final로 설정합니다.
- name 필드는 사용되지 않으므로 제거합니다.
- 아래 두 메서드는 현재 사용되지 않으므로 제거합니다.
- asyncGet(final String key)
- put(String k, Future<T> future, long timeout)
> CLEANUP: tidy LocalCacheManager

- src/main/java/net/spy/memcached/compat/CloseUtil.java
- 
- logger 필드를 final로 선언할 수 있는 경우 final로 선언합니다.
> INTERNAL: Make logger final field.

- src/main/java/net/spy/memcached/MigrationMonitor.java
- src/main/java/net/spy/memcached/util/CacheLoader.java
- src/test/java/net/spy/memcached/CASMutatorTest.java
- src/test/java/net/spy/memcached/LongClientTest.java
- src/test/java/net/spy/memcached/ProtocolBaseCase.java
- src/test/java/net/spy/memcached/TimeoutTest.java
- 
- 익명함수를 람다로 변경하여 코드를 단순화합니다.
> CLEANUP: replace anonymous function into lambda

- src/main/java/net/spy/memcached/CacheManager.java
https://github.com/jam2in/arcus-works/issues/598
1. 앞선 PR (https://github.com/naver/arcus-java-client/pull/600/files)에 의해 
alter_list의 경우에도 validation이 진행되도록 변경되었다.
alter_list는 leave인 경우 이미 validation이 진행되었고, 
join인 경우는 미래에 진행할 예정이라 검증을 굳이 할 필요가 없다.
그래서 alter_list에서 복제 검증은 수행하지 않도록 변경하였다.
(기존엔 getSocketAddrList 메서드 내 로직에서 검증 수행합니다.)
> INTERNAL: Remove the incorrectly added repl validation when cache list changed.

- .github/workflows/ci.yml
- https://github.com/jam2in/arcus-works/issues/568#issuecomment-2406254086
- 기존 8, 11, 17 버전에서 수행되던 ci를 8, 21 버전에서 수행하도록 하였습니다.
> INTERNAL: Update jdk ci version

- src/main/java/net/spy/memcached/CacheManager.java
- 
- Sonarlint 의 수정사항을 반영하였습니다.
- 같은 예외처리를 하는 exception 처리를 하나로 통합하였습니다.
- 오버라이드하는 함수에 대하여 `@Override` 메서드를 붙였습니다.
- snake case 의 변수명을 camel case 로 변경하였습니다.
- 지역 변수명이 상위의 변수명과 겹쳐 변수명을 수정하였습니다.
> CLEANUP: Refactor CacheManager

- src/main/java/net/spy/memcached/StatisticsHandler.java
https://github.com/jam2in/arcus-works/issues/615
mBean이 수집될 때, 발생하는 info 레벨의 로그를 debug로 변경합니다.
> INTERNAL: Change mbean retrival log level.

- src/main/java/net/spy/memcached/CASMutator.java
- src/main/java/net/spy/memcached/ConnectionFactoryBuilder.java
- src/test/java/net/spy/memcached/AddrUtilTest.java
- src/test/java/net/spy/memcached/LongClientTest.java
- src/test/java/net/spy/memcached/ProtocolBaseCase.java
- src/test/java/net/spy/memcached/transcoders/BaseTranscoderCase.java
- src/test/manual/net/spy/memcached/test/MemoryFullTest.java
- https://github.com/jam2in/arcus-works/issues/576
- IllegalArgumentException / Assertions.assertXXX 으로 전환할 수 있거나 assert문을 제거할 수 있는 부분을 고쳤습니다.
- ~상태 검증을 위해 IllegalStateException을 반환하는 부분은 다음 PR로 올리고자 합니다.~ 크게 중요한 작업이 아닌 것 같아 보류하겠습니다.
> INTERNAL: change assert statement into IllegalArgumentException or Assertions methods

- src/main/java/net/spy/memcached/collection/BTreeFindPosition.java
- src/main/java/net/spy/memcached/collection/BTreeFindPositionWithGet.java
- src/main/java/net/spy/memcached/collection/BTreeGet.java
- src/main/java/net/spy/memcached/collection/BTreeGetByPosition.java
- src/main/java/net/spy/memcached/collection/CollectionDelete.java
- src/main/java/net/spy/memcached/collection/CollectionGet.java
- src/main/java/net/spy/memcached/collection/CollectionInsert.java
- src/main/java/net/spy/memcached/collection/CollectionUpdate.java
- src/main/java/net/spy/memcached/collection/SetDelete.java
- src/main/java/net/spy/memcached/collection/SetGet.java
- https://github.com/jam2in/arcus-works/issues/666
- 내부적으로 사용하기 위한 용도인 command class들에서 사용되지 않는 메서드를 제거합니다.
> CLEANUP: remove unused methods in command classes

- ChangeLog
- jam2in/arcus-works#708
- ChangeLog 형식을 수정합니다.
> DOCS: Update ChangeLog format

- docs/user_guide/10-log-message.md
- naver/arcus-c-client#366
- 앙상블 리스트 주소 예시를 변경합니다.
"dev.arcuscloud.nhncorp.com:17288" -> "dev.arcuscloud.jam2in.com:2181"
> DOCS: Change an ensemble address example

- docs/user_guide/02-arcus-java-client.md
- https://github.com/jam2in/arcus-works/issues/695
- ConnectionFactoryBuilder에 대한 문서를 수정합니다.
- https://github.com/oliviarla/arcus-java-client/blob/docs2/docs/user_guide/02-arcus-java-client.md#connectionfactorybuilder-%EC%84%A4%EC%A0%95
> DOC: update ConnectionFactoryBuilder docs

- src/main/java/net/spy/memcached/internal/result/SMGetResultImpl.java
- https://github.com/jam2in/arcus-works/issues/720#issuecomment-2965124112
- refineTrimmedKeys 메서드를 리팩토링하였습니다.
> CLEANUP: Make refineTrimmedKeys easier to understand

- src/main/java/net/spy/memcached/protocol/TCPMemcachedNodeImpl.java
- https://github.com/jam2in/arcus-works/issues/728
-
> CLEANUP: Use direct buffers in TCPMemcachedNodeImpl

- src/main/java/net/spy/memcached/DefaultConnectionFactory.java
- src/main/java/net/spy/memcached/transcoders/CollectionTranscoder.java
- src/main/java/net/spy/memcached/transcoders/SerializingTranscoder.java
- src/test/java/net/spy/memcached/ConnectionFactoryBuilderTest.java
- src/test/java/net/spy/memcached/ProtocolBaseCase.java
- src/test/java/net/spy/memcached/transcoders/SerializingTranscoderTest.java
- src/test/manual/net/spy/memcached/MultibyteKeyTest.java
- src/test/manual/net/spy/memcached/bulkoperation/BulkStoreTest.java
- src/test/manual/net/spy/memcached/collection/CollectionMaxElementSize.java
- src/test/manual/net/spy/memcached/collection/transcoder/CollectionTranscoderTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolSetDeleteTest.java
- src/test/manual/net/spy/memcached/emptycollection/ProtocolSetExistTest.java
- https://github.com/jam2in/arcus-works/issues/732
- 이슈 본문 내용대로 SerializingTranscoder와 CollectionTranscoder를 하나의 Transcoder로 통합하였습니다.
> INTERNAL: Merge KV and collection transcoders

- src/main/java/net/spy/memcached/transcoders/JsonSerializingTranscoder.java
- src/test/java/net/spy/memcached/transcoders/JsonSerializingTranscoderTest.java
- 
- JsonSerializingTranscoder 클래스를 주석 처리합니다.
> INTERNAL: Comment out JsonSerializingTranscoder class

- docs/user_guide/02-arcus-java-client.md
- 
- CollectionTranscoder 사용 예시를 제거합니다.
> DOC: Remove the usage example of deprecated class, CollectionTranscoder

- ChangeLog
- README.md
- docs/arcus-java-client-getting-started.md
- pom.xml
- 
- version 1.15.0 커밋입니다.
- https://github.com/naver/arcus-java-client/pull/969 PR이 먼저 반영되어야 합니다.
> version 1.15.0
